### ISSUE TITLE
Rename plugin to cakephp/authentication

### ISSUE THREAD

**Issue by dereuromark** [cakephp/authentication#10]
Shouldnt the whole plugin then be renamed from

    cakephp/middleware-authentication

to 

    cakephp/authentication

?

I mean Middleware is a specific pattern and implementation detail that does not need to be reflected in the name. How it is done internally should not matter to "what it does" which should be reflected in the name.

Refs https://github.com/cakephp/authentication/pull/9

**Comment by burzum** [comment]
Agreed. 👍
