### ISSUE TITLE
When failing to authenticate Results errors is empty

### ISSUE THREAD

**Issue by davidyell** [cakephp/authentication#100]
## What I did
Setup my middleware as per the docs, and then tried to authenticate with invalid credentials.

## What happened
The middleware set the attribute in the request

## What I tried to do
I wanted to get the reason why it failed with `$request->getAttribute('authentication')->getResult()->getErrors()`.

## What I expected to happen
[I would assume that it'd return a string](https://github.com/cakephp/authentication/blob/master/src/Result.php#L67-L74) reason for the `-1` response code, which is `FAILURE_IDENTITY_NOT_FOUND`. So something like 'Unable to identify' or similar.

## What actually happened
I got an array with just the authenticators as a key and no string errors.
```
object(Authentication\Result)[177]
  protected '_code' => int -1
  protected '_identity' => null
  protected '_errors' => 
    array (size=2)
      'Authentication.Orm' => 
        array (size=0)
          empty
      'Authentication.Token' => 
        array (size=0)
          empty
```

## Code
It seems that the identifier isn't returning any errors to pass through to the result.
https://github.com/cakephp/authentication/blob/master/src/Authenticator/TokenAuthenticator.php#L116

**Comment by cleptric** [comment]
Duplicate of #84

**Comment by davidyell** [comment]
Right, so it should be called 'additionalErrors' or something then I guess? That sure is misleading when looking at the code.
