### ISSUE TITLE
Add a Token authenticator?

### ISSUE THREAD

**Issue by burzum** [cakephp/authentication#11]
It's pretty common these days to work with APIs that have a token.

* Look in the header for a token like JWT
* Look in the request query params for a token
* Allow a callback for the token extraction from the request
* Add an OrmToken identifier

The only thing somebody would have to do in this case for the JWT token is to implement a JWT token identifier. We could provide it as well and suggest the JWT lib in the composer.json. JWT out of the box would be nice.

Add it or not? :)

**Comment by dereuromark** [comment]
Would that replace `ADmad/JwtAuth` plugin of https://github.com/FriendsOfCake/awesome-cakephp#authentication-and-authorization ?

**Comment by burzum** [comment]
Yes

**Comment by burzum** [comment]
See https://github.com/cakephp/authentication/pull/17

**Comment by burzum** [comment]
Merged #17
