### ISSUE TITLE
Datasource backend proposal.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/authentication#112]
In #109 "backend" idea was introduced. I was wondering if we could transform this idea into kind of a pattern.

Currently both `OrmIdentifier` and `TokenIdentifier` (and identifiers that extend it) depend on ORM but do it differently. OrmIdentifier is an identifier build especially for identifying users by password using CakePHP ORM. TokenIdentifier can be extended and use other methods of token verification. Implementations differ but the idea is the same: query the ORM (or any other datasource) with given conditions (username/password or token) and return an identity (EntityInterface in this case).

I was thinking we could enhance this and make it easier to integrate with other ORMs.

My idea is to add `Authentication\Identifier\Backend\DatasourceInterface`:

```php
interface DatasourceInterface {
    //return value should be ArrayAccess instead of cake EntityInterface
    public function find(array $conditions): ArrayAccess;
}
```

And implement it for our ORM:
```php
//draft implementation
class OrmBackend implements DatasourceInterface {
    public function find(array $conditions) {
        return $this->table->find()->where($conditions)->first();
    }
}
```

Now both `OrmIdentifier` and `TokenIdentifier` could use this in order to query an identity from database (or any other datasource). 

For example:
```php
//TokenIdentifier
$identity = $this->backend->find([$tokenField => $token]);
...
//OrmIdentifier
$identity = $this->backend->find([$usernameField => $username]);
//password check etc
...
```

Developers could implement adapters (*backends*) for custom ORMs and still use those identifier classes.

I think `OrmIdentifier` should be then renamed to `PasswordIdentifier` to better reflect what this does since it would no longer be ORM dependent.

**Comment by dereuromark** [comment]
+1 for PasswordIdentifier

**Comment by cleptric** [comment]
Keep in mind that the `OauthAuthenticator` could also do an ORM lookup without a password as we don't have one in place in this case.

**Comment by burzum** [comment]
> I was thinking we could enhance this and make it easier to integrate with other ORMs.

Honestly, except showing off how well it is abstracted I have doubts that anyone ever is using this with another ORM. SF and Laravel guys will stick to their stack and tools.

For any other person I feel this lib still has to many dependencies:

```
        "cakephp/core": "~3.4",
        "cakephp/datasource": "~3.4",
        "cakephp/event": "~3.4",
        "cakephp/utility": "~3.4",
```

I would be happy if we could get away without the event and utility at least if possible. Core might be easy to drop if we do a conditional check if the `App` class is present. AFAIK it is only used for the locator to load the classes. If we accept a FQN for the class and check for `App` being present we could get away without the core dependency?

If we don't rely on the EventManager trait we could make the event dependency optionally as well by checking if it is present or not and use the EventManager directly vs the Trait.

**Comment by robertpustulka** [comment]
@burzum `cakephp/event` could be suggest only if you plan to use AuthenticateComponent. You don't a component while working with anything other than CakePHP, so you don't need our event dispatcher as well.

`cakephp/datasource` is needed for `EntityInterface` but this dependency could probably be dropped in favor of `ArrayAccess`.

That leaves `cakephp/core` for `App:className()` and `InstanceConfigTrait` and `cakephp/utility` for `Hash` and `Security`.

**Comment by burzum** [comment]
> cakephp/datasource is needed for EntityInterface but this dependency could probably be dropped in favor of ArrayAccess.

@robertpustulka we need to discuss this with @markstory.

Let's make `cakephp/event` a suggested dependency then? It should be present in any Cake app anyway.

We could get rid off `App:className()` as I proposed but I doubt we can work around the config trait and hash and security.

**Comment by robertpustulka** [comment]
@burzum in `JwtAuthenticator` `Security` is optional and loaded only if there's no `secretKey` provided. It's also used in `WeakPasswordHasher` but AFAIR this is a legacy hasher for old cake apps.

`Hash` is used only in a component.

So IMO `cakephp/utility` could also be a suggested dep.

**Comment by burzum** [comment]
@robertpustulka if we make them suggested we should add a section to the docs that describes the cases when they're needed.

**Comment by ADmad** [comment]
> cakephp/datasource is needed for EntityInterface but this dependency could probably be dropped in favor of ArrayAccess.

:+1: 

> As for non-cake developers using this plugin. If we make it easier for them to use it in their environment, there's a bigger chance they would, I believe :)

:+1: 

> It's also used in WeakPasswordHasher but AFAIR this is a legacy hasher for old cake apps.

How about we just drop `WeakPasswordHasher`?  It was mainly added in cakephp 3.x for easy transitioning from 2.x.  The probability of someone still using old hashing scheme and wanting to use this plugin would be pretty low I think. They could still make their own password hasher class anyway if they wan to.

**Comment by robertpustulka** [comment]
@ADman I'm currently moving 2.x app to 3.4 so I'm happy this legacy hasher is there ;)

**Comment by ADmad** [comment]
@robertpustulka Okay :)

**Comment by inoas** [comment]
But we could deprecate it for 4.0 none-the-less?

**Comment by burzum** [comment]
> How about we just drop WeakPasswordHasher? 

Let's rename it to Cake2LegacyPasswordHasher for the time being? Makes it's purpose a lot more clear?

**Comment by dereuromark** [comment]
`LegacyPasswordHasher` suffices as name IMO.

**Comment by robertpustulka** [comment]
OK, I'm starting a draft PR.

**Comment by robertpustulka** [comment]
I think that moving dependencies to `suggest` needs another PR so we don't mix the ideas.

For dependencies PR we need to:
-  Move cakephp/event to suggest
-  Rename WeakPasswordHasher and modify code to check if Security class exists
-  Move cakephp/utility to suggest 
-  What to do about cakephp/datasource and EntityInterface?

**Comment by cleptric** [comment]
@robertpustulka Which identifier should I use after the refactoring for the `OauthAuthenticator`?
Do I have to create a new one?

**Comment by robertpustulka** [comment]
@cleptric `OauthAuthenticator` would return some token? Maybe extend TokenAuthenticator?

**Comment by cleptric** [comment]
@robertpustulka This depends on the Provider (Twitter, Facebook,..) you are using. So it could be a mixture of username and email, an id or something else.
So I'm not sure if a generic OrmIdentifier is a bad thing to have.

**Comment by robertpustulka** [comment]
@cleptric You must identify a user by something: token, password, username, a combination of some of them. Currently `OrmIdentifier` identifies by password so I'm afraid it wouldn't meet your needs.

But a generic identifier could do the job. It's a matter of configuring which fields should be queried in a datasource.


On the other hand I don't think that you should worry about identifiers while implementing authenticator at all. These are seperate things. A developer could add a number of identifiers that would identify a user depending on what provider they choose.

**Comment by markstory** [comment]
> > cakephp/datasource is needed for EntityInterface but this dependency could probably be dropped in favor of ArrayAccess.
>
> @robertpustulka we need to discuss this with @markstory.

Wouldn't this also imply that the 'identity' available on authentication results would also be `ArrayAccess`? Is that interface going to give people enough functionality to make identities useful?

I'm not sure 'backend' is a good descriptor of what this new class type does. It sounds like an 'identity locator' or 'identity resolver'

**Comment by robertpustulka** [comment]
> Wouldn't this also imply that the 'identity' available on authentication results would also be ArrayAccess? Is that interface going to give people enough functionality to make identities useful?

@markstory yes it would. Data returned from CakePHP ORM would still be `EntityInterface` so if someone needed this they could do `instanceof` check on that. AFAIR `AuthComponent` kept identity data as a simple array.

> I'm not sure 'backend' is a good descriptor of what this new class type does. It sounds like an 'identity locator' or 'identity resolver'

Yes, this is a WIP name, I was inspired by `Backend` namespace added in LDAP PR. I could refactor both `Backend` namespace and `Datasource` suffix into consistent `Locator` or `Resolver` namespace. So that would produce `Authentication\Identifier\Resolver\ResolverInterface` and `OrmResolver` accordingly.

**Comment by markstory** [comment]
>  AFAIR AuthComponent kept identity data as a simple array.

It does currently. But its a frequently complaint that AuthComponent's user data is a basic array.

**Comment by robertpustulka** [comment]
What people do with authenticated identities that something more that array or ArrayAccess is needed?

**Comment by markstory** [comment]
In the past people have requested the ability to use their entity methods on the user data stored in the session.

**Comment by robertpustulka** [comment]
@markstory
They still can using OrmResolver. It would return EntityInterface. The question is should we force third party resolvers to return entities or maybe ArrayAccess will suffice?

**Comment by ADmad** [comment]
I am of the same opinion as @robertpustulka. Let the OrmResolver return entity but don't force identity object to implement `EntityInterface`, just keep it `ArrayAccess`.

**Comment by robertpustulka** [comment]
So if nobody is against it I'm going to change checks from `instanceof EntityInterface` to `instanceof ArrayAccess`. The `EntityInterface` return value of `OrmResolver` will remain. 
This will also mean dropping `cakephp/datasource` dependency. It will be loaded with `cakephp/orm` anyway if someone decides to use CakePHP ORM backend.

**Comment by markstory** [comment]
@robertpustulka Good point about third party/non-orm resolvers. ArrayAccess will have to do for now.

**Comment by burzum** [comment]
Done

- [x] Rename WeakPasswordHasher and modify code to check if Security class exists
- [x] Move cakephp/utility to suggest

**Comment by robertpustulka** [comment]
Resolvers are merged and dependency issues has been addressed.
