### ISSUE TITLE
FormAuthenticator checks for username password for every request

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#13]
Currently the `FormAuthenticator` checks for username password for every request which is undesirable. It would be especially problematic for example for a registration form. Since it would find the username and password in POST data it would automatically log in. Ideally the one should be able to configure a login URL and the authenticator should check for the fields only for that URL.

**Comment by burzum** [comment]
This will add it https://github.com/cakephp/authentication/pull/16

**Comment by burzum** [comment]
Merged #16
