### ISSUE TITLE
[RFC] Identity abstraction

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/authentication#132]
IIRC we decided that `ArrayAccess` for identity abstraction would suffice. It would allow for using `EntityInterface` instances as identities.

I noticed that there's still `IdentityInterface` and `Identity` class in use. It looks like a wrapper for a `ArrayAccess` an actual identity returned from a successfull authenticator result.

I'm wondering if that's even necessary given the fact, that the actual identity passed to the request parameter will be an `IdentityInterface` instance rather than an entity or whatever returned from an identity resolver. The whole idea of having flexible interface (`ArrayAccess`) for identities falls through. The `IdentityInterface` doesn't even have a method to access the original identity.

My idea is to get rid of `IdentityInterface` and `Identity` at all and use actual identities as request parameters. The interface and the class look reduntant to me.

**Comment by markstory** [comment]
The Identity class implements `ArrayAccess`. Having a generic way to get an identities 'id' is the value that class provides. If we were to use 'bare' entities, we would not be able to reliably find the id field as it could have arbitrary names based on the developer's schema.

**Comment by robertpustulka** [comment]
Is that needed somewhere to get the identity `id`?

If that's a convenience for the userland code I think that the developer is aware of the schema their Users model is using and there's no real benefit of having such wrappers.

It's actually limiting, because the identity no longer implements the EntityInterface if ORM resover was used.

**Comment by markstory** [comment]
> Is that needed somewhere to get the identity id?

I think it is. Wouldn't we need a consistent way to get the id when making application code that is agnostic of the identifier/resolver?

> It's actually limiting, because the identity no longer implements the EntityInterface if ORM resover was used.

If your application uses ldap & local ORM identifiers, you wouldn't be able to rely on an EntityInterface either.

**Comment by robertpustulka** [comment]
OK, but the method to get the original data from the identity is required IMO.

**Comment by markstory** [comment]
Won't [the ArrayAccess](https://github.com/cakephp/authentication/blob/master/src/IdentityInterface.php#L20) extension allow for that?

**Comment by robertpustulka** [comment]
That won't allow me to access custom methods defined in my `User` entity. I hit a wall while developing my app. I was certain i have an instance of my `User` class in a request attribute.

I remember that the decision to make identities `ArrayAccess` was made on ordee to allow people to use their entity classes optionally as one of the complaints about `AuthComponent` was the use of raw arrays. Having array in a form of an object wrapper does not resolve the issue.
IIRC that was also one of your arguments to make the maximum requirement of `ArrayAccess`.

I also think that brings some confusion. Let's say I use ORM resolver. The return value of `Request::getIdentity()` is `EntityInterface` and then it is transformed into `IdentityInterface` while being attached to the registry. But the identity data and the identity object itself is named "identity" throughout the code. 

If we really need to have the interface for identities, let's wrap the object returned from a resolver only if it does not implement the `IdentityInterface`. This way I could for example implement the interface in my User entity class and wouldn't loose any of it's functionality.

**Comment by markstory** [comment]
> If we really need to have the interface for identities, let's wrap the object returned from a resolver only if it does not implement the IdentityInterface. This way I could for example implement the interface in my User entity class and wouldn't loose any of it's functionality.

I'm :+1: for that.

**Comment by robertpustulka** [comment]
Pull request open
