### ISSUE TITLE
FormAuthenticator::_checkLoginUrl() fails when accessing alternative route

### ISSUE THREAD

**Issue by burzum** [cakephp/authentication#137]
For testing I've been accessing the direct controller/action URL `http://cake3.world-architects.com/en/users/login` *but* we have a route for that as well `/en/login`.

But the FormAuthenticator compares *only* a string URL and not if the passed array really matches the resolved controller action but instead only the first route that machtes:

```
\vendor\cakephp\authentication\src\Authenticator\FormAuthenticator.php (line 71)
'/en/users/login'
\vendor\cakephp\authentication\src\Authenticator\FormAuthenticator.php (line 72)
'/en/login'
```

I'm not sure if there is a better way than to compare the arrays to resolve this?

**Comment by markstory** [comment]
I think you would have to compare array values as well.

**Comment by burzum** [comment]
@markstory exactly my thought but then it is required that you run the routing middleware before authentication. But this brings up a problem if we want to do authorization against routes. authorization requires the identity.

**Comment by markstory** [comment]
Couldn't the 'loginAction' be defined as a string URL if people have multiple possible routes a login page can be reached at?

**Comment by burzum** [comment]
We would always require a string then and turn the URI from the request also into an array and then compare them. Or am I missing something? If not I'll do the change.

**Comment by markstory** [comment]
That sounds like it should work to me.

**Comment by burzum** [comment]
@markstory does that look OK?

```php
    protected function _checkLoginUrl(ServerRequestInterface $request)
    {
        $loginUrl = $this->getConfig('loginUrl');

        if (!empty($loginUrl)) {
            $requestUrl = Router::parseRequest($request);

            if (is_string($loginUrl)) {
                $loginUrl = Router::parseRequest((new ServerRequest([
                    'uri' => $loginUrl
                ])));
                $this->setConfig('loginUrl', $loginUrl);
            }

            $keysToCompare = array_keys($loginUrl);

            foreach ($keysToCompare as $key) {
                if (!isset($requestUrl[$key])
                    || $requestUrl[$key] !== $loginUrl[$key]
                ) {
                    return false;
                }
            }

        }

        return true;
    }
```

**Comment by markstory** [comment]
You could use `Hash::diff` or `array_key_diff()` to check the difference between the two URL arrays.

**Comment by burzum** [comment]
@markstory I've pushed the code to the branch `bug/check-login-url` there is an issue with the routing it seems, I'm not sure if we simply want to match against the URL it has generated in this case. Would you mind to look at the code?

**Comment by markstory** [comment]
Sure, I'll try to take a look in the next few days.

**Comment by markstory** [comment]
Closing as #146 covers this.
