### ISSUE TITLE
RFC: Default sessionKey is not BC compatible

### ISSUE THREAD

**Issue by burzum** [cakephp/authentication#138]
The old auth system used `Auth.User` or `Auth.<modelAsSingular>` but the default in the new SessionAuthenticator is just `Auth`. This causes problems when you're still using the old AuthComponent and it's authorization part. 

In our case I try to migrate the existing apps AuthComponent to the new plugin but running into trouble with exactly the above.

This can be fixed / worked around by configuring it:

```php
$service->loadAuthenticator('Authentication.Session', [
    'sessionKey' => 'Auth.User'
]);
```

Do we want to make this BC at all out of the box?

**Comment by ADmad** [comment]
This plugin works significantly differently than existing core AuthComponent so I don't think BC is a concern anyway. Plus it can be configured as you should. So only thing to consider IMO is whether current default is good enough on it's own merit.

**Comment by burzum** [comment]
@ADmad I'm OK with both possibilities, but some in the core team are extremely concerned about users who don't read docs and migration guides and the users in question then come up crying why something is not working as expected. My perception is that we always try to make it easy, even for the lazy non-reading audience.

But I also think it's going to be a common case that you want to use the authentication plugin side by side with the old auth component as long as we don't have the authorization refactored as well. Authentication and authorization has been married in the AuthComponent, so I can't have authoriziation without the AuthComponent yet which is sadly coupled to the authentication.

**Comment by markstory** [comment]
This plugin is already not a drop in replacement, so I don't think this will be the breaking point. This plugin has no equivalent for `Auth->allow()` and `Auth->deny()` and I think we're all OK with that at this point.
