### ISSUE TITLE
userModel not working? 

### ISSUE THREAD

**Issue by B1scuit** [cakephp/authentication#142]
Apologies for putting this here, unfortunatly I have no idea where else to ask.

I have the following method: 
```
    public function middleware($middlewareQueue)
    {

        // Authentication block
        $service = new AuthenticationService();
        $fields = [
            'username' => 'login',
            'password' => 'password',
        ];
        $service->loadIdentifier('Authentication.Password', [
            'userModel' => 'Employees',
            'fields' => [
                'username' => 'login',
                'password' => 'password',
            ],
        ]);
        $service->loadAuthenticator('Authentication.Session');
        $service->loadAuthenticator('Authentication.Form', [
            'fields' => $fields,
            'loginUrl' => [
                'plugin' => false,
                'controller' => 'Employees',
                'action' => 'login',
            ],
            'userModel' => 'Employees'
        ]);
        
        $middlewareQueue
            ->add(new AuthenticationMiddleware($service))
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(ErrorHandlerMiddleware::class)
            // Handle plugin/theme assets like CakePHP normally does.
            ->add(AssetMiddleware::class)
            // Add routing middleware.
            ->add(new RoutingMiddleware($this));

        return $middlewareQueue;
    }
```

However when running this it just complains it cant find a Users table, am I doing something wrong?

Unfortunately, It doesn't seem to say where to put the userModel setting in the documentation.

**Comment by markstory** [comment]
What stack trace do you get in your error?

**Comment by B1scuit** [comment]
Is there any way I can get a better stack trace out? 

⟩ Cake\Database\Schema\Collection->_reflect
CORE/src/Database/Schema/Collection.php, line 97
⟩ Cake\Database\Schema\Collection->describe
CORE/src/Database/Schema/CachedCollection.php, line 63
⟩ Cake\Database\Schema\CachedCollection->describe
CORE/src/ORM/Table.php, line 532
⟩ Cake\ORM\Table->getSchema
CORE/src/ORM/Query.php, line 211
⟩ Cake\ORM\Query->addDefaultTypes
CORE/src/ORM/Query.php, line 168
⟩ Cake\ORM\Query->__construct
CORE/src/ORM/Table.php, line 1578
⟩ Cake\ORM\Table->query
ROOT/vendor/cakephp/authentication/src/Identifier/Resolver/OrmResolver.php, line 56
⟩ Authentication\Identifier\Resolver\OrmResolver->find
ROOT/vendor/cakephp/authentication/src/Identifier/PasswordIdentifier.php, line 153
⟩ Authentication\Identifier\PasswordIdentifier->_findUser
ROOT/vendor/cakephp/authentication/src/Identifier/PasswordIdentifier.php, line 119
⟩ Authentication\Identifier\PasswordIdentifier->_findIdentity
ROOT/vendor/cakephp/authentication/src/Identifier/PasswordIdentifier.php, line 104
⟩ Authentication\Identifier\PasswordIdentifier->identify
ROOT/vendor/cakephp/authentication/src/Identifier/IdentifierCollection.php, line 38
⟩ Authentication\Identifier\IdentifierCollection->identify
ROOT/vendor/cakephp/authentication/src/Authenticator/FormAuthenticator.php, line 83
⟩ Authentication\Authenticator\FormAuthenticator->authenticate
ROOT/vendor/cakephp/authentication/src/AuthenticationService.php, line 172
⟩ Authentication\AuthenticationService->authenticate
ROOT/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php, line 56
⟩ Authentication\Middleware\AuthenticationMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
ROOT/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php, line 52
⟩ DebugKit\Middleware\DebugKitMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Http/Runner.php, line 51
⟩ Cake\Http\Runner->run
CORE/src/Http/Server.php, line 81
⟩ Cake\Http\Server->run
ROOT/webroot/index.php, line 40

**Comment by B1scuit** [comment]
I hope that's what you're after unless there is more detail I can provide you?

**Comment by markstory** [comment]
That's good. Looks like the documentation is not very clear on this scenario. The identifiers no longer take a 'userModel' option. That has been separated out into a 'resolver'. Your identifier configuration should look like:

```php
$service->loadIdentifier('Authentication.Password', [
  'resolver' => [
    'className' => 'Authentication.Orm'
    'userModel' => 'Employees',
  ],
  'fields' => [
    'username' => 'login',
    'password' => 'password',
  ],
]);
```

I'll get the documentation updated.

**Comment by inoas** [comment]
Would it be possible to use FQNS? like Employees::class and Authentication\Orm::class and Authentication\Password::class, if that is not already possible?

**Comment by markstory** [comment]
Yes you can do that already.

**Comment by B1scuit** [comment]
Ahh awesome, thanks for that and yep that worked a treat 👍
