### ISSUE TITLE
Should the authenticator handle expired or otherwise invalid JSON Web Tokens?

### ISSUE THREAD

**Issue by ndm2** [cakephp/authentication#147]
I've started implementing an API with CakePHP that uses JSON Web Tokens, and upon testing handling expired or otherwise invalid tokens, I've noticed that in non-debug mode this will cause CakePHP to respond with a generic 500 error, as the `JWT::decode()` call in `JwtAuthenticator::decodeToken()` will throw an exception that isn't being handled.

```javascript
{
	"message": "An Internal Error Has Occurred.",
	"url": "\/api\/v1.0\/account\/info",
	"code": 500
}
```

I'd like to have a more graceful handling of such "errors", I'd like to be able to inspect the authentication result and respond with a "soft" 401 in such cases, alongside with a message and/or code for the client to evaluate, so that it can present meaningful information to the user.

I'm currently extending `JwtAuthenticator`, overriding `JwtAuthenticator::authenticate()` to catch the exception(s) and prepare a result accordingly, but I'm wondering whether this is maybe something that `JwtAuthenticator` should be able to somehow handle out of the box?

**Comment by lorenzo** [comment]
I agree, this case should be handled out of the box

**Comment by markstory** [comment]
I can take care of this.

**Comment by robertpustulka** [comment]
PR #148 has been merged
