### ISSUE TITLE
Feedback: Status Codes

### ISSUE THREAD

**Issue by inoas** [cakephp/authentication#155]
About the Status Codes:

```
    1: Success (Result::SUCCESS)
    0: Failure (Result::FAILURE)
    -1: Identify not found (Result::FAILURE_IDENTITY_NOT_FOUND)
    -2: Credentials invalid (Result::FAILURE_CREDENTIAL_INVALID)
    -3: Any other kind of failure (Result::FAILURE_OTHER)
    -4: Credentials not found (Result::FAILURE_CREDENTIALS_NOT_FOUND)
```

The numbers are weird ...
- There are no holes to add more inbetween or have them grouped
- Working with negative status codes makes stuff harder to work with as you cannot easily use strpos
- They do not follow posix-style or http-style (why not one of them?)
- They are ordered strange... identity not found > credentials not found > credentials invalid > any other failure or so would make more sense.
- This shows PHP misses atoms :(.

**Comment by markstory** [comment]
> Working with negative status codes makes stuff harder to work with as you cannot easily use strpos

Would you prefer to see string error codes? And `'ok`' for success?

> This shows PHP misses atoms :(.

Sure but we have to make due with what we have.

**Comment by ADmad** [comment]
What's the usecase that would require using string function like strpos() on result code?

**Comment by inoas** [comment]
I would indeed prefer strings that match the constant name, aka `Result::SUCCESS == 'SUCCESS'` - This would also make things unambiguous and easy to debug, IMHO.

@Admad if you group things into error categories, like HTTP does, you can determine the type of error from the first "char" of the error int code.

**Comment by markstory** [comment]
> if you group things into error categories, like HTTP does, you can determine the type of error from the first "char" of the error int code.

We could do something similar with our error codes too. Just need more than 1 digit.

**Comment by burzum** [comment]
> I would indeed prefer strings that match the constant name, aka Result::SUCCESS == 'SUCCESS' - This would also make things unambiguous and easy to debug, IMHO (and would be closest to atoms)

Each time I spot a string comparison like that I comment on that issue in the PR and demand to use a constant. Why would ever have the case you demonstrate? We have constants because they're, well, guess, constant values and have a clear name. The thing you try to show here would be actually:

```php
if ($result->getCode() !== Result::SUCCESS) { /* handle error in detail */}
```

This reads very nice and leaves no room for typos, not in a string nor in an integer. If you make a type in the constant an error will be thrown.

**Comment by dereuromark** [comment]
@burzum In this case the string would just for outputting purposes. It speaks more than some int number.
But for access in code of course everyone would always only use the constant access :)

**Comment by inoas** [comment]
@burzum you are certainly right but if you debug the data you will get the constant value instead of the constant name, then reading the constant value will help a lot figuring out what's going on, will it not?

**Comment by dereuromark** [comment]
@burzum If the value does not matter for code usage, then why not using speaking and proper string codes in the first place? Those numbers really are confusing, especially when somewhere between log file content and debug output.

**Comment by burzum** [comment]
@inoas Just look it up in the docs or code? I think the result provides a human readable error message as well via getErrors().

@dereuromark what about getErrors()? We should instead insure that every result that is not a success contains a good description in the errors of what went wrong.

**Comment by robertpustulka** [comment]
I also think that if a value itself does not matter, than it as well can be a "descriptive" string that can actually help quickly understand what went wrong while debugging.

**Comment by markstory** [comment]
@inoas Would you want to put together a pull request to change the constant keys?

**Comment by inoas** [comment]
What's the semantic difference of FAILURE vs FAILURE_OTHER?

**Comment by inoas** [comment]
Closing as PR is open.
