### ISSUE TITLE
Composer PHPUnit incompatible with framework

### ISSUE THREAD

**Issue by sdustinh** [cakephp/authentication#156]
The plugins PHPUnit is pinned to `<6.0` which is incosistent with the [framework](https://github.com/cakephp/cakephp/blob/master/composer.json#L44) which makes this plugin hard to install in applications that support `>=6.0`. I'm not sure if this was planned, just thought I'd throw an issue in since the auth component [deprecations](https://github.com/cakephp/cakephp/wiki/3.6-Roadmap#http-middleware-improvements) are en route.

**Comment by robertpustulka** [comment]
Good catch. The PR is open.
