### ISSUE TITLE
Make empty() checks explicit

### ISSUE THREAD

**Issue by inoas** [cakephp/authentication#161]
https://github.com/cakephp/authentication/blob/b0170077a44f3c9f9480a58c3985a03c10e37e7d/src/Authenticator/Result.php#L56

I really do not like the use of weak empty() I am always uncertain what types there are ok and which are not.

Could we make this more explicit? Could the core authors say a word about what kind of data structure there should be in $data? Maybe we should even check against some array_key_exists?

**Comment by dereuromark** [comment]
Especially with the 2nd check afterewards:

    if ($data !== null && !is_array($data) && !$data instanceof ArrayAccess) {

this does indeed sound a bit overkill.

**Comment by markstory** [comment]
@dereuromark We can't typehint across `array|ArrayAccess` which is why that check is there.

@inoas Given `null|array|ArrayAccess` how else would you check for a non-empty result? In the success case an empty array and null are both error cases.

**Comment by inoas** [comment]
@markstory - ok - just the empty weak-type check just makes my stomach feel bad.

I'll close this as I agree that the lower check is mandatory and the upper check with empty cannot easily be improved
