### ISSUE TITLE
RFC Improve status codes

### ISSUE THREAD

**Issue by inoas** [cakephp/authentication#162]
@robertpustulka wrote:
> Shoudl we fix the status codes here: https://github.com/cakephp/authentication/blob/master/src/Authenticator/TokenAuthenticator.php#L119 and https://github.com/cakephp/authentication/blob/master/src/Authenticator/HttpDigestAuthenticator.php#L82 I think that empty token or digest mean that the credentials haven't been found.

In https://github.com/cakephp/authentication/pull/159#issuecomment-351317087

**Comment by burzum** [comment]
Closing this, continue the discussion in the PR.
