### ISSUE TITLE
Fix return types or check

### ISSUE THREAD

**Issue by inoas** [cakephp/authentication#164]
https://github.com/cakephp/authentication/blob/e59550739b42d06cd109aec1d289f95618c05a6e/src/Authenticator/CookieAuthenticator.php#L112
^ this is a weak type comparison
but _checkToken's docblock says it returns string.

... and $this->getPasswordHasher()->check($plain, $tokenHash) then must return string... or boolean? but without an IDE you don't even know what it returns.

Could wee discard all `!($foo)` statements for `$foo === false` statements in future, then this will never be a problem in php 7 + strict mode world? I know it is a bit more verbose but maybe a good practise in PHP-world?

**Comment by dereuromark** [comment]
I think the only issue here is that a bool method does not return bool - or the doc block lies.
A always bool method does not have to be checked with `=== false` for obvious reasons, it would just be syntatic sugar/overhead and bear no value.

So fixing the actual issue would probably suffice IMO.
Weak checks are only a problem where mixed return types can happen.

**Comment by markstory** [comment]
>  Weak checks (in PHP) are only a problem where mixed return types can happen.

Or when PHP's type juggling is involved.

**Comment by markstory** [comment]
Pull request open to fix type annotation.
