### ISSUE TITLE
Controller.isAuthorized isn't called

### ISSUE THREAD

**Issue by lilHermit** [cakephp/authentication#176]
I know "Authorization" isn't handled by this plugin so here might not be the place for this, however I need a way to stop an action being invoked. The old AuthComponent would call `isAuthorized` so you can return false to stop the flow. Now the question is 

How do I stop the propagation of events without `isAuthorized`? I'm using `FriendsOfCake/crud` and have tried the following

```
    public function initialize() {
        parent::initialize();

        $this->Crud->on('beforeFilter', function (Event $event) {
            if (!$this->authorizedCheck()) {
                $event->stopPropagation();
                return false;
            }
        });
    }

    public function beforeFilter(Event $event) {
        parent::beforeFilter($event);

        if (!$this->authorizedCheck()) {
            $this->Flash->error('You can not perform this action, please talk to a SuperAdmin');
            $event->stopPropagation();
            return $this->redirect(['_name' => 'admin:home']);
        }
    }
```

However the action is still called. Maybe this is more a cakephp core issue/requirement?

a) am I doing something wrong?
b) I feel I shouldn't need the double check in both `beforeFilters`, so maybe Crud needs to handle stopped better?

**Comment by ADmad** [comment]
> I know "Authorization" isn't handled by this plugin so here might not be the place for this

Right, this isn't the right place to ask your question. Please use one of the help forums.
