### ISSUE TITLE
How to migrate automatic redirect handling

### ISSUE THREAD

**Issue by markstory** [cakephp/authentication#178]
The current `AuthComponent` handles a few redirect related features that are currently not implemented. 

When a user isn't logged in and is kicked back to the login page, `AuthComponent` stores where they should be going in the `redirect` query parameter. It also makes it easier to redirect users on login via `Auth->redirectUrl()`

Currently this use case must be rebuilt by the application developer. Should we add methods to `AuthenticationComponent` to make that workflow easier to build?

**Comment by robertpustulka** [comment]
I was thinking that maybe authorization should handle it (cakephp/authorization#25)

**Comment by dereuromark** [comment]
Yeah, definitily one of the most important and now since query string perfectly working features.
The crux about splitting auth - Authorization sounds good.

**Comment by robertpustulka** [comment]
Refs #31
