### ISSUE TITLE
Authenticators post data is empty when using Content-Type: application/json

### ISSUE THREAD

**Issue by chrisShick** [cakephp/authentication#185]
I have a fresh install of cakephp/app to test this. The middleware is setup like this: 

```php
 public function middleware($middlewareQueue)
    {
        $fields = [
            'username' => 'phone',
            'password' => 'password',
        ];
        $service = new AuthenticationService([
            'identifiers' => [
                'Authentication.Password' => [
                    'fields' => $fields,
                    'resolver' => [
                        'className' => 'Authentiation.Orm',
                    ]
                ]
            ],
            'authenticators' => [
                'Authentication.Form' => [
                    'loginUrl' => '/posts/add',
                    'fields' => $fields
                ],
                'Authentication.Jwt' => [
                    'returnPayload' => false
                ]
            ]
        ]);

        $middlewareQueue
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(ErrorHandlerMiddleware::class)

            // Handle plugin/theme assets like CakePHP normally does.
            ->add(AssetMiddleware::class)

            // Add routing middleware.
            ->add(new RoutingMiddleware($this))

            ->add(new AuthenticationMiddleware($service));

        return $middlewareQueue;
    }
```

When using Content-Type: application/json header the authentication fails. When using application/x-www-form-urlencoded it works. I did some digging and noticed that the Form Authenticator uses  $request->getParsedBody(); I output the contents and when using application/json, the body is empty. Usually the RequestHandler will handle recognizing the request body as json but it does not load in the middleware therefore it looks like application/json is not being recognized.

**Comment by markstory** [comment]
Looks like we might be missing middleware to convert the request body based on the content type header. The old flow with `RequestHandlerComponent` will happen too late. I think that content-type parsing belongs in cakephp/cakephp and not here though.

**Comment by chrisShick** [comment]
Now that I think about it, I agree, I should be opened up on cakephp/cakphp. Thanks for doing that @markstory

**Comment by markstory** [comment]
Going to close as this will be solved by changes in cakephp/cakephp.

**Comment by bravo-kernel** [comment]
For those using Crud... make sure to use both the `BodyParserMiddleware` and the `RequestHandler` to prevent the following ApiListener error: 
```
 `"Call to a member function setConfig() on boolean",`)
```

**Comment by angelxmoreno** [comment]
Since cake/cake added the `BodyParserMiddleware`, the solution is to make sure you add it before the authentication  middleware.
