### ISSUE TITLE
Silent allow Issue.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/authentication#188]
In a fresh 3.next app wiring this up as documented leads to
```
	[protected] _result => object(Authentication\Authenticator\Result) {
		[protected] _status => 'FAILURE_OTHER'
		[protected] _data => null
		[protected] _errors => [
			(int) 0 => 'Login URL `http://app.local/public` did not match `/users/login`.'
		]
	}
```
inside the Result, but the controllers are still accessible.
Shouldn't it in that case through an exception maybe?

**Comment by markstory** [comment]
>  Shouldn't it in that case through an exception maybe?

If you apply the middleware to your entire application, how would you go about rendering a login page, or a response that is publicly accessible?

The tutorial could be updated to add a basic authorization checks to ensure that actions have a logged in user when required.

**Comment by dereuromark** [comment]
That would sure be helpful. 
Coming from AuthComponent it disallows by default. Middelware is too early, that is a fair point.

As per documentation I added the AuthenticationComponent:

        $this->loadComponent('Authentication.Authentication', [
            'logoutRedirect' => '/users/login'  // Default is false
        ]);

And at that point I would expect it to do some sanity check here.

**Comment by markstory** [comment]
@robertpustulka and I had a few discussions about this topic. Would you think it reasonable for the authentication component to have a method like `requireIdentity()` that raises an exception if the request does not contain a calid identity?

I think something like that covers the use case you're describing and doesn't introduce any authorisation baggage.

**Comment by dereuromark** [comment]
This will sure help to avoid any user land implementations that will otherwise be necessary here to workaround this. It will then be documented and clear.

But don't you think the "former use case" of whitelisting public ones could be even more helpful?
This way you can't "forget" to protect certain controllers, actions or plugins - exposing certain data by accident.
The "default" should be the safer way IMO.

**Comment by markstory** [comment]
An alternate approach would be to default to requiring an identity and provide a `allowUnauthenticated($actions)` that can be called in a controller's beforeFilter() to mark specific actions as not requiring an identity.

**Comment by dereuromark** [comment]
Yes exactly, people coming from existing 3.x applications sure would rather expect this whitelisting behavior and might even be able to upgrade to this easier then.

**Comment by markstory** [comment]
Closing as we can continue this discussion in #191
