### ISSUE TITLE
Unnecessary cakephp version check

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/authentication#193]
The composer.json already set the version of cakephp to 3.5. 

The following check seems unnecessary:

https://github.com/cakephp/authentication/blob/f24afb6a074d6d8153b931a819b49289463ad1ba/src/Authenticator/CookieAuthenticator.php#L76

**Comment by jeremyharris** [comment]
That requirement is a dev requirement so the library can be used outside of CakePHP without bringing in the whole framework. It needs to check that the Cookie class exists as that class is within Cake, and if you installed the library stand-alone the class would not exist.
