### ISSUE TITLE
Paseto authenticator 

### ISSUE THREAD

**Issue by chrisShick** [cakephp/authentication#199]
Lately, I have been using the [Paseto](https://github.com/paragonie/paseto) of JOSE to provide better security than the current JOSE implementation on the market. I was curious if this would be an addition to the authentication plugin. I know Cake takes security pretty serious and I feel this provides a step in the right direction for developers who might be thinking of using some of the JOSE implementations. I would be happy to contribute this to the repository if there is interest!

**Comment by burzum** [comment]
After reading about it I'm OK with it as well.

**Comment by dereuromark** [comment]
@chrisShick Are you willing to make a PR here?

**Comment by burzum** [comment]
@chrisShick any news on this?

**Comment by dereuromark** [comment]
After reading https://research.securitum.com/jwt-json-web-token-security/ we are all very much looking forward to a more secure default strategy instead of JTW :)
