### ISSUE TITLE
RFC - Change file organization 

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#2]
Not really happy with the way files / namespace are organized. Would much prefer to have them similar to what's shown below:

```
src/
    Identifier/
        IdentifierCollection.php
        IdentifierInterface.php
        AbstractIdentifier.php
        ...
    Adapter/
        AdapterInterface.php
        AbstractAdapter.php
        FormAdapter.php
        ...
    PasswordHasher/
        PasswordHasherFactory.php
        PasswordHasherTrait.php
        AbstractPasswordHasher.php
        ...
    Result.php
    ResultInterface.php
    AuthenticationService.php
```

**Comment by dereuromark** [comment]
Sounds reasonable to me.

**Comment by dakota** [comment]
Sounds good to me

**Comment by markstory** [comment]
Works for me too.

**Comment by burzum** [comment]
The namespaces becomes `Auth\Adapter` then. I'm OK with the others but with do you want to rename the specific "Authenticators" to generic "Adapter". Adapter could be anything. Also, when this is going to go into the core in the future, how would you make the difference to authentication? The last time this was discussed was: `Auth\Authentication` and `Auth\Authorization`.

So if you want to rename the structure as shown in your comment, then we should rename the top level namespace from Auth to Authentication.

**Comment by ADmad** [comment]
The top level `Auth` stands for authentication so `Auth\Authentication is redundant. I am fine with renaming the top level `Auth` to `Authentication` so that we get `Authentication\Adapter`.

**Comment by ADmad** [comment]
@burzum Thanks for taking care of the renames. 

Just I would still prefer using `Adapter` prefix instead of `Authenticator` so `src/Adapter/FormAdapter.php` instead of `src/Adapter/FormAuthenticator.php`.  But if the majority prefers existing prefix then it's okay for me too.

**Comment by burzum** [comment]
I would prefer Authenticator because it's not as generic as Adapter. I would also prefer to keep the folder name Authenticator vs Adapter. So lets people vote on this.

**Comment by ADmad** [comment]
I have few more renaming suggestions :)

- `BasicAuthenticator` => `HttpBasicAuthenticator`
- `DigestAuthenticator` =>  `DigestHttpBasicAuthenticator`
- `FormAuthenticator` => `PostAuthenticator` : Not too sure about the new name but I have always disliked "Form" prefix.

**Comment by dereuromark** [comment]
The first two I like, but Post doesnt is the protocol type, and Form is the actual "type". So I prefer keeping Form as it makes it clear where the data comes from, whereas POST is just the way how they get there (and should not be part of the Authenticator name).
