### ISSUE TITLE
Set cakephp 3.6 as minimum and update deprecated methods

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/authentication#202]
Is it possible to update deprecated methods and set cakephp 3.6 as minimum requirement ?

**Comment by dereuromark** [comment]
3.6 shouldnt be the minimum requirement if no new methods are required (deprecations dont count IMO), so 3.5 people can continue using it.
Same should have been the case for https://github.com/cakephp/bake and others btw.

**Comment by ADmad** [comment]
#203 will take care of this.
