### ISSUE TITLE
Get the last result of each Authenticator

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/authentication#204]
Hi,

Could we add a method to get the last result of each authenticator processed? Today we only have one result (request attribute authenticationResult) but it would be a good idea to know why each authenticator failed.

Thanks.

**Comment by markstory** [comment]
What is the use case you're interested in for this?

**Comment by rochamarcelo** [comment]
Lets say I have four authenticators in this order: Session, Form, Custom, Cookie.

If the user is not successfully authenticated, the result object in request is from Cookie authenticator (last one) but  I want to know the failed result produced in Form and Custom authenticator to give a better feedback to the user.

**Comment by markstory** [comment]
Ok.

**Comment by dereuromark** [comment]
PR open.
