### ISSUE TITLE
UnauthorizedException => UnauthenticatedException

### ISSUE THREAD

**Issue by dereuromark** [cakephp/authentication#207]
There was a small discussion around it here
https://github.com/cakephp/authentication/pull/191#discussion_r181536200

But if you only use this plugin and either you are logged in (authenticated) or not, then it must clearly be `UnauthenticatedException` - as at this point it does not even know about the concept of authorization and role management etc.

So would you be OK with renaming the exception here inside of this plugin at this state?
To make things consistent and a bit more clear from the naming (as there are now also two different plugins).

**Comment by markstory** [comment]
My only concern with renaming is that the exception name will no longer match the http status code description. I can let go of that though.

**Comment by dereuromark** [comment]
Resolved with https://github.com/cakephp/authentication/pull/209

**Comment by inoas** [comment]
So will we use UnauthorizedException with HTTP 403 and UnauthenticatedException with HTTP 401 (aka both exceptions should exist)?

**Comment by dereuromark** [comment]
UnauthorizedException is not part of this plugin - obviously.
As explained there can only be either not logged in or logged in - the authorization part is part of the other plugin.
