### ISSUE TITLE
Docs missing for login redirect on unauthenticated

### ISSUE THREAD

**Issue by dereuromark** [cakephp/authentication#208]
https://github.com/cakephp/authentication/blob/master/docs/Migration-from-the-AuthComponent.md

Currently you would just get a `Authentication\Authenticator\UnauthorizedException` exception page rendered, no redirect to login.
There seems to be a part of the docs missing doing that - maybe by catching the exception in the lower levels (middleware?) and doing the redirect.

Would be nice if the plugin offered an easy way to do that (e.g. activating/calling a specified method).

**Comment by markstory** [comment]
Pull request open now.
