### ISSUE TITLE
Allow PluginInterface as AuthenticationMiddleware subject

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/authentication#210]
Could we allow PluginInterface as valid AuthenticationMiddleware subject? Plugin Object was added in cakephp 3.6.
https://github.com/cakephp/authentication/blob/3c03a8621d09789e169f4dc1e84c7f8cbd737ee7/src/Middleware/AuthenticationMiddleware.php#L66

**Comment by markstory** [comment]
Seems like a good idea to me.

**Comment by burzum** [comment]
Instead of adding more interfaces to check for inside our code we should follow the IoC principle. The authentication plugin should not make assumptions about different implementations outside of it.

Can't we add something to the plugin or use an event there that would create an authentication service and pass it somehow to the authentication middleware? I would prefer to check *only* for `AuthenticationServiceInterface` instead of adding more things there. Otherwise the list will grow and we'll add more shady assumptions to the plugin.

**Comment by burzum** [comment]
Created a branch here, tests are not yet changed, I'll do that as soon as we agree to this.

https://github.com/cakephp/authentication/tree/service-provider-interface

**Comment by burzum** [comment]
@robertpustulka and how do you do that without touching the code? I don't see the point.

The request object is passed to the method returning the service, the method can check if the request was done to /api or was json and return a differently configured instance based on that.

**Comment by robertpustulka** [comment]
I feel like this is a bit late for such drastic changes. We're on some ridiculous RC number right now. Breaking people's code now just before doing a stable release isn't something I'd like to do.

Maybe we could add support for providers but not remove support for application instances (for BC reasons)?

**Comment by burzum** [comment]
@robertpustulka I see this as a design flaw that should be fixed *now*. It's not like we have 10k stars yet and a finished released nor is the change a dramatic change that will require a day of work.

**Comment by robertpustulka** [comment]
Makes sense to me :+1:

**Comment by burzum** [comment]
I agree with @ADmad we should keep this in mind and make it mandatory for new projects.

**Comment by markstory** [comment]
Agreed that we mucked up the version number, but we can only fix future releases. Do we want to continue with the rc release numbers for now? When will we know we are done?

I am not too attached to the current application/ authentication integration point. It sounds like the new approach would continue to allow different parts if an application to use different authentication stacks.  Could we include how to do that as part of the documentation?

**Comment by burzum** [comment]
@markstory let's fix this in another RC release. Then wait two weeks and release 1.0 and push a 2.x branch as soon as API breaking stuff comes up and have more often a major.

**Comment by robertpustulka** [comment]
@burzum Are you planning to implement auth providers? If not I think I could spare some time later this week and create a PR.

**Comment by burzum** [comment]
@robertpustulka if somebody tells me my proposed changes are OK I'll finish the branch today.

**Comment by robertpustulka** [comment]
OK, I will take a look tomorrow.

**Comment by burzum** [comment]
@robertpustulka @markstory any update on this? Can I continue with the proposed implementation?

**Comment by markstory** [comment]
@burzum Good to go on my side.

**Comment by robertpustulka** [comment]
@burzum Please start a PR

**Comment by markstory** [comment]
#212 is open now.
