### ISSUE TITLE
CakePHP 3.6+ compatibility

### ISSUE THREAD

**Issue by HorlogeSkynet** [cakephp/authentication#211]
Hi the team,

Simple question, have you planned (or already got an ETA for) making this plugin compatible for Cake 3.6+ ?
Is it _just_ about the constraints that are not up-to-date or does it need some changes to work ?

Thanks again, bye :wave:

**Comment by dereuromark** [comment]
It should already be completely BC. Some deprecated methods might be used, but that can easily be silenced.

**Comment by dereuromark** [comment]
No, why?
The current one works with both 3.5 and 3.6, which it should as people can still be using the former minor framework version.

**Comment by HorlogeSkynet** [comment]
Sorry bad reading of the Cake's contraint on Packagist...
I've just lowered the minimum-stability, and Composer installed it.
Should I close this issue ?

**Comment by dereuromark** [comment]
For now we can close as resolved, yes.
