### ISSUE TITLE
FormAuthenticator Notice Error when using multiple CakeRouterUrlChecker loginUrls

### ISSUE THREAD

**Issue by crifpeguy** [cakephp/authentication#214]
When doing this:
```
$service->loadAuthenticator('Authentication.Form', [
            'fields' => $fields,
            'urlChecker' => CakeRouterUrlChecker::class,
            'loginUrl' => [
                ['controller'=>'Users', 'action'=>'login'],
                ['controller'=>'Users', 'action'=>'login', 'lang'=>'es'],
            ],
        ]);
```

I get the following error:
`Notice (8): Array to string conversion [ROOT/vendor/cakephp/authentication/src/Authenticator/FormAuthenticator.php, line 89]`

Seems to be because of the `implode` on the multi-dimensional Array in `_buildLoginUrlErrorResult`.

Or maybe I'm not configuring the Authenticator properly?
Thanks

**Comment by dereuromark** [comment]
Why are you configuring multiple URLs for login?
You should only have there one.

**Comment by dereuromark** [comment]
Oh, I would rather also like to support arrays here, just internally transfer them to string where necessary.

**Comment by markstory** [comment]
Supporting URLs being both strings and arrays is likely going to cause more problems down the road. Are we not interested in having the URLs resolved by users allowing the authentication internals to only deal with string URLs?

**Comment by robertpustulka** [comment]
Array URLs is opt-in. You need to load special checker for that. By default only string urls are supported.

We probably could safely remove cake router checker and encourage manual url resolving. We just have to make sure that routing middleware is invoked before the route is resolved.

**Comment by markstory** [comment]
>  We just have to make sure that routing middleware is invoked before the route is resolved.

This shouldn't be overly hard unless authentication is applied before Routing (which it generally shouldn't).
