### ISSUE TITLE
AuthenticationComponent possible event sync issues.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/authentication#218]
Currently the `Authentication.afterIdentify` event is fired from the `beforeFilter` hook (`Controller.initialize` event), before the check for identity presence is made (`Controller.startup` event).

I'm wondering if the event should be fired only if the identity presence check is successfull. 

Also there's another issue. Since the identity check is performed at `Controller.startup` phase and automatic authorization is performed before that (on `Controller.initialize`) by default (https://github.com/cakephp/authorization/blob/master/src/Controller/Component/AuthorizationComponent.php#L44), the authorization check will be performed first for `null` identity and `UnauthenticatedException` may never be thrown. In my example, the `TypeError` has been thrown since my policy requires the identity to be the `User` object.

My idea to fix this is to merge AuthenticationComponent `beforeFilter` and `startup` callbacks so the identity presence check is made in `beforeFilter` handler so the `UnauthenticatedException` could be thrown a bit earlier.

**Comment by markstory** [comment]
Where does the component use the `Controller.startup` event? I'm not seeing it.

> My idea to fix this is to merge AuthenticationComponent beforeFilter and startup callbacks so the identity presence check is made in beforeFilter handler so the UnauthenticatedException could be thrown a bit earlier.

Sounds reasonable to me.

**Comment by robertpustulka** [comment]
Identity presence check in `Controller.startup` event handler of `AuthenticationComponent`:
https://github.com/cakephp/authentication/blob/master/src/Controller/Component/AuthenticationComponent.php#L121-L133

Automatic authorization in `Controller.initialize` event handler of `AuthorizationComponent`: 
https://github.com/cakephp/authorization/blob/master/src/Controller/Component/AuthorizationComponent.php#L199-L215

In this case the authorization takes place before the identity presence check is made which is my concern.

My other concern is that the `Authentication.afterIdentify` is being fired even if there's no identity found and `UnauthenticatedException` is thrown afterwards.

**Comment by markstory** [comment]
Removing the event on missing identity seems like a simple enough change. We should do that one.

Given that putting authentication into the initialize hook will cause problems for bake, would it also make sense to align authorization with authentication and use startup for both?

**Comment by robertpustulka** [comment]
> would it also make sense to align authorization with authentication and use startup for both?

Yeah, that makes sense.
