### ISSUE TITLE
How would one logout user?

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#22]
Currently there's no mechanism to clear the identity stored in session so how would one handle user logout? It would be wrong to expect user to directly clear identity from session using `request->session()`.

**Comment by burzum** [comment]
Good question, any ideas?

**Comment by ADmad** [comment]
This is the drawback of removing storage class :)

**Comment by burzum** [comment]
Not really a drawback, you would have to somehow access it as well. :)

**Comment by markstory** [comment]
`Identity::logout()` sounds like a good interface for what we want. We might also want to consider the option of attaching the authentication adapter to the identity as well. Allowing you to do `$identity->getAuthenticator()`

**Comment by burzum** [comment]
@markstory check the latest changes in the persistence branch. It works this way now:

```php
$request->getAttribute('authentication')->clearIdentity();
```

If you really want the identity object, which is mostly a pure data object, to encapsulate these logic, we'll have to introduce more coupling and add the service to the identity object as well. Please review my changes in the persistence branch. I think they solve all our problems with the logout in a nice way.

**Comment by markstory** [comment]
@burzum Looks good to me. Does clearIdentity() need a response as well? Having a response would let you clear out response values like cookies for stateless auth, or send the client additional headers.

**Comment by burzum** [comment]
@markstory yes, I just didn't paste the whole signature here:

```php
    public function clearIdentity(ServerRequestInterface $request, $requestAttribute = 'identity')
    {
        foreach ($this->_authenticators as $authenticator) {
            if ($authenticator instanceof PersistenceInterface) {
                $authenticator->clearIdentity($request);
            }
        }

        if (!empty($requestAttribute)) {
            return $request->withoutAttribute($requestAttribute);
        }

        return $request;
    }
```

Please merge it if you agree with this.

**Comment by markstory** [comment]
That includes the request, but what about the response?

**Comment by burzum** [comment]
Ah, response, OK, my fault, I'll add it.

**Comment by burzum** [comment]
Closing this in favour of https://github.com/cakephp/authentication/pull/27 Let's continue the discussion there if needed.
