### ISSUE TITLE
Remove InstanceConfigTrait from AuthenticationMiddleware?

### ISSUE THREAD

**Issue by burzum** [cakephp/authentication#220]
I want to use the middleware outside of a CakePHP application and would like to reduce the dependencies. Especially because I don't see a reason why we can't use a simple array instead of the instance config trait. If we want more control over the config we should pass a config object.

Also this seems to be the only dependency that is required if you're not using the CakePHP ORM. I might add an Eloquent and Propel resolver if we can make this change.

**Comment by ADmad** [comment]
The `Core` package isn't too large but if `InstanceConfigTrait` is the only thing from it then I would simple duplicate that trait in the plugin.

**Comment by burzum** [comment]
Why using the trait at all for a simple array?

**Comment by ADmad** [comment]
If we don't foresee the config being anything more than a flat array and don't require the deep merging feature that trait provides, then we don't need to use it.

**Comment by markstory** [comment]
I'm ok with not using the trait if we don't have a reason to use it right now.

**Comment by saeideng** [comment]
`Cake\Core\App::className()` now uses 
also
```php
use Cake\Core\Configure;
use Cake\Error\Debugger;
use Cake\Utility\Security;
```

**Comment by dereuromark** [comment]
Sounds like this is not doable in the next time.
