### ISSUE TITLE
Unable to register middleware from Application::routes()

### ISSUE THREAD

**Issue by hiryu85** [cakephp/authentication#228]
Hi folks
Any way to load AuthenticationMiddleware for a specific routing's prefix only?

With this code i have an exception _"The request object does not contain the required `authentication` attribute"_.

```
// my src/Application.php
    public function routes($routes)
    {
        $AuthenticationMiddleware = new AuthenticationMiddleware($this, [
            'queryParam' => 'redirect'
        ]);
        $routes->registerMiddleware('authentication', $AuthenticationMiddleware);
    }

// src/config/routes.php
Router::prefix('admin', ['_namePrefix' => 'admin:'], function (RouteBuilder $routes) {
    $routes->applyMiddleware('auth');
    ....
```

If load Middleware into  Application::middleware() all works.

**Comment by garas** [comment]
Do you get it while in route with 'auth' or without?

AuthenticationComponent should be enabled only on routes with this middleware. In your case, load it  only in `Admin/` controllers.

**Comment by hiryu85** [comment]
> Do you get it while in route with 'auth' or without?

I get this exception if apply middleware in /admin with RouterBuilder (wrrapped in Rouer::prefix - show my code). 
While, if I use it with Application :: middleware (with add) it works.

> AuthenticationComponent should be enabled only on routes with this middleware. 

It would be much more convenient to apply this route-side authentification logic, without avoiding creating logic in the various controllers.

**Comment by markstory** [comment]
You `routes()` method does not appear to be calling parent. Scoped middleware is currently not going to work well if you are using cached routes as middleware is not included in the cached data.

**Comment by hiryu85** [comment]
@markstory thanks for reply.

I forgot to put it, but I have the same problem.
What do you recommend then? I wanted to assign the middleware and not the controller side

**Comment by markstory** [comment]
>  What do you recommend then? I wanted to assign the middleware and not the controller side

Have you tried turning off route caching?

**Comment by hiryu85** [comment]
@markstory yes, same result.
Surely I'm wrong approach .. I will follow your guidelines to push the middleware in a global way, and then set for each controller the actions accessible without authentication.

Thanks to the availability

**Comment by markstory** [comment]
Can you paste your full `routes()` method from your `Application` class?

**Comment by hiryu85** [comment]
@markstory sure



```
    public function routes($routes)
    {
        $authenticationSetup = [];
        $routes->registerMiddleware('authentication', new AuthenticationMiddleware($this, $authenticationSetup));
        parent::routes($routes);
    }
```

**Comment by garas** [comment]
You register with `$routes->registerMiddleware('authentication', ...);`, but then route builder uses `       $routes->applyMiddleware('auth');`. Make sure you use same name.

In your `AppController::initialize()` add `throw new \Exception;` and check if:
-  `AuthenticationMiddleware` is in callstack between `RoutingMiddleware` and `AppController` when requesting `/admin`
- there is no `AuthenticationMiddleware` when requesting `/`.

**Comment by hiryu85** [comment]
@garas meanwhile the key of my registerMiddleware changed name, sorry. The name is the same.

**Comment by markstory** [comment]
What is the stacktrace on the error you're getting? Is it from the AuthenticationComponent?

**Comment by viraj-khatavkar** [comment]
@markstory I was having a similar issue when trying to register the csrf middleware through `Application::routes` -  I was wondering if a solution to this problem was found?

**Comment by markstory** [comment]
@viraj-khatavkar What is similar about your issue? Are you getting errors about `authentication` missing? Or another error when adding csrf inside a scope?

**Comment by HelloBytes** [comment]
Same issue here. I think it is a caching / serialization problem. If I turn route caching off, no problem. With Cache config _cake_routes_ > serialize off I will get: Object of class Cake\Routing\RouteCollection could not be converted to string. With serializtion: Exception Serialization of 'Closure' is not allowed

**Comment by markstory** [comment]
Route caching doesn't work well when there are route specific middleware as middleware can contain unserializable objects as you noted. You might be best to disable route caching.

**Comment by HelloBytes** [comment]
> Route caching doesn't work well when there are route specific middleware as middleware can contain unserializable objects as you noted. You might be best to disable route caching.

Thank you for your feedback Mark. I have solved it by applying the auth to the whole application as documented via the middleware and make a separate admin prefix / controller with the auth component implemented there.
