### ISSUE TITLE
unauthenticatedRedirect skip app directory

### ISSUE THREAD

**Issue by kicaj** [cakephp/authentication#229]
Based on https://github.com/cakephp/authentication/blob/master/docs/Migration-from-the-AuthComponent.md#migrating-unauthenticated-redirects and setting `unauthenticatedRedirect` to:
```
$authentication = new AuthenticationMiddleware($this, [
    'unauthenticatedRedirect' => Router::url([
        'controller' => 'Users',
        'action' = 'login'
    ]),
]);
```
then redirect to `localhost/users/login` instead of `localhost/my_app/users/login`.

Using router array in other place works correctly.

**Comment by hiryu85** [comment]
also redirect url in redirect query parameter skip app directory

**Comment by markstory** [comment]
@hiryu85 The redirect query parameter missing the app directory seems like a separate but related issue. Could you make a new issue for that problem?

**Comment by hiryu85** [comment]
@markstory sure.
issue #230

**Comment by Zuluru** [comment]
Is the Authentication middleware supposed to be before or after the Routing middleware in the queue? I have it after, and something very like your code is working fine for me. Is it because I have my "new" call wrapped in a function instead of adding the object directly to the queue?

**Comment by krugerpl** [comment]
Hi, Any progress with this issue?

**Comment by markstory** [comment]
@krugerpl no. Would you like to help by sending a pull request?

**Comment by krugerpl** [comment]
> @krugerpl no. Would you like to help by sending a pull request?

I will try.

**Comment by kicaj** [comment]
@krugerpl How are the jobs going?

**Comment by nifa-dev** [comment]
I think I'm having the same, or closely related issue.  I'm using the following code to generate a URL in my Application.php file for redirect of an Unauthenticated request:

```
Router::url(
            [
                'prefix' => false,
                'controller' => 'Users',
                'action' => 'login',
                '_full' => true
            ]);
```

My site is hosted locally at http://localhost/scoring.  I have a route defined as /login for /users/login.  

This Router properly sets the relative URL as /login with the above function, but drops the /scoring directory from the URL and returns http://localhost/login instead of http://localhost/scoring/login.  

Any additional thoughts?  I'd love to see a code example from @Zuluru of what worked in that case.

**Comment by Zuluru** [comment]
My application is at https://github.com/Zuluru/Zuluru3

**Comment by nifa-dev** [comment]
@Zuluru, Thank you.  I was able to use that logic and successfully solve my problem.

**Comment by andrii-pukhalevych** [comment]
Maybe allow array for `unauthenticatedRedirect` like it is in `AuthComponent`? 
```
$authentication = new AuthenticationMiddleware($this, [
    'unauthenticatedRedirect' => ['controller' => 'Users', 'action' = 'login'],
]);
```

And handle it in `AuthenticationMiddleware::getRedirectUrl()` :
```
if (is_array($target)) {
	$target = Router::url($target);
}
```

Also will be good to omit copy-paste with `unauthenticatedRedirect`, `loginUrl` for `Authentication.Form` and `logoutRedirect` for `AuthenticationComponent` in some way.

**Comment by markstory** [comment]
I don't think it is always safe to assume that `loginUrl`, `logoutRedirect` and `unauthenticatedRedirect` will all go to the same place though.

**Comment by kicaj** [comment]
Resolved by https://github.com/cakephp/authentication/pull/287
