### ISSUE TITLE
AuthenticationMiddleware.queryParam generate URL without app directory

### ISSUE THREAD

**Issue by hiryu85** [cakephp/authentication#230]
If i use AuthenticationMiddleware with ```queryParam = 'redirect'``` as setting, middleware redirect me to a invalid URL.
Seems ignore application directory from URL, becase if i run cake application in root domain works fine.

## Example 1 (app not have directory, in root of domain) [WORKS]

http://myapp.test/foo/bar redirect me to http://myapp.test/users/login?redirect=http://myapp.test/foo/bar

## Example 2 (app have directory in url) [NOT WORKS]

http://myapp.test/v1/foo/bar  redirect me to http://myapp.test/v1/users/login?redirect=http://myapp.test/foo/bar but in redirect query parameter /v1/ disappears.

**Comment by Zuluru** [comment]
I've run into this same issue. It's kind of mission critical for some of my clients to be able to run in a subdirectory of their main site. What I've found:

`ServerRequestFactory::marshalUriFromServer` adds `base` and `webroot` properties to the `$uri`, but those are non-standard extensions. Most specifically, they are not handled by `\Zend\Diactoros\Uri::__toString`. As a result, when `AuthenticationMiddleware::getRedirectUrl` is called, it generates a URL without the base in it. If it generated relative URLs, that might not be an issue (or it might; I'm not really sure), but given that it generates absolute URLs, it's absolutely an issue.

Given that the code is relying on a third-party library for URL generation, and that said library doesn't support functionality that we need, I'm not sure the best solution. Make a copy of the URL object, set the `path` to be `base` + `path`, and generate the redirect URL from that? I can put together a PR for that, if it's not considered too kludgy.

**Comment by markstory** [comment]
> Make a copy of the URL object, set the path to be base + path, and generate the redirect URL from that? I can put together a PR for that, if it's not considered too kludgy.

I think that is a reasonable approach. Using `$uri->withPath()` will create a new instance for you so you won't need to clone the uri.
