### ISSUE TITLE
No direct way to redirect from an authenticator to an external Authorization Provider (ie: OIDC)

### ISSUE THREAD

**Issue by calteran** [cakephp/authentication#231]
See [this post](https://stackoverflow.com/questions/54067100/how-to-properly-redirect-from-a-cakephp-authentication-authenticator-for-openid) on StackOverflow.

There does not appear to be a formal way for an Authenticator to redirect the request to an external endpoint, a la OpenID Connect.  As noted in the accepted answer however, using the stateless auth targeted UnathorizedException achieves this.

My recommendation (FWIW) is to formalize this process either in the documentation, or with a second exception: ExternalProviderNeededException.

**Comment by markstory** [comment]
Have you attempted to use the `unauthorizedChallenge` method available to stateless authenticators? We use this in the basic and digest authenticators to add headers to the response via an exception.

Having to overwrite the status code is a bit clunky, but we could provide another exception class that is a redirecting unauthorized error. Would that help in your use case?

**Comment by calteran** [comment]
I'm currently throwing an UnauthrorizedException from within Authenticator::authenticate(), which works well enough.  I'm fairly new to this, so maybe current state is correct, so my suggestion is either to add this use case to the documentation, or to add another exception that has the same behavior but targets this case specifically.

When I get this code polished, I'm planning to share it.  Would the team want it through a PR, or should I just publish it independently as a compatible plugin?

**Comment by markstory** [comment]
> When I get this code polished, I'm planning to share it. Would the team want it through a PR, or should I just publish it independently as a compatible plugin?

If the authenticator can be used generically across various OpenID connect providers a pull request here would be good. If its for a specific vendor a plugin would be better.
