### ISSUE TITLE
Changing Hashing Algorithms

### ISSUE THREAD

**Issue by challgren** [cakephp/authentication#239]
Previously when using the AuthComponent we were able to see if the password needed a rehash by calling $this->Auth->authenticationProvider()->needPasswordRehash(). https://book.cakephp.org/3.0/en/controllers/components/authentication.html#changing-hashing-algorithms 

Currently with the new middleware it seems this is impossible to determine if the password needs rehashing

**Comment by markstory** [comment]
The PasswordHasher objects have a `needsRehash()` method that is intended for this scenario. You can get to the password hasher from the `authentication` request attribute.

I can update the documentation with an example as right now it is unclear on how to do rehash checks.

**Comment by challgren** [comment]
If you could update the documentation/provide an example that would be phenomenal
