### ISSUE TITLE
PSR 15 standard middleware and using phauthenticate/authentications as dependency

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#242]
The "double pass" middleware that this plugin currently provides incorrectly modifies the response instance before calling `$next()`. This makes it impossible to update it to PSR 15 standard / use with CakePHP 4.0 (without changing public API of various classes).

[Phauthentic/authentication](https://github.com/Phauthentic/authentication) is the framework agnostic PHP 7.1+ fork of this plugin which already has an updated PSR 15 complaint middleware.

So for next major version of this plugin I suggest this plugin only contain the CakePHP specific classes and use `phauthenticate/authentication` as dependency.

**Comment by markstory** [comment]
There have been a bunch of bugfixes in this project that I'm not sure have been ported to phauthenticate/authentication. We should make sure those tests and fixes are ported over as well.

**Comment by rochamarcelo** [comment]
What is the status of the items mentioned by @markstory ? Is someone handling it? I could compare the repos to look for missing code to port.

**Comment by robertpustulka** [comment]
There already is a CakePHP adapter for `Phauthentic/authentication`: https://github.com/Phauthentic/authentication-cakephp

The development of a library and an adapter stopped around October last year. I really didn't have an opportunity (not sure if @burzum had?) to use the Phauthentic implementation in a new project nor the time needed to update my old projects to the new lib. So we need to apply fixes as @markstory suggested.

The Phauthentic implementation differs at some points from the CakePHP plugin though. Mostly at how the services are build as we dropped the config arrays in favor of injection and setters so it is now a bit more verbose to configure the service. This means it may have lost this Cake feel but for the good reasons we believe.

Also the APIs have been simplified and changed in some places. AFAIR resolvers no longer support `OR` conditions (you should attach two or more resolvers for each field if you need to support more than one credential field) and URL checkers accept strings only now (but you still can configure multiple urls, but now they are checked in a loop). This means the migration may be tricky at some points.

I don't think it would be reasonable to maintain both CakePHP and Phauthentic implementations and personally I'd like to focus only on one of them in the future.

So we just need a decision on how to proceed. The Phaunthentic has already been updated to PHP 7.1 and PSR-15 which means there's a lot of work done already for potential Cake 4.0 compatibility. We may need to come up with a tool to make the migration from config arrays easier though and apply those fixes.

**Comment by ADmad** [comment]
I had made a PR cakephp/authorization#77 for the authorization plugin to use `Phauthentic/authentication` but it didn't pan out as the more terse and "non cake" way weren't acceptable for the plugin. With the divergence in API between the plugin and the `Phauthentic/authentication` lib, we would probably end up in same situation trying to update this plugin to use the standalone lib.

Giving the fact that a Cake 4 / PSR 15 compatible `2.x` branch has already been made at least I have no interest pursing this issue, hence closing.

**Comment by robertpustulka** [comment]
@ADmad have you been able to successfully adapt this plugin for PSR-15? I remember that there has been a significant design issue with response handling in middlewares and we needed to alter the design around identity persistence for phauthentic implementation.

**Comment by ADmad** [comment]
Yes, check the `2.x` branch.
