### ISSUE TITLE
unauthenticatedRedirect ignoring "prefix" and "plugin"

### ISSUE THREAD

**Issue by kicaj** [cakephp/authentication#245]
There is no option to use keys like "prefix" and "plugin" in `unauthenticatedRedirect` array.

    'unauthenticatedRedirect' => Router::url([
        'controller' => 'Users',
        'action' = 'login'
    ]),

The problem is because middleware of routing is after authentication.

So, why, it can't use `$this->Authentication->setConfig('unauthenticatedRedirect', ...)` in AppController? That would solve the problem

**Comment by markstory** [comment]
Couldn't routing be applied *before* routing?

> So, why, it can't use $this->Authentication->setConfig('unauthenticatedRedirect', ...) in AppController? That would solve the problem

Setting the configuration option on the component won't propagate up to the middleware as the two objects are not aware of each other. The unauthenticated redirect could live on the AuthenticationService instead, but we'd need to figure out how to do it without breaking existing usage.

**Comment by ADmad** [comment]
> The problem is because middleware of routing is after authentication.

Why not have routing middleware before authentication?

**Comment by kicaj** [comment]
How do this?

**Comment by markstory** [comment]
@kicaj Reorder the middleware add calls in your middleware() hook method so that Router is above the Authentication middleware.
