### ISSUE TITLE
Need Help with  authentication plugin

### ISSUE THREAD

**Issue by faridlinein** [cakephp/authentication#253]
can not login, when i try to debug

>object(Authentication\Authenticator\Result) {
>	[protected] _status => 'FAILURE_CREDENTIALS_MISSING'
>	[protected] _data => null
>	[protected] _errors => [
>		(int) 0 => 'Login credentials not found'
>	]
>}

need sample with from
 CMS Tutorial - Authentication (but with  authentication plugin, not Auth Component )

**Comment by faridlinein** [comment]
This is my authentication config

     $service = new AuthenticationService();
        
        $service->loadIdentifier('Authentication.Password', [
            'fields' => [
                'username' => [
                    // 'username',
                    'email'
                ],
                'password' => 'password'
            ],
            'resolver' => [
                'className' => 'Authentication.Orm',
                'userModel' => 'CoreDev/Data/User.Siteuser'
            ],
            'passwordHasher' => [
                'className' => 'Authentication.Fallback',
                'hashers' => [
                    [
                        'Authentication.Default'
                    ],
                    [
                        'className' => 'Authentication.Legacy',
                        'hashType' => 'md5'
                    ]
                ]
            ]
        ]);

        // Load the authenticators, you want session first
        $service->loadAuthenticator('Authentication.Session');
        $service->loadAuthenticator('Authentication.Form', [
            'fields' => 'fields',
            'loginUrl' => '/user/login'
        ]);

        return $service;

**Comment by ADmad** [comment]
For both identifier and authenticator config `fields` is supposed to be an array with keys `username` and `password` and the values for those keys should also be field.

Please read the [docs](https://book.cakephp.org/authentication/1.1/en/) carefully.

**Comment by faridlinein** [comment]
thank you @adman for answering my question
but in the document it is explained that the fields of the username can be filled with an array containing the username and email simultaneously

> Password
> 
> The password identifier checks the passed credentials against a datasource.
> 
> Configuration options:
> 
> fields: The fields for the lookup. Default is ['username' => 'username', 'password' => 'password']. You can also set the username to an array. For e.g. using ['username' => ['username', 'email'], 'password' => 'password'] will allow you to match value of either username or email columns.
> resolver: The identity resolver. Default is Authentication.Orm which uses CakePHP ORM.
> passwordHasher: Password hasher. Default is DefaultPasswordHasher::class.
> 

when I use one, user name or email
`'username' => 'username',`
its working , but  when i try with 
`'username' => ['email','username'],`
its return 

> object(Authentication\Authenticator\Result) {
> [protected] _status => 'FAILURE_CREDENTIALS_MISSING'
> [protected] _data => null
> [protected] _errors => [
> (int) 0 => 'Login credentials not found'
> ]
> }

**Comment by robertpustulka** [comment]
Your credential fields cannot be found because you have an error in your config:
```php
$service->loadAuthenticator('Authentication.Form', [
        'fields' => 'fields', // <-- this should be an array
        'loginUrl' => '/user/login'
    ]);
```

`fields` should be an array mapping credential fields (`username`, `password`) to your login form fields.

For example if you have a login form with fields `email` for username and `pass` for password your config should look like this:
```php
$service->loadAuthenticator('Authentication.Form', [
        'fields' => [
            'username' => 'email',
            'password' => 'pass'
        ],
        'loginUrl' => '/user/login'
    ]);
```

**Comment by faridlinein** [comment]
@robertpustulka Thank you for answering my question, but that is not what I meant, from my understanding according to the document plugin it was like this

> **Password**
> The password identifier checks the passed credentials against a datasource.
> Configuration options:
> 
> **fields**: The fields for the lookup. Default is **['username' => 'username', 'password' => 'password']**. You can also set the username to an array. For e.g. using **['username' => ['username', 'email'], 'password' => 'password']** will allow you **to match value of either username or email columns**.
> **resolver**: The identity resolver. Default is Authentication.Orm which uses CakePHP ORM.
> **passwordHasher**: Password hasher. Default is DefaultPasswordHasher::class.
> 


when I use one, user name or email
```
  'fields' => [
                'username' => [
                    'email'
                ],
                'password' => 'password'
            ]
```
its working fine, but when i try with
```
  'fields' => [
                'username' => [
                    'email',
                    'username'
                ],
                'password' => 'password'
            ]
```
its return

> object(Authentication\Authenticator\Result) {
> [protected] _status => 'FAILURE_CREDENTIALS_MISSING'
> [protected] _data => null
> [protected] _errors => [
> (int) 0 => 'Login credentials not found'
> ]
> }

**Comment by robertpustulka** [comment]
FAILURE_CREDENTIALS_MISSING is returned when credentials are missing (is fields not found in login form) and this error is not related to the identifier. From the config you’ve shown it looks to me you have a bug in your config which may be related to the error you’re getting.

Please show us your full config for working setup again.

**Comment by faridlinein** [comment]
This is my Application.php (or Plugin.php in my case)


```
namespace CoreDev;

use Cake\Core\BasePlugin;
use Cake\Core\Exception\MissingPluginException;
use Cake\Error\Middleware\ErrorHandlerMiddleware;
use Cake\Http\BaseApplication;
use Cake\Routing\Router;
use Cake\Routing\Middleware\AssetMiddleware;
use Cake\Routing\Middleware\RoutingMiddleware;
use Authentication\AuthenticationService;
use Authentication\AuthenticationServiceProviderInterface;
use Authentication\Middleware\AuthenticationMiddleware;
// use Authorization\AuthorizationService;
// use Authorization\AuthorizationServiceProviderInterface;
// use Authorization\Middleware\AuthorizationMiddleware;
// use Authorization\Policy\OrmResolver;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Authentication;

/**
 * Plugin for CoreDev
 */
class Plugin extends BasePlugin implements AuthenticationServiceProviderInterface
{

    public function getAuthenticationService(ServerRequestInterface $request, ResponseInterface $response)
    {
        $service = new AuthenticationService();

        $service->loadIdentifier('Authentication.Password', [
            'resolver' => [
                'className' => 'Authentication.Orm',
                'plugin' => 'CoreDev/Data',
                'userModel' => 'Siteuser'
            ],
            'fields' => [
                'username' => [
                    'email',
                    'username'
                ],
                'password' => 'password'
            ]
        ]);

        // Load the authenticators, you want session first
        $service->loadAuthenticator('Authentication.Session');
        $service->loadAuthenticator('Authentication.Form', [
            'fields' => [
                'username' => 'email',
                'password' => 'password'
            ]
            // , 'loginUrl' => '/user/login'
        ]);

        return $service;
    }

    public function middleware($middlewareQueue)
    {
        $middlewareQueue->

        // Add the authentication middleware
        // dari plugin Authentication
        add(new AuthenticationMiddleware($this) // , [
        // 'unauthenticatedRedirect' => Router::url('/user/login'),
        // 'queryParam' => 'redirect'
        // ]
        );

        // Add the authentication middleware
        // dari plugin Authentication
        // ->
        // add(new AuthorizationMiddleware($this));

        return $middlewareQueue;
    }
}
````

This is My AppController inside Plugin/CoreDev

````
namespace CoreDev\Controller;

class MemberController extends AppController
{

    /**
     *
     * {@inheritdoc}
     * @see \App\Controller\AppController::initialize()
     */
    public function initialize()
    {

        parent::initialize();
        $this->loadModel('CoreDev/Data/User.Siteuser');
    }


    public function login()
    {
        $result = $this->Authentication->getResult();
        debug($result);

        if ($result->isValid()) {
            return $this->redirect('/web/user/siteuser');
        }


        if ($this->request->is([
            'post'
        ]) && ! $result->isValid()) {
            $this->Flash->error('Invalid username or password');
        }

    }

    public function logout()
    {
        $this->Authentication->logout();

        return $this->redirect($this->referer());
    }
}

**Comment by faridlinein** [comment]
if i wrote this
```
 $service->loadAuthenticator('Authentication.Form', [
            'fields' => [
                'username' => ['email', 'siteuser'],
                'password' => 'password'
            ]
            // , 'loginUrl' => '/user/login'
        ]);
```
it will return FAILURE_CREDENTIALS_MISSING

**Comment by robertpustulka** [comment]
FormAuthenticator does not take an array for username. Fields config is used to map credential fields into post request data fields. Multiple username fields are supported only by PasswordIdentifier.

There is no plugin config key OrmResolver. Configure your model with dot syntax (PluginName.TableAlias).
