### ISSUE TITLE
$this->Authentication->allowUnauthenticated() does not work with Authentication.HttpBasic

### ISSUE THREAD

**Issue by asgraf** [cakephp/authentication#258]
### What you did
in Aplication.php
```PHP
public function getAuthenticationService(ServerRequestInterface $request, ResponseInterface $response)
{
	$service = new AuthenticationService();
	$authenticatorFields = [
		'username' => 'email',
		'password' => 'password'
	];
	$service->loadAuthenticator('Authentication.Session', [
		'fields' => $authenticatorFields
	]);
	$service->loadAuthenticator('Authentication.HttpBasic');
	$service->loadIdentifier('Authentication.Password', [
		'fields' => [
			'username' => ['email', 'login'],
			'password' => 'password'
		],
		'passwordHasher' => 'Authentication.Default',
		'resolver' => [
			'className' => 'Authentication.Orm',
			'finder' => 'session'
		],
	]);
	return $service;
}
```
in ExampleController.php

```PHP
class ExampleController extends AppController
{
	public function beforeFilter(Event $event)
	{
		$this->Authentication->allowUnauthenticated(['getIsLoggedIn']);
	}

	public function getIsLoggedIn()
	{
		$this->set('logged_in', $this->Authentication->getResult()->isValid());
		$this->set('_serialize', 'logged_in');
	}

	public function actionForLoggedInUsers()
	{
		//Some other action for authenticated users only
	}
}
```

Then requested getIsLoggedIn action from browser

### What happened
Http basic authentication popup showed up.
getIsLoggedIn is not accesible without authentication

### What you expected to happen
getIsLoggedIn action should be available for anyone without any authentication

**Comment by markstory** [comment]
Basic auth challenges are emitted during the middleware execution which happens well in advance of the controller being invoked. You could solve this problem differently by placing the route for that action in a routing scope that doesn't apply authentication. Outside of that I'm not sure there is a great solution for this right now.

**Comment by asgraf** [comment]
So this is backward incompatibility when migrating from deprecated $this->Auth->allow()
