### ISSUE TITLE
Differentiate between Identity not found and Credentials Invalid in FormAuthenticator

### ISSUE THREAD

**Issue by julianpollmann** [cakephp/authentication#259]
### What I did:
Added FormAuthentication with Passwordidentifier and (in my Controller) checked for the error, if the result is not valid:

    if ($this->request->is(['post']) && !$result->isValid()) {
        switch ($result->getStatus()) {
            case ResultInterface::FAILURE_IDENTITY_NOT_FOUND:
                $this->Flash->error(__('Your mail address was not found.'));
                break;
            case ResultInterface::FAILURE_CREDENTIALS_INVALID:
                $this->Flash->error(__('Your password is invalid.'));
                break;
            case ResultInterface::FAILURE_CREDENTIALS_MISSING:
                $this->Flash->error(__('Please enter your e-mail address and your password.'));
                break;
            default:
                $this->Flash->error(__('Something went wrong.'));
        }
    }

### What I expected:
If the entered password does not match the saved password, case ResultInterface::FAILURE_CREDENTIALS_INVALID should be triggered. For some reason FAILURE_IDENTITY_NOT_FOUND is triggered. I expected the Passwordidentifier to return this status.

FormAuthenticate's authenticate method returns always ID not found, whether the user does not exist or the password does not match.

    $user = $this->_identifier->identify($data);

    if (empty($user)) {
        return new Result(null, Result::FAILURE_IDENTITY_NOT_FOUND, $this->_identifier->getErrors());
    }

Is this on purpose?

**Comment by markstory** [comment]
> Is this on purpose?

Yes. Exposing that the username is correct and the password is incorrect enables attackers to know that they have half the credentials correct and to focus on brute forcing the password.

**Comment by julianpollmann** [comment]
So for what rreason there's the Result FAILURE_CREDENTIALS_INVALID? Other Identifiers?

**Comment by markstory** [comment]
Yes it is used in the Cookie and JWT authenticators.

**Comment by think-ai** [comment]
> Yes. Exposing that the username is correct and the password is incorrect enables attackers to know that they have half the credentials correct and to focus on brute forcing the password.

I understand that prompting the exact error if the username is incorrect or password is highly discourageable. However I am building a project whereby I need to block the user account after a number of unsuccessful attempt. I also thought to take advantage from FAILURE_CREDENTIALS_INVALID but it is never returned from FromAuthenticator.

I think FormAuthenticator should also return FAILURE_CREDENTIALS_INVALID and let the programmer decide if they want to use it or not.

**Comment by markstory** [comment]
@think-ai You could always extend/replace the PaswordIdentifier to provide the additional states you need.

**Comment by think-ai** [comment]
Hi Mark,

Thank you for your reply.

I had already extended `PasswordIdentifier` and `FormAuthentication` with custom classes `BackofficeIdentifier` and `BackofficeAuthentication` where `BackofficeIdentifier` `return false` when password is not correct. I am not getting false because `IndentityCollection` class has condition on line #42 `if ($result) { return $result; }` which fails for `false` and `null` is returned instead. is it intentional behaviour?

**Comment by markstory** [comment]
Yes the current code is correct as far as I know. The collection should attempt all the connected identifiers, until one succeeds.
