### ISSUE TITLE
Adding a cookie authenticator

### ISSUE THREAD

**Issue by burzum** [cakephp/authentication#26]
I know this exists https://github.com/Xety/Cake3-CookieAuth/blob/master/src/Auth/CookieAuthenticate.php but the code is really trivial to do and maintain with our identifiers. :) So what about shipping the plugin with a cookie authenticator out of the box?

**Edit**: We'll implement it, just have to wait for the Cookie changes that we need to get done before in the request and response objects.

**Comment by dereuromark** [comment]
Sounds like a good idea to me!

**Comment by ADmad** [comment]
Sure, once the API is finalized.

**Comment by burzum** [comment]
We'll also need to work on the cookie handling because right now we're stuck on the component, which is not available in the middleware stack... I've already discussed the issue with Mark Story. We'll address it and add the cookie authenticator when this has been done.

**Comment by burzum** [comment]
There is a branch open for this feature if somebody wants to help:

https://github.com/cakephp/authentication/tree/cookie-authenticator

**Comment by cleptric** [comment]
Closing as we have an open PR.
