### ISSUE TITLE
Cannot use IdentityHelper and Authorization plugin together. 

### ISSUE THREAD

**Issue by doshu** [cakephp/authentication#260]
Authorization plugin decorate the identity with the IdentityDecorator Class that implement the Authorization/IdentityInterface.

The IdentityHelper check that the identity saved in session is an instance of Authentication/IdentityInterface.

**Comment by markstory** [comment]
You could implement a custom user object that implements both interfaces if you want to use the helper with both plugins.

**Comment by Modicrumb** [comment]
I ended up forgetting the helper and using ->getOriginalData() to get the user entity i wanted:

```php
        $userEntity = $this
            ->getController()
            ->getRequest()
            ->getAttribute('identity')
            ->getOriginalData();
```

**Comment by markstory** [comment]
If you're in the view you should be able to do `$this->getRequest()->getAttribute('identity')->getOriginalData()`

**Comment by dereuromark** [comment]
Do we need any docs here, or can we close?

**Comment by Modicrumb** [comment]
I think most people will expect IdentityHelper to work with Authorization. It should probably be mentioned in the Docs for IdentityHelper, or patched to work with Authorization.

**Comment by ADmad** [comment]
This resolved in `2.x` of authorization plugin through https://github.com/cakephp/authorization/pull/94.
