### ISSUE TITLE
Kill existing sessions on password change

### ISSUE THREAD

**Issue by karmicdice** [cakephp/authentication#272]
The general rule of thumb is to **change the password** when someone believes that credentials are compromised.
When the password is changed, it logs all the sessions of the current user out.

I reckon having an option or a flag which talks to the middleware and expires the sessions of currently logged in user will be a great security feature.

Currently, if I am logged in from an account and change password from another machine. I can stay logged in for as long as I like, it does not log the other sessions out.

**Comment by ADmad** [comment]
You should explicitly call `AuthenticationService::clearIdentity()` after changing password.

**Comment by ADmad** [comment]
> Currently, if I am logged in from an account and change password from another machine. I can stay logged in for as long as I like, it does not log the other sessions out.

How do you propose we do that? There's no way for sessions to communicate with each other. If you are using database or cache engine for session then you can find all session records and clear them. But that again is something you need to do explicitly, it's beyond the scope of the auth lib.

**Comment by karmicdice** [comment]
Wow!
Did you just close the issue... which is a security must-have - especially when the component deals with Auth?
Yes, I do have a proposal.
I remember mentioning middleware.
It is not necessary to use database or cache engine! An if-else with 2 sessions upon login is enough to get the logic right. If you are planning to consider this, I will be happy to share the logic in more details.

**Comment by ADmad** [comment]
If you have a concert proposal then yes we can reconsider.

**Comment by ADmad** [comment]
Please make your PR against the 2.x branch (which is for cake 4.x) and if things work out we can backport the enhancement to 1.x.

**Comment by dereuromark** [comment]
I have the feeling too that this is out of scope, but lets see.

**Comment by dakota** [comment]
I am curious how to solve this when using PHP sessions.

**Comment by karmicdice** [comment]
Sure! Would love to share :)

This is what I had implemented using Cake 3 in one of the saas projects I did.

Additional stuff to do:

It requires adding : Timestamp on login (alongwith the user data - within session itself)

Additional changes : Maintaining an ini file outside the webroot directory

> User changes password. Refresh the timestamp in current session.
> Make a note of their ID and current timestamp
> When the auth script is executed, check the ini file with the current user id, and note the timestamp. If the current request is auth-ed but timestamp is before the timestamp in ini, then log the user out, else continue.

This way, all the older sessions will logout.

It is a proven workaround and has been working well for most of my clients. Would be awesome if this feature is incorporated in the framework.

I welcome your comments before I start coding.

**Comment by ADmad** [comment]
So as we expected what you want isn't possible using just sessions, you need an extra data store. 

Implementing all the steps you mentioned are beyond the scope of this lib, you can handle them in your app code and custom authenticate class.

**Comment by karmicdice** [comment]
Yes, ofcourse with an additional layer which isn't utilizing sessions as a whole under database or on a cache engine.
Thank you for your time.
