### ISSUE TITLE
API reference link ?

### ISSUE THREAD

**Issue by raul338** [cakephp/authentication#273]
Is there a link to the API documentation/reference? I didn't find in the readme or in the actual docs.

Something [Like chronos](https://api.cakephp.org/chronos/1.1/)

**Comment by markstory** [comment]
No there isn't. We've not gotten around to updating the api-docs build processes to also generate API reference for various plugins.

**Comment by raul338** [comment]
Ok, As far as I can understand, the whole api.cakephp.org should be built in [cakephp-api-docs](https://github.com/cakephp/cakephp-api-docs) right?
Is the plan to include every official plugin? (Maybe this should be discussed in an issue or in the chat)

Feel free to close this issue

**Comment by markstory** [comment]
@raul338 yes that project generates all of the currently published API docs. I am not sure that every plugin needs to be published. For example debugkit and migrations don't have a very wide public PHP API so I don't think that API docs would be that valuable. However, authentication and authorization could be helpful.

**Comment by jdecode** [comment]
The documentation link (not the API doc) is mentioned incorrectly as :
https://book.cakephp.org/authentication/2.0/en/

While I am getting a 404 error on the link above, I couldn't find the correct link from the book as well.
Could someone please share (if there is any) working link of the docs for Auth 2.x

**Comment by garas** [comment]
The link is https://book.cakephp.org/authentication/2/.

There is link from book in left menu in near bottom in _Plugins_ section. Currently it links to v1, link to non-released v2 can be get by replacing `1` to `2` in URL.

**Comment by markstory** [comment]
I will get the 2.0 URLs fixed. They should be rewriting to the /2/en path.
