### ISSUE TITLE
Routing problems in authentication plugin

### ISSUE THREAD

**Issue by bitproITSolutions** [cakephp/authentication#276]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x-dev
* Authentication plugin Version: 2.x-dev
* Platform and Target: XAMPP, URL of Cake installation http://localhost/subdir/

### What you did
Integrating authentication and authorization plugins. I did the setup/config according to the book and attached both plugins to the middleware trying to get things going. 

### What happened
First issue is that the "loginUrl" config parameter in AuthenticationService caused a "Login URL http://localhost/users/login did not match /users/login." error in the login action.
Second issue is that "unauthenticatedRedirect" config in AuthenticationMiddleware set to "/users/login" redirects to "http://localhost/users/login" ignoring the subdir.

### What you expected to happen
Routing in the authentication plugin should recognize the subdir where Cake is installed.

**Comment by markstory** [comment]
What does your authentication plugin configuration look like?

**Comment by bitproITSolutions** [comment]
`$service->loadAuthenticator('Authentication.Form', [
            'fields' => $fields,
            'loginUrl' => '/users/login'
        ]);`

`new AuthenticationMiddleware($this, [
                'unauthenticatedRedirect' => '/users/login'
            ])`

**Comment by markstory** [comment]
You are using string URLs. You need to use `Router::url()` to ensure that the base directory is applied.

**Comment by bitproITSolutions** [comment]
I tried this already but I get a "MissingRouteException" with the router when adding "AuthorizationMiddleware" to the middleware queue.

`$middlewareQueue->add(new AuthorizationMiddleware($this), [
                'unauthorizedHandler' => [
                    'className' => 'Authorization.Redirect',
                    'url' => Router::url(['controller' => 'users', 'action' => 'login']),
                    'queryParam' => 'redirectUrl',
                    'exceptions' => [
                        MissingIdentityException::class,
                        OtherException::class,
                    ],
                ],
            ]);`

**Comment by markstory** [comment]
Yeah you can't use an array URL in the middleware hook as routes aren't loaded until the `RoutingMiddleware` runs. What version of the authentication plugin are you using?

I was looking at how the AuthenticationMiddleware works, and https://github.com/cakephp/authentication/blob/d79ed9028b882214059e2bec8f652611dbdef469/src/Middleware/AuthenticationMiddleware.php#L161-L165 this block should be prepending the base path onto redirect URLs. Could you check why the base path isn't being applied there when you use a simple URL target?

**Comment by markstory** [comment]
This reads like a duplicate of #230

**Comment by bitproITSolutions** [comment]
I think I found the problem. The redirect URL ist generated correctly with the base path of the installation.

In line 167 
`$url = parse_url($target);`

When the §target is a string URL the base path is not applied to $url. 

The same happens in line 158, only the target is returned without the base.

**Comment by markstory** [comment]
Ok. I'll see if I can reproduce this scenario.

**Comment by markstory** [comment]
I was able to reproduce this problem. My earlier suggestions were not useful as they were referencing code that handles the `redirect` value which you aren't using based on what you've provided earlier.

Right now it isn't possible to use `Router` to generate the `unauthorizedRedirect` callback destination. One potential solution I can think of is to move this configuration value off of the middleware and move them to the `AuthenticationService`. This would help centralize configuration onto the service which has its construction deferred until the middleware is invoked which happens after routing has been applied generally.

I think this can all be done in a backwards compatible way as well.

**Comment by markstory** [comment]
You can now configure the `unauthenticatedRedirect` option on the `AuthenticationService`. Doing this in your application's `authentication` hook method will allow you to use `Router::url()` to generate a URL with the base path as long as you apply authentication middleware *after* the routing middleware.

**Comment by bitproITSolutions** [comment]
Thank you. Same problem applies to the url param in the unauthorizedHandler of AuthorizationMiddleware. Should I open another issue?

**Comment by markstory** [comment]
Yes a separate issue would be useful as it is a separate repository.

**Comment by bitproITSolutions** [comment]
https://github.com/cakephp/authorization/issues/104

**Comment by duendwang** [comment]
In Application.php, I had to add use Cake\Routing\Router; to the top in order to use Router::url(). Is that right?

**Comment by markstory** [comment]
@duendwang Yes that is expected.

**Comment by duendwang** [comment]
Thank you. Mentioning it for newbies, for whom this won't be obvious.
