### ISSUE TITLE
RFC: Setup authentication through method calling (bonus fluent interface)

### ISSUE THREAD

**Issue by inoas** [cakephp/authentication#28]
### Reason
I would love to see stuff to fail early. It should be easy to know where and why. The current array configuration is maybe a bit error-prone and fails silently.

I would love to be notified when something is wrong and right now when you pass some array structure that is malformed it is silently ignored and I think it would save countless hours if you were notified.

The current array-based configuration *also* adds a lot of newbie questions on the social channels that could be caught early with this feature!

### Suggestion
Could an interface like this work (and/or be improved)?:

```php
class Application extends BaseApplication
{
    public function middleware($middleware)
    {
        // Instantiate the authentication service and configure authenticators
        $service = new AuthenticationService()
            ->addIdentifier('Orm'),
            // TODO handle assignments - like username, password, finders (scopes) - here
            ->addAuthenticator('Form')
            ->addAuthenticator('Session');

        // Add it to the authentication middleware
        $authentication = new AuthenticationMiddleware($service);

        // Add the middleware to the middleware stack
        $middleware->add($authentication);
    }
}
```

**Comment by inoas** [comment]
The syntax, if it made any sense, would also allow to remove Authenticatiors.

**Comment by ADmad** [comment]
As mentioned [here](https://github.com/cakephp/authentication/pull/23#issuecomment-264832232) configuring the service class using fluent interface is already possible.

**Comment by inoas** [comment]
Setting username, password fields, custom finders etc, should also be possible through a fluent interface - is it?

Could you update the example to see if it flows good?

**Comment by burzum** [comment]
@inoas *please* review the code before making suggestions.

> Setting username, password fields, custom finders etc, should also be possible through a fluent interface - is it?

`AuthenticationService::loadAuthenticator()` is already doing what you propose, 2nd arg is the config. It returns the authenticator not the current objects instance.

We could add a `loadIdentifier` method but this would just be a proxy to the collection object. So you can already do $service->identifiers()->load('Identifier');

**Comment by inoas** [comment]
Chaining isn't the key, that would/is nice to have.

The array way of setting up component should be discouraged unless the new code throws very explicit warnings including warnings about array keys/values that were not expected.

If the setting is done through single calls or chains matters little to me, though fluent is just nicer.

**Comment by burzum** [comment]
@inoas I've updated the documentation with the OOP style config.

**Comment by inoas** [comment]
So what happens if someone enters this:
```php
        $service->identifiers()->load('Authentication.Orm', [
            'fields' => [
                'username' => 'email',
                'passwort' => 'pass'
                     // ^
            ]
        ]);
```

Could these be method calls like `setUsernameField()` and `setPasswordField()`?

**Comment by burzum** [comment]
Nothing happens then. Unit test your login. :)

**Comment by markstory** [comment]
Adding methods to set every config option seems like it would get unwieldy at least on the surface. We could add checking for typos in configuration keys, and raise exceptions when unexpected keys are provided.

**Comment by burzum** [comment]
@markstory this becomes a ton of checks for some config arrays. Especially the nested ones like the fields.

**Comment by markstory** [comment]
Wouldn't it also be a ton of methods?

**Comment by ADmad** [comment]
It's not praction to have tons of method nor array key checks. At some point devs just have to be careful.

In AuthComponent you would end up with a dozen keys in config array making typos difficult to spot but here having separate methods for setting up identifiers and authentication means each function call would have only 2-3 keys making typos easy to spot.

**Comment by burzum** [comment]
We should remove the possibility to pass the whole config in a giant array in the constructor then? This would force people to use the two methods.

**Comment by ADmad** [comment]
I would keep it. Let people choose their preferred way.

**Comment by dereuromark** [comment]
I agree. Some might have it configured and pass the Configure::read() stuff or sth.

**Comment by burzum** [comment]
OK, so we can close this and keep it as it is because it already features both flavours?

**Comment by burzum** [comment]
> I still think it is kind of error prone. This is the moment things change and I'd like to see less error-prone-ness.

While I agree, just test your code. :) You should get failing tests for your login if you have such typos.

> How about we read out every key then unset it. If anything is left afterwards, the intention was unclear and an exception would be thrown listing (dotnotation) the path that could not be consumed?

@inoas  This has been discussed before and the idea was to have config objects. Basically something like an entity that can validate it's config and the config be read from. However, if you're interested in chasing this idea any further please open a ticket in the cakephp repository. You might show how other frameworks do it (I don't have the time for the research) and might come up with a sample implementation? A BC compatible way would be a config array that implements ArrayAccess. So we can do checks on it while staying BC when passing it.
