### ISSUE TITLE
Result include the matching Authenticator and Identifier

### ISSUE THREAD

**Issue by Erwane** [cakephp/authentication#283]
## Context
my users table have 2 fields `password` and `password_tmp`
I want to known if user authenticate with `password` or `password_tmp`

Application.php
```php
    $service->loadAuthenticator('Authentication.Form', [
            'fields' => ['username' => 'email', 'password' => 'password'],
            'loginUrl' => Router::url(['_name' => 'auth.signin']),
        ]);
    $service->loadIdentifier('Authentication.Password', [
            'fields' => ['username' => 'email', 'password' => 'password'],
            'passwordHasher' => 'Authentication.Default',
        ]);
   $service->loadIdentifier('PasswordTmp', [
            'className' => 'Authentication.Password',
            'fields' => ['username' => 'email', 'password' => 'password_tmp'],
            'passwordHasher' => 'Authentication.Default',
        ]);
```

This works great BUT if don't known which Identifier match.
It's possible to include `Identifier` object in `Result` ?

**Comment by markstory** [comment]
>  It's possible to include Identifier object in Result ?

How would that work? Where would you get that information in from the result?

**Comment by Erwane** [comment]
There is 2 things : 
in `IdentifierCollection::identify`, should set the successfulIdentifier when result exists
in `XyzAuthenticator::authenticate` create `Result` and set `authenticator` ($this) and `identifier` (from IdentifierCollection::getSuccessfulIdentifier`

Then you return a `Result` and can access the correct Authenticator and Identifier.

**Comment by dereuromark** [comment]
https://github.com/cakephp/authentication/pull/298
