### ISSUE TITLE
1.1.3 & SecurityComponent yield "Bad Request".

### ISSUE THREAD

**Issue by kevindecapite** [cakephp/authentication#284]
When I have time later I will provide steps to reproduce the error more specifically. For now, I will say that in Cake 3.7.9 and Authentication plugin 1.1.3, using default configuration in `SecurityComponent`, I get a "Bad Request" on all form posts.

Downgrading to the 1.1.2 version of the plugin resolves it.

**Comment by kevindecapite** [comment]
Here's the stack trace.

![Screen Shot 2019-09-07 at 9 31 08 PM](https://user-images.githubusercontent.com/1189656/64491122-47ac4b80-d219-11e9-8d7a-7c91143b1530.png)

**Comment by markstory** [comment]
I will see if I can reproduce this issue.

**Comment by erfunath** [comment]
Thanks for jumping on this. I spent hours trying to figure this out.

**Comment by kevindecapite** [comment]
Oddly, this fixed the issue for all cases except my login, even though my login code works as-is in 1.1.2.

**Comment by markstory** [comment]
@kevindecapite Without a way to reproduce what you're seeing I can't be of much help.

**Comment by erfunath** [comment]
I too am having issues with login still, but not with anything else. What code would you need to see to diagnose this?

**Comment by Erwane** [comment]
Sorry to reopen but i still have error in 1.1.4
I should fallback to 1.1.2 to get working page.

AuthenticationMiddleware call SessionAuthenticator::persistIdentity and renew the session, process continue and SecurityComponent is called with a new session id.

Redirect is done by controller, not AuthenticationMiddleware, the SecurityComponent fail.

**Comment by markstory** [comment]
@erwane yes, there is another pull request open to fix that problem which will be in 1.1.5

**Comment by think-ai** [comment]
Sorry to reopen again. I am using FormAuthenticator on 1.2.1 and the login request is ending in ```
Bad Request
Cake\Controller\Exception\AuthSecurityException
```
![security component issue](https://user-images.githubusercontent.com/54765200/65406436-2e042a00-ddfd-11e9-8cc7-9f5bcff53eae.png)

I am login security component after authentication component.

**Comment by markstory** [comment]
@think-ai I'm not able to reproduce a token failure on a login page in the applications I have locally. Are you able to provide a way to help me reproduce what you're seeing?

**Comment by think-ai** [comment]
@markstory I'll do this tonight and let you know.

Thanks.

**Comment by think-ai** [comment]
Hi @markstory, I was able to solve this issue. There is no bug with the plugin but my afterIdentify event listener was adding few addtional values to identity data. thats why it was failing with security component.

Thanks.

**Comment by groovenectar** [comment]
This seems possibly related to https://github.com/CakeDC/users/issues/818

Since the session needs to be renewed, any login form would break unless it can get the new token

**Comment by groovenectar** [comment]
I wonder what would be involved in porting `SecurityComponent` to middleware, as was case is for `AuthComponent`? Then the order of the processes can be controlled?

**Comment by ADmad** [comment]
The primary benefit of having it as a component is one can easily manage configs like `allowedActions`, `unlockedFields` etc. on per controller basis.

I am a bit surprised so many people wanting to make `SecurityComponent` work with login form when the easy option is to just skip the security token check for login action :slightly_smiling_face:. Form manipulation is a non issue when it comes to login form as it doesn't involved using the form data to update database.

**Comment by groovenectar** [comment]
@ADmad Thanks, since login is so closely associated with security, it is nice to have concrete reasoning to solve it by just skipping `SecurityComponent` for that case. Just from the verbiage of "login"/"security", it sounds very counterintuitive. But perhaps that is actually not at all the case in this context. Perhaps there is zero benefit to `SecurityComponent` on login and the best thing is to just skip it. To get login working with Authentication and Form Authenticator, that would be an ultimate goal and disabling `SecurityComponent` for login sounds like the way to go

**Comment by ADmad** [comment]
Historically `SecurityComponent` did lot of security related stuff, for e.g. it handled CSRF protection too.

Currently it only provides form tampering protection and enforcing use of `https` for specific URLs. The latter is pretty simple to achieve, so in 4.x we should probably deprecate `SecurityComponent` and move the form tampering projection code into a new `FormTamperingProtectionComponent`.
