### ISSUE TITLE
Unable to log user out

### ISSUE THREAD

**Issue by beboobailey** [cakephp/authentication#290]
I am migrating my application from the AuthComponent to the Authentication plugin. When attempting to log the user out, they are redirected but they remain logged in. In my testing, I noticed that in my UserController::logout(), if I return anything, the user will remain logged in. If I do not, it will log the user out.

This will not log the user out:
```php
public function logout()
{
    $this->Authentication->logout();

    return $this->redirect($this->referer());
}
```

This will:
```php
public function logout()
{
    $this->Authentication->logout();
}
```

My issue is that I don't have a view for this function (nor do I want one) and need it to redirect. 

In case you need it, this is in my AppController::initialize():
```php
$this->loadComponent('Authentication.Authentication', [
        'logoutRedirect' => '/users/login'
]);
```

What am I missing here?

**Comment by markstory** [comment]
How are you storing sessions? This could be a race condition around session write time. There have been issues in the past where a redirect could be completed before the previous session's has been fully persisted. This has come up often with database sessions and with php-fpm.

**Comment by markstory** [comment]
I was able to reproduce this, and found a problem. See #291

**Comment by beboobailey** [comment]
I am not using database sessions or php-fpm. I made your PR change to my source and the problem appears to be fixed. Thank you!
