### ISSUE TITLE
Fix this to implement correct status

### ISSUE THREAD

**Issue by lpj145** [cakephp/authentication#293]
https://github.com/cakephp/authentication/blob/eac7a8e4b2f0c1e14d9128fe7febd7e8b9b50888/src/Middleware/AuthenticationMiddleware.php#L136

Hey boy's when i'm working with tuupola cors i check have something wrong on this code, why he not check if i need a throw ? why not pass correct status 401 and all the response data to body ? ok maybe i'm wrong, but why no define on config something to choose by throw or a simple response ?

Thank's for your attention!

**Comment by lpj145** [comment]
I can make pr to it.

**Comment by lpj145** [comment]
![image](https://user-images.githubusercontent.com/11980109/65738891-db0acb00-e0b9-11e9-8d91-f23482b47b96.png)
i maked this, for right work, ps don't see *X-Powered-By* header :)

**Comment by markstory** [comment]
How could someone reproduce the problem you're running into? I'm not sure how the current code becomes a problem.

**Comment by lpj145** [comment]
@markstory think you need use cors or anything headers to get response from api, right... now you have some issue with login by jwt, by credentials... the code on line 134 don't try get olders headers, it's simple throw response and all  olders information are fault.

**Comment by lpj145** [comment]
but if you see, the line 101 try to authorize, if have any issue, this generate a response with headers and other things, you can understand ?

**Comment by markstory** [comment]
@lpj145 I think so. In both the scenarios you're pointing to any headers currently in the request are retained. I don't see where headers are being removed. Is the problem that your controller action isn't being called or doesn't run to completion?

**Comment by lpj145** [comment]
ok, so reproduce this steps... add tuupola or any cors psr-15, add authentication middleware and enter wrong credentials or expired credentials.. voila, the response don't have a Cors headers or any other headers. he have a simple throw response with string body "You need authentication to continue!"

**Comment by markstory** [comment]
What order do you have the middleware stacked in? If the Cors or tuupola middleware are *after* authentication that code is never reached. Those middleware would need to be added to the middleware stack *before* authentication is applied.

**Comment by lpj145** [comment]
@markstory don't tell me wrong! yes the cors is before not after...try reproduce steps to get this bug.

Install cake
Install Authentication plugin
install Tuupola/Cors

and try login with jwt or something...

to facilitate your life i'm have a skeleton with all these.

https://github.com/lpj145/cake_jwt

**Comment by markstory** [comment]
In the repository you linked, I don't see any cors middleware being used here https://github.com/lpj145/cake_jwt/blob/12eb327501de14027e28d3281fc98d7b33e74e7e/src/Application.php#L85-L103

**Comment by lpj145** [comment]
Yes @markstory not have a middleware, but you can add with easily.

Yes cors os before and bug os a true, i'm make a pr to yours verify.

**Comment by markstory** [comment]
@lpj145 I'm looking for a way to reproduce the problem your having. I don't really have the time to guess my way to the problem.

**Comment by lpj145** [comment]
in sometimes i'm post repository whit this skeleton,

**Comment by markstory** [comment]
Bump
