### ISSUE TITLE
[feature request] Persist identity without form "remember me" in CookieAuthenticator

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/authentication#294]
Currently the CookieAuthenticator persists the identity if a "remember me" parameter is send via the request, which is nice for a form based login. 

Alas there isn't straight forward way to persist the cookie without manipulating the request. It would be nice if there was an option to persist without checking for a "remember me" (e.g. as `'cookie' => ['rememberMeField' => null, ...` config).

Personal motivation: I don't want to set a "forever"-cookie but I also want regular visitors (within a few days) to be kept logged-in and update the cookie before it expires.

**Comment by markstory** [comment]
Have you considered adding a hidden input to your login form that sends your 'remember me' input value?

**Comment by Schlaefer** [comment]
Let me try to be more precise. The user logs in via a form and "remember me" checkbox using the current implementation. That is absolutely fine, desired and works as expected.

But I don't want to set a forever cookie. It just feels wrong from a security point of view (device isn't owned by the user [work, semi-public, ...], you know how people are, they forget to logout). I also don't want to limit the cookie to let's say a month, because I got feedback from people being irritated about being logged-out on their personal devices.

I want to implement a conventional "remember me" form-login and after that push out the cookie-expiry if the user continues to visit from their personal devices without having them see a login-form again.

What I consider doing now in my authentication component to accomplish that:

```php
    /**
     * Update persistent authentication providers for regular visitors.
     *
     * Users who visit somewhat regularly shall not be logged-out.
     *
     * @param User $user User identity to refresh
     * @return void
     */
    private function refreshAuthenticationProvider(User $user)
    {
        // Get current authentication provider
        $authenticationProvider = $this->Authentication
            ->getAuthenticationService()
            ->getAuthenticationProvider();

        // Persistent login provider is cookie based. Every time that cookie is
        // used for a login its expiry is pushed forward by setting it anew.
        if (authenticationProvider instanceof CookieAuthenticator) {
            $request = $this->getController()->getRequest();

            // Simulate form-submit-"remember me" for Cake authentication plugin.
            // See: https://github.com/cakephp/authentication/issues/294
            $bodyData = $request->getParsedBody() ?: [];
            $bodyData += [$authenticationProvider->getConfig('rememberMeField') => true];
            $request = $request->withParsedBody($bodyData);

            ['response' => $response] = $authenticationProvider->persistIdentity(
                $request,
                $this->getController()->getResponse(),
                $user
            );
            $this->getController()->setResponse($response);
        }
    }
```

It would be handy if you could communicate to CookieAuthenticator to persist from code - just put the cookie down - without faking a form field.

**Comment by markstory** [comment]
Instead of simulating a sub request, you could extend the expiration time on the existing cookie.

```php
$authenticationProvider = $this->Authentication
  ->getAuthenticationService()
  ->getAuthenticationProvider();

if ($authenticationProvider instanceof CookieAuthenticator) {
  $cookie = $this->request->getCookieCollection()->get('rememberMe');
  $cookie = $cookie->withExpiry(new DateTime('+7 days'));
  $this->response = $this->response->withAddedHeader('Set-Cookie', $cookie);
}
```

**Comment by Schlaefer** [comment]
> Instead of simulating a sub request, you could extend the expiration time on the existing cookie.

Thanks for pointing in me in that direction.

For future reference/visitors, this is what I went with (Cake 3.8):

```php
$authenticationProvider = $this->Authentication
    ->getAuthenticationService()
    ->getAuthenticationProvider();

if ($authenticationProvider instanceof CookieAuthenticator) {
    $controller = $this->getController();

    $cookieKey = $authenticationProvider->getConfig('cookie.name');
    $expire = $authenticationProvider->getConfig('cookie.expire');
    $cookie = $controller->getRequest()->getCookieCollection()->get($cookieKey);
    $refreshedCookie = $cookie->withExpiry($expire);

    $response = $controller->getResponse()->withCookie($refreshedCookie);
    $controller->setResponse($response);
}
```

```
