### ISSUE TITLE
Bug on authenticationService

### ISSUE THREAD

**Issue by lpj145** [cakephp/authentication#295]
ok! sorry! i'm open two issues on same day hahaha, but yours can see docs say to implement IdentityInterface to use custom IdentityClass.
[Custom Identity Class](https://book.cakephp.org/authentication/1.1/en/identity-object.html#creating-your-own-identity-object)

![image](https://user-images.githubusercontent.com/11980109/65809259-03ee9700-e172-11e9-8cbe-b81bdf29cbf7.png)
i think made it with no errors, but when AuthenticationService try to construct Identity he pass a object to User Entity but entities normally received a array on constructor...

generating this error:
![image](https://user-images.githubusercontent.com/11980109/65809278-43b57e80-e172-11e9-8f9d-aa641d5d3bbc.png)

_ps*_ i'm using jwt identifier/authenticator.

**Comment by lpj145** [comment]
after i try to get some data from identity and get this errros:
![image](https://user-images.githubusercontent.com/11980109/65809338-e3730c80-e172-11e9-95f3-d7369a02d512.png)

![image](https://user-images.githubusercontent.com/11980109/65809346-ecfc7480-e172-11e9-9a1f-c52b95cfc66e.png)

**Comment by markstory** [comment]
You will need to turn off the [returnPayload option](https://book.cakephp.org/authentication/1.1/en/authenticators.html#jwt) on the JwtAuthenticator. With that option on you'll get an ArrayObject of what was in the JWT token. With it off your user will be identified as it would be with the Form authenticator.
