### ISSUE TITLE
Allow named routes for unauthenticatedRedirect as AuthenticationService config option for cohesion

### ISSUE THREAD

**Issue by michielkeijts** [cakephp/authentication#299]
At the moment it seems that the config option `unauthenticatedRedirect` in the `AuthenticationService` does not parse routes, but requires a parsed url. 

Example: 
e.g. the named route as config argument like this does not work: 
`$service = new AuthenticationService(['unauthenticatedRedirect' => ['_name' => 'auth:login']]);`

this does work:
`$service = new AuthenticationService(['unauthenticatedRedirect' => Router::url(['_name' => 'auth:login'])]);`

however, in for example the `FormAuthenticator` the named routes are an option
```
$service->loadAuthenticator('Authentication.Form', [
            'fields' => $fields,
            'loginUrl' => ['_name' => 'auth:login'],
            'urlChecker' => 'Authentication.CakeRouter'
        ]);
```

whould it be possible for cohesion, to parse the `unauthenticatedRedirect` option by the `Router`? 

### Proposed solution: 

``AuthenticationService::getUnauthenticatedRedirectUrl``
```
    public function getUnauthenticatedRedirectUrl(ServerRequestInterface $request)
    {
        $param = $this->getConfig('queryParam');
        $target = $this->getConfig('unauthenticatedRedirect');
        if ($target === null) {
            return null;
        }
       // new line of code
       $target = Router::url($target);

        if ($param === null) {
            return $target;
        }

        $uri = $request->getUri();
        if (property_exists($uri, 'base')) {
            $uri = $uri->withPath($uri->base . $uri->getPath());
        }
        $redirect = $uri->getPath();
        if ($uri->getQuery()) {
            $redirect .= '?' . $uri->getQuery();
        }
        $query = urlencode($param) . '=' . urlencode($redirect);

        $url = parse_url($target);
        if (isset($url['query']) && strlen($url['query'])) {
            $url['query'] .= '&' . $query;
        } else {
            $url['query'] = $query;
        }
        $fragment = isset($url['fragment']) ? '#' . $url['fragment'] : '';

        return $url['path'] . '?' . $url['query'] . $fragment;
    }
```

For cohesion, it seems like a good thing to do

**Comment by markstory** [comment]
Another way to make code consistent would be to only accept string URLs in the FormAuthenticator. This might be the better change as there are other places in this plugin where string URLs are the only accepted type.
