### ISSUE TITLE
Authentication component? Needed? Features?

### ISSUE THREAD

**Issue by burzum** [cakephp/authentication#30]
This could be done as a convenience way to access the service in the request:

```php
class AuthenticationComponent extends Component {

    public function logout()
    {
        $controller = $this->_registry->getController();
        $authentication = $controller->request->getAttribute('authentication');
        if (!$authentication instanceOf AuthenticationService) {
            // Just return or throw exception?
            return;
        }

        $result = $authentication->clearIdentity(
            $controller->request,
            $controller->response
        );

        $controller->request = $result['request'];
        $controller->response = $result['response'];
    }
}
```

We could get the user as well but we can't write to the persistent authenticators through the service yet. So do we want to implement that at all? Also the component would give us a way to implement events like afterLogin we currently don't have but the old AuthComponent has.

If we implement methods to get and set the user data I would suggest to call them `getUser` and `setUser`.

Question: Is the changed instance of $controller->request and the response going to be available in the view layer as well? Or won't make this the way down to the view?

**Comment by ADmad** [comment]
Yes a convenience component would be nice.

**Comment by markstory** [comment]
> Question: Is the changed instance of $controller->request and the response going to be available in the view layer as well? Or won't make this the way down to the view?

View templates don't currently have access to the response, but they do have access to the request, which comes from the Controller.

**Comment by markstory** [comment]
I think the component methods make sense to make migration easier, and the new auth system easier to use for new developers as well.

**Comment by burzum** [comment]
Closing this in favour of #31
