### ISSUE TITLE
Authentication service URLs don't match Cake core integration test expectations

### ISSUE THREAD

**Issue by Zuluru** [cakephp/authentication#305]
Creating a new issue from the result of [discussion here](https://github.com/cakephp/authentication/commit/dbcc83f384bd1c9133c05768ef850e17adea8e88). To summarize:

AuthenticationService::getUnauthenticatedRedirectUrl gets the configured unauthenticatedRedirect target, breaks it up, and returns a URL that does not include the scheme or host. AuthenticationMiddleware::__invoke uses this return value directly when setting the Location header. In short, anything using the Authentication middleware will NOT include the scheme and host in the Location header.

Then on the Cake side, IntegrationTestTrait::assertRedirect compares the Location header against Router::url($url, ['_full' => true]). This will thus ALWAYS fail for URLs that have come back from the Authentication middleware.

These three things (AuthenticationService::getUnauthenticatedRedirectUrl, IntegrationTestTrait::assertRedirect and Controller::redirect) need to agree with each other on whether they will always use full URLs, or just use whatever is provided to them.

@markstory commented in the earlier discussion that "A redirect without the host & protocol is a reasonable and valid value." Based on this, I would think that everything above could be updated to handle both absolute and relative URLs, always returning a URL of the type they received.

I'm a little uneasy about the idea proposed there of letting `assertRedirect` check for both types of URL, as that removes the capability for people to ensure that the redirect value is one or the other, when it's important for them to do so. More rigorous, I think, to remove the `_full` parameter there, and people can pass full URLs in when they want to? But that does have potential backward compatibility issues.

**Comment by markstory** [comment]
I was looking at what would be involved in changing `assertRedirect()` and rediscovered `assertRedirectContains()`. That could help with these URLs.

**Comment by Zuluru** [comment]
Changing `assertRedirect` isn't ideal, because of backward compatibility issues.

Using `assertRedirectContains` seems like a poor alternative, because a) it's imprecise (it can't be used to check that the redirect *is* a particular string, only that it contains that, meaning that passing in a relative URL will return true even if the redirect was a full URL, or if it had unwanted query parameters) and b) it doesn't handle array URLs (though that could be added).

What about adding a new `assertRedirectEquals`, which is essentially identical to the existing `assertRedirect` except for removing the `'_full' => true`?

**Comment by markstory** [comment]
Adding a new assertion would work well too.
