### ISSUE TITLE
Url base missing

### ISSUE THREAD

**Issue by smarek** [cakephp/authentication#310]
Configuring the AuthenticationService within Application, will miss ServerRequestInterface or Router context to provide with non-static `_base`

I've came up with workaround, which is not very nice, but does the job

```php
    public function getAuthenticationService(ServerRequestInterface $request, ResponseInterface $response)
    {
        $service = new AuthenticationService();

        $fields = [
            'username' => 'username',
            'password' => 'password'
        ];

        // Load identifiers
        $service->loadIdentifier('Authentication.Password', compact('fields'));

        // Load the authenticators, you want session first
        $service->loadAuthenticator('Authentication.Session');

        $base = explode('/', $_SERVER['PHP_SELF']);
        $base = ($base[1] === 'webroot') ? false : $base[1];
        $service->loadAuthenticator('Authentication.Form', [
            'fields' => $fields,
            'loginUrl' => Router::url(['controller' => 'Pages', 'action' => 'login', '_base' => $base], false),
        ]);

        return $service;
    }
```

Is there any better solution to provide base relative loginUrl, without having to set the base statically in config?

**Comment by ADmad** [comment]
Why do need to set the base explicitly? I have used Authentication lib in an app which is in a subfolder of document root and the login url is generated as expected with the subfolder and URL base.

**Comment by smarek** [comment]
Well, if I don't, the UrlChecker will fail like this

```
// current browser url is http://1.2.3.4/subdir/config/login
// dump($this->Authentication->getResult());
Result {#53 ▼
  #_status: "FAILURE_OTHER"
  #_data: null
  #_errors: array:1 [▼
    0 => "Login URL `http://1.2.3.4/config/login` did not match `http://1.2.3.4/config/login`."
  ]
}
```

**Comment by smarek** [comment]
Might be worth mentioning, i'm using CakePHP version 3.8.5 and authentication plugin version 1.2.1 from composer

**Comment by ADmad** [comment]
I have only used the 2.x version of the lib with Cake 4.x, so I don't know if there's an issue with 1.x :)

**Comment by markstory** [comment]
When are you running the authentication middleware? If it is run *after* the RoutingMiddleware the request context should be set and used when generating URLs.

**Comment by smarek** [comment]
I'm sorry, revisiting the code, I can confirm, moving the AuthenticationMiddleware after RoutingMiddleware in middlewareQueue setup solves the issue.

**Comment by smarek** [comment]
One more related issue is when using `unauthenticatedRedirect` and configuration `urlChecker.checkFullUrl=true`

```
Result {#67 ▼
  #_status: "FAILURE_OTHER"
  #_data: null
  #_errors: array:1 [▼
    0 => "Login URL `http://1.2.3.4/config/login?redirect=%2Fsubdir%2Fconfig%2Fadmin` did not match `http://92.43.29.196/subdir/config/login`."
  ]
}
```

From what i can tell, this call https://github.com/cakephp/authentication/blob/524dc7031516d45c468f33a2fe06644f21b7e1a7/src/UrlChecker/DefaultUrlChecker.php#L110 results in URL without query params, thus failing the url-check

**Comment by markstory** [comment]
You did ask it to check the full URL and they aren't the same.

**Comment by smarek** [comment]
@markstory well that defers the whole logic of login-redirect, if `unauthenticatedRedirect` and `checkFullUrl` are meant to be incompatible, plugin should warn/error about that
