### ISSUE TITLE
getLoginRedirect() method from documentation is missing from 1.2.1 version

### ISSUE THREAD

**Issue by smarek** [cakephp/authentication#311]
Either it's doc inconsistency, because https://book.cakephp.org/authentication/1.1/en/index.html talks about 1.1 not 1.2 version, or version inconsistency, the method expected is included in master and not in 1.0.x, 1.1.x or 1.next branches

Composer for CakePHP 3.8.5 installs version 1.2.1, and I'm not sure, if it's generated from 1.next or which branch currently.

**Comment by markstory** [comment]
The documentation for 1.x builds off of master. I forgot to do a a release that contains the new method. I've tagged 1.3.0 now :blush:

**Comment by smarek** [comment]
Thank you, just verified version 1.3 fixes the issue
