### ISSUE TITLE
DefaultPasswordHasher - incorrect constant usage

### ISSUE THREAD

**Issue by smarek** [cakephp/authentication#312]
https://github.com/cakephp/authentication/blob/c4f0ec85fc2c3f3a0fe538cf92cc4a472e722367/src/PasswordHasher/DefaultPasswordHasher.php#L35

https://github.com/cakephp/authentication/blob/1b1d67f8d70cc702e9cae52bb31e3218fb08efe3/src/PasswordHasher/AbstractPasswordHasher.php#L57

https://github.com/cakephp/authentication/blob/525f0e0fd04b3ce0c818ffd8f7e678b43d2dd58f/tests/TestCase/AuthenticationTestCase.php#L49

as of docs: https://www.php.net/manual/en/password.constants.php
>PASSWORD_DEFAULT (integer)
>The default algorithm to use for hashing if no algorithm is provided. This may change in newer PHP releases when newer, stronger hashing algorithms are supported.

>It is worth noting that over time this constant can (and likely will) change. Therefore you should be aware that the length of the resulting hash can change. Therefore, if you use PASSWORD_DEFAULT you should store the resulting hash in a way that can store more than 60 characters (255 is the recommended width).

using PASSWORD_DEFAULT seems wrong to me, because different versions of PHP, might point the constant to other algorithms than PASSWORD_BCRYPT, thus breaking existing installations in future

Imho correct should be using directly PASSWORD_BCRYPT

**Comment by ADmad** [comment]
The hashed created by `password_hash()` include info about about the hashing algo used. So even if default algo changes in future old passwords will continue to word and you won't have any problems.

**Comment by ADmad** [comment]
> Note that password_hash() returns the algorithm, cost and salt as part of the returned hash. Therefore, all information that's needed to verify the hash is included in it. This allows the verify function to verify the hash without needing separate storage for the salt or algorithm information.

https://www.php.net/manual/en/function.password-verify.php

**Comment by smarek** [comment]
Cool, thank you for explanation
