### ISSUE TITLE
cake4: Move away from `array|\ArrayAccess` 

### ISSUE THREAD

**Issue by dereuromark** [cakephp/authentication#315]
`array|\ArrayAccess` is a code smell IMO
We have tons of it in both auth plugins now, and it basically makes
- no typehints and return types addable
- count() vs ->count() and all other array vs object handling logic needed everywhere.
- especially with php74 and where PHP moves, it seems those become more and more exclusive.

We should decide for one, e.g. array and stick with it. There is no value in supporting both this generically. It only weakens the API here.

I am for array since this also doesn't "modify" the input by reference. Less side effects.

**Comment by markstory** [comment]
Going to ArrayAccess might be better as the common use case we have is Entities being used in the `array|ArrayAccess` type.
