### ISSUE TITLE
Authentication doesn't store identity, clear cookies required

### ISSUE THREAD

**Issue by nitramxx** [cakephp/authentication#319]
Probably related to this issue: https://github.com/cakephp/cakephp/issues/6053

No specific cookies/sessions, no messing with code, lightweight app.

Most likely cookies issue, worked in anonymous window (Safari, macOS), didn't work with cookies. After removing, authentication could keep session/hold auth data.

**Comment by markstory** [comment]
How would someone reproduce what you experienced? Right now I don't know how you configured anything.

**Comment by othercorey** [comment]
@nitramxx Can you give us more information before we close this?
