### ISSUE TITLE
setIdentity on the auth component doesn't work

### ISSUE THREAD

**Issue by SvenBuis** [cakephp/authentication#320]
In the controller we use `$this->Authentication->setIdentity($user)`. This will be overwritten by the AuthenticationMiddleware. The Middelware sets the old identity and only updates when you modify the object you got from `$this->Authentication->getIdentity()`; 

An example where this won't work for us is when we have an admin function 'login in as user'. This allows us to login to an users profile as admins.

**Comment by markstory** [comment]
What version of this plugin are you using?

**Comment by SvenBuis** [comment]
Using 1.4.0.

I found that the SessionAuthenticator doesn't update the session when using the AuthenticationComponent setIdentity. The session key is obviously present and the `$session->check($sessionKey)` is the issue, because then the persistIdentity won't update the session. 

The identity used in the middleware therefore isn't updated (but also that persistIdentity won't save it to the session).

Just removing the check also results in a issue, because then the `$session->renew()` will cause problems with pages that have multiple ajax requests.

**Comment by markstory** [comment]
The session renew will have to stay as you are changing user privileges and should rotate session ids. I can fix the user not being persisted to the session though.

**Comment by SvenBuis** [comment]
Okay. I can understand that. 

Any suggestions on how to fix the issue that when you renew the session each request and a page with many ajax requests. For us this resulted in some ajax elements showing the login page or the default after login redirect page.

**Comment by markstory** [comment]
@SvenBuis if you can prevent the ajax requests form happening while you switch sessions, you would have to implement your own session authenticator that doesn't rotate sessions and accept the risks that entails.
