### ISSUE TITLE
lookup hashed tokens

### ISSUE THREAD

**Issue by waspinator** [cakephp/authentication#329]
I'm trying to use the token authenticator/identifier for an API key, but I'd like to only store the hashed version of the token and only show the plain text version once to the user. This kind of system is used by a few web services already. For example, github uses it to issue "Personal access tokens"

![access_token](https://user-images.githubusercontent.com/100416/69593210-8bb41e80-0fc6-11ea-8be3-382789b92f37.png)

How would I use a hasher with the `TokenIdentifier`?

Or maybe a better way is to configure the password identifier to check multiple `password` fields?

```
        $service->loadIdentifier('Authentication.Password', [
            'fields' => [
                'username' => 'username',
                'password' => ['password', 'api_key']
            ]
        ]);
```

**Comment by markstory** [comment]
> How would I use a hasher with the TokenIdentifier?

You could generate the token using `Secure::randomBytes()` and encode it as hexadecimal. Then that token could be stored in a separate column from the password. Then you can configure the `TokenIdentifier` to use that field.

**Comment by waspinator** [comment]
I'm not sure how how I would unhash it using the TokenIdentifier though. 

The other option I thought may work is modifying the `PasswordIdentifier`

```
    protected function _checkPassword($identity, $password)
    {
        $passwordFields = $this->getConfig('fields.' . self::CREDENTIAL_PASSWORD);

        if ($identity === null) {
            $identity = [
                $passwordFields => []
            ];
        }

        $hasher = $this->getPasswordHasher();

        foreach ($passwordFields as $passwordField) {
            $hashedPassword = $identity[$passwordField];
            if ($hasher->check($password, $hashedPassword)) {
                return true;
            }

            $this->_needsPasswordRehash = $hasher->needsRehash($hashedPassword);
        }

        return false;
    }
```

so that you can set to password to an array like 

```
        $service->loadIdentifier('Authentication.Password', [
            'fields' => [
                'username' => 'username',
                'password' => ['password', 'api_key']
            ]
        ]);
```

**Comment by markstory** [comment]
You don't unhash the token ever. The TokenIdentifier treats the API tokens like opaque values which they should be.

**Comment by waspinator** [comment]
sorry I didn't mean `unhash`, I meant `check`. 

`$hasher->check($api_key, $hashed_api_key)`

How can I use the `TokenIdentifier` to check if the provided api key, if it has been encrypted in the database.

**Comment by markstory** [comment]
> How can I use the TokenIdentifier to check if the provided api key, if it has been encrypted in the database.

The tokens aren't stored encrypted. They are stored in 'plain' form as they are opaque strings. If you want to store API tokens as encrypted data you'll need to build your own identifier.

**Comment by waspinator** [comment]
How do you feel about adding an option to the password identifier to accept multiple password fields, as it currently does with username fields?

**Comment by markstory** [comment]
Why would a user have multiple hashed passwords?
