### ISSUE TITLE
Authentication for login redirect when unauthenticated

### ISSUE THREAD

**Issue by Chechesa** [cakephp/authentication#331]
I work over localhost/app directory and I used this code for config a redirect:

```
        // Configure unauthenticated redirect
        $service->setConfig([
            'unauthenticatedRedirect' => \Cake\Routing\Router::url('/users/login'),
            'queryParam' => 'redirect',
        ]);
```

I needed to include Router because redirection was to localhost/users/login

When I enter with redirection trying to enter to localhost/app/articles, I see this URL: 
http://localhost/app/users/login?redirect=%2Fapp%2Fusers

And I need to avoid redirection to localhost/app/app/users (app twice)

```
        if ($result->isValid()) {
            $target = $this->Authentication->getLoginRedirect() ?? '/home';
            if (strncmp($target, '/app', 4) === 0) {
                $target = substr($target, 4);
            }
            return $this->redirect($target);
        }
```

I think behavior is related to routing problems.

**Comment by markstory** [comment]
What happens if your unauthenticatedRedirect doesn't include the application sub-directory?

**Comment by harpax** [comment]
same problem here. If the redirect param is manipulated so that the sub-dir is not included it works as expected.

As a sidenote: If I trigger /users/logout there is a redirect to login screen (as expected), but with the redirect param set to /users/logout, which leads to a nice loop

**Comment by markstory** [comment]
> As a sidenote: If I trigger /users/logout there is a redirect to login screen (as expected), but with the redirect param set to /users/logout, which leads to a nice loop

This sounds like something you might be doing in your application code by requiring a user to be present for the logout action.

**Comment by duendwang** [comment]
I have the same problem with the login redirect to logout loop. I set the logout action to accessible when not authenticated in the controller and that fixed the issue.

I had to work around the duplicate /app/ in the url issue also. In app_local.php I added another entry into the array 

'Root_URL' => '/app'

and in the login() action I changed the line to

$target = str_replace(Configure::read('RootURL'),'',$this->Authentication->getLoginRedirect()) ?? '/';

For some reason '/home' didn't work. I had to use '/'. It would tell me HomeController not found.

On the top of the controller, I had to add 

use Cake\Core\Configure;

**Comment by sebastianknopf** [comment]
I think maybe I found the issue in AuthenticationService.php, in the method **getUnauthenticatedRedirectUrl(...)**. This is the point, where the config parameter unauthenticatedUrl is processed and transformed into the needed URL for redirecting when a user is unauthenticated.

In this method you could use the **base** property of the current Uri object to represent a full and complete redirect url. The method maybe could look like this:

`
        $param = $this->getConfig('queryParam');
        $target = $this->getConfig('unauthenticatedRedirect');
        if ($target === null) {
            return null;
        }

        /* Changed code here: Always use the base property of the current Uri object 
        to generate the full unauthenticated URL! */
        $uri = $request->getUri();
        if (property_exists($uri, 'base')) {
            $target = $uri->base . $target;
        }

        if ($param === null) {
            return $target;
        }

        if (property_exists($uri, 'base')) {
            $uri = $uri->withPath($uri->base . $uri->getPath());
        }
        $redirect = $uri->getPath();
        if ($uri->getQuery()) {
            $redirect .= '?' . $uri->getQuery();
        }
        $query = urlencode($param) . '=' . urlencode($redirect);

        $url = parse_url($target);
        if (isset($url['query']) && strlen($url['query'])) {
            $url['query'] .= '&' . $query;
        } else {
            $url['query'] = $query;
        }
        $fragment = isset($url['fragment']) ? '#' . $url['fragment'] : '';

        return $url['path'] . '?' . $url['query'] . $fragment;
`

This works for me, even when leaving App.base set to false. The correct redirect url is returned.

**Comment by markstory** [comment]
@sebastianknopf This issue is for when the `queryParam` and `unauthenticatedRedirect` options are used together. If you are only using the `unauthenticatedRedirect` option you will need to use `Router` to generate the correct URL including the base URL.

I'm not able to reproduce either the redirect loops or the dropped base URL anymore. If someone can provide a way to reproduce either of these problems I'm happy to take another look.

**Comment by Ndiongmo** [comment]
I had the same issue, i solved it inside `public function getAuthenticationService`, by setting the `unauthenticatedRedirect `param with adding of Base URL on it e.g `$request->getUri()->base.'/controller/action'` inside `Application.php `.
