### ISSUE TITLE
4.x defect

### ISSUE THREAD

**Issue by dereuromark** [cakephp/authentication#335]
something is wrong with master. it is not the valid 2.x (cake4) code...
https://github.com/cakephp/authentication/compare/2.x?expand=1
thus the fails.

**Comment by markstory** [comment]
Looks like I had a stale 2.x branch when I did the master merge and release. I've fixed that up now.

**Comment by dereuromark** [comment]
O_O

did you merge 1.x (old master) into it before releasing? so we dont have outdated new master before 
 and then even worse after tagging?

**Comment by markstory** [comment]
The current `master` contains everything from the 1.x and 2.x. There weren't any unreleased changes on `1.x` before master was moved.
