### ISSUE TITLE
TokenAuthenticator class hasn't implemented PersistenceInterface

### ISSUE THREAD

**Issue by mukesh-sangtani** [cakephp/authentication#341]
TokenAuthenticator class hasn't implemented PersistenceInterface.
Since persistence interface is not implemented, this authenticator method doesn't store identity in session and user logs out after redirection.

**Comment by ADmad** [comment]
TokenAuthenticator is for stateless auth and isn't expected to store identity in session.

**Comment by mukesh-sangtani** [comment]
then how we can persist data in session?
Once user logged-in using TokenAuthenticator, I need user data to be persist into session.

**Comment by ADmad** [comment]
You can create a custom authenticator to suit your needs. The TokenAuthenticator is meant for use with stateless API.

**Comment by markstory** [comment]
Or use a combination of Token + Session authenticators. Needing to use a session implies that you will also be using session cookies, which is generally not how Token authentication is used.
