### ISSUE TITLE
DebugKit not loading because of missing login route

### ISSUE THREAD

**Issue by harpax** [cakephp/authentication#345]
I am sure this is something obvious, but I don't see it.

After activating the authentication(!) middleware the debug kit panel raises following error:

> A route matching "array ( 'controller' => 'users', 'action' => 'login', 'plugin' => 'DebugKit', '_ext' => NULL, )" could not be found.

The login action is set to `allowUnauthenticated`, which works fine. 

cake 4.0.3
dk 4.0.5
authentication 2.0.3

**Comment by kb-itdesk** [comment]
Same problem here. Any solution for this?

**Comment by garas** [comment]
Upgrade to  DebugKit 4.0.6 or later.

**Comment by kb-itdesk** [comment]
> Upgrade to DebugKit 4.0.6 or later and set `DebugKit.ignoreAuthorization` to true.
> 
> [cakephp/debug_kit#737](https://github.com/cakephp/debug_kit/pull/737)

Dependencies update was the first thing I did. I'm using DebugKit 4.1 right now:
```
"cakephp/debug_kit": "^4.1"
```
From my bootstrap.php:
```
Configure::write('DebugKit', [
    // 'panels' => [],
    // 'includeSchemaReflection' => false,
    // 'safeTld' => [],
    // 'forceEnable' => true,
    'ignoreAuthorization' => true,
]);
``` 

but still I got missing route error. Here's my middleware:

```public function middleware(
        MiddlewareQueue $middlewareQueue
    ): MiddlewareQueue {
        $middlewareQueue
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(new ErrorHandlerMiddleware(Configure::read('Error')))

            // Handle plugin/theme assets like CakePHP normally does.
            ->add(
                new AssetMiddleware([
                    'cacheTime' => Configure::read('Asset.cacheTime'),
                ])
            )

            // Add routing middleware.
            // If you have a large number of routes connected, turning on routes
            // caching in production could improve performance. For that when
            // creating the middleware instance specify the cache config name by
            // using it's second constructor argument:
            // `new RoutingMiddleware($this, '_cake_routes_')`
            ->add(new RoutingMiddleware($this))
            ->add(new EncryptedCookieMiddleware(
                // Names of cookies to protect
                Configure::read('Security.cookieNames', []),
                Configure::read('Security.cookieKey')
            ))
            ->add(new AuthenticationMiddleware($this));

        return $middlewareQueue;
    }```

**Comment by ndm2** [comment]
Take a look at the stacktrace for the error, it might happen before debug kit is actually involved, possibly in your authentication service setup if you're using the router.

**Comment by garas** [comment]
Try to set login URL with null for plugin and prefix: `['controller' => 'Users', 'action' => 'login', 'plugin' => null, 'prefix' => null]`. Router uses current plugin if not set.

**Comment by kb-itdesk** [comment]
With plugin = null I get another error (please change ext. to html):
[Error_ Record not found in table _requests_.txt](https://github.com/cakephp/authentication/files/4609337/Error_.Record.not.found.in.table._requests_.txt)

```
public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
    {
        $authFields = [
            'username' => Configure::read('Security.authUsernameField'),
            'password' => Configure::read('Security.authPasswordField'),
        ];

        $loginUrl = Router::url([
            'controller' => 'users',
            'action' => 'login',
            'plugin' => null,
            'prefix' => null
        ]);

        $authenticationService = new AuthenticationService([
            'unauthenticatedRedirect' => $loginUrl,
            'queryParam' => 'redirect',
        ]);

        // Load identifiers, ensure we check email and password fields
        $authenticationService->loadIdentifier('Authentication.Password', [
            'fields' => $authFields
        ]);

        // Load the authenticators, you want session first
        $authenticationService->loadAuthenticator('Authentication.Session');
        // Configure form data check to pick email and password
        $authenticationService->loadAuthenticator('Authentication.Form', [
            'fields' => $authFields,
            'loginUrl' => $loginUrl
        ]);
        // Cookie
        $authenticationService->loadAuthenticator('Authentication.Cookie', [
            'rememberMeField' => 'remember',
            'fields' => $authFields
        ]);

        return $authenticationService;
    }
```

**Comment by kb-itdesk** [comment]
I have noticed one strange thing: now it sometimes work, but in most cases does not. I have a plenty of console warnings about missing map files like:
```
DevTools failed to load SourceMap: Could not load content for...
```
Maybe this is related?

**Comment by garas** [comment]
Error in attached file is because DebugKit tries to load non-existing request entry. It might be already deleted if it is older request. But it should exist if it is recent request. If you think it is bug feel free to open new issue at DebugKit repository with more details. 

`DevTools failed to load SourceMap` is maybe because app skeleton has `milligram.min.css` with reference to non-existing `map` file. When file not exists, web request is handled by CakePHP, which might give some delay. If it is requested plenty of times, it might reach limit of saved requests, and older requests might be deleted, so it maybe related.

**Comment by ddellostritto** [comment]
> I have noticed one strange thing: now it sometimes work, but in most cases does not. I have a plenty of console warnings about missing map files like:
> 
> ```
> DevTools failed to load SourceMap: Could not load content for...
> ```
> 
> Because of that, DebugKit request is made with delay. Maybe this is related?

I think that is more of a console warning and has to do with browser/console configurations.

**Comment by ddellostritto** [comment]
> Try to set login URL with null for plugin and prefix: `['controller' => 'Users', 'action' => 'login', 'plugin' => null, 'prefix' => null]`. Router uses current plugin if not set.

Why does this work?
