### ISSUE TITLE
The limitations of combining stateless with stateful authenticators

### ISSUE THREAD

**Issue by ndm2** [cakephp/authentication#347]
The docs have the [**Using Stateless Authenticators with stateful Authenticators**](https://github.com/cakephp/authentication/blob/2.0.4/docs/en/authenticators.rst#using-stateless-authenticators-with-stateful-authenticators) section, which introduces the topic and shows an example, but combining form authentication and HTTP basic authentication doesn't work overly well, even when the latter is the last authenticator in the chain, it will still render login form unusable, one would never see them since the middleware would always bail out and return a basic auth challenge response.

All one could do with that setup, would be to directly POST login credentials to the login URL. I'm not sure, maybe the section should mention these limitations, or maybe it should use the token authenticator instead (or additionally), or I don't know what, but in its current state it seems that it would probably rather cause confusion.

**Comment by markstory** [comment]
The example should be updated to not use a mix of stateless and stateful authenticators. There are precious few scenario where one would actually do that.
