### ISSUE TITLE
JWT Auth examples for cake 4?

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/authentication#353]
Is there any examples for implementing JWT auth in cakephp 4? The only full example is for Form logins here: https://book.cakephp.org/authentication/2/en/index.html

The only examples I could find related to JWT is for a cake 3 plugin by ADmad.

**Comment by markstory** [comment]
Right now we only have the one tutorial. Adding more is something we'd like to do though.

**Comment by cnizzardini** [comment]
Yeah, it puts userland developers in a bit of a pickle trying to implement this. I've tried going through the code and unit tests, but that's not always super easy.

**Comment by cnizzardini** [comment]
Can you at least tell me if its at least possible to authenticate with an HTTP POST of a username (email in my case) and password, and then return JWT token representing the user? I am attempting to build an API in CakePHP 4 and would prefer this approach since my application client is a trusted application. Its not clear looking at the documentation (or code) if this is possible.

**Comment by markstory** [comment]
> Can you at least tell me if its at least possible to authenticate with an HTTP POST of a username (email in my case) and password, and then return JWT token representing the user?

Yes, that all sounds like it would happen outside of the authentication plugin. The JwtAuthenticator validates and decodes the contents of the JWT in each request, and can either return the payload contents or use the contents to identify a user (generally by id).

**Comment by cnizzardini** [comment]
So I got this working, sort of, in a very ugly way... I am not proud of this...

in my Plugin.php (my API is a plugin so I use this instead of Application.php)
```
    public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
    {
        $service = new AuthenticationService();

        $fields = [
            'username' => 'email',
            'password' => 'password'
        ];
        $service->loadAuthenticator('Authentication.Jwt', [
            'returnPayload' => false,
            'queryParam' => 'token',
        ]);
        $service->loadAuthenticator('Authentication.Form', [
            'fields' => $fields,
        ]);
        $service->loadIdentifier('Authentication.JwtSubject',[
            'tokenField' => 'id',
            'dataField' => 'id'
        ]);
        $service->loadIdentifier('Authentication.Password', [
            'returnPayload' => false,
            'fields' => $fields,
        ]);

        return $service;
    }
```

Then I have this in a login controller:

Needing to reference JWT and build my own token seems super hacky...so I assume this is wrong, but it does work and returns a token that is parseable on jwt.io

```php
    public function index()
    {
        if (!$this->request->is('POST')) {
            throw new MethodNotAllowedException('HTTP POST is required');
        }

        $result = $this->Authentication->getResult();

        if (!$result->isValid()) {
            throw new UnauthorizedException('Login failed');
        }

        $jwt = new JWT();
        $token = $jwt->encode($result->getData(), env('SECURITY_SALT'));

        $this->set('data', $token);
        $this->viewBuilder()->setOption('serialize', ['data']);;
    }
```
So I can now include a token as query parameter to endpoints requiring authentication via the Authentication Component. When I do this it errors.

If I go to Authentication\Authenticator\JwtAuthenticator and set $key to 'id' to match my configs it works:

```
//$key = IdentifierInterface::CREDENTIAL_JWT_SUBJECT;
$key = 'id';
```
The documentation does indicate (https://book.cakephp.org/authentication/2/en/identifiers.html) that you can configure the `dataField` though. However, if you look in `Authentication\Identifier\JwtSubjectIdentifier` it auto sets to sub. The same is true for TokenIdentifier.

So in closing, a pretty hacky night on this side of the monitor. But I feel like what I am attempting to do is a pretty common use-case for JWT.

**Comment by markstory** [comment]
> Needing to reference JWT and build my own token seems super hacky...so I assume this is wrong, but it does work and returns a token that is parseable on jwt.io

Building your own token is something we currently expect application developers to do. There are quite a few different ways that JWTs can be created and no one has proposed higher level APIs to simplify the use case you have.

> When I do this it errors. If I go to Authentication\Authenticator\JwtAuthenticator and set $key to 'id' to match my configs it works:

The jwt authenticator being tied to the sub field looks incorrect to me, as the key should be configurable. 

I have never personally setup JWT authentication, but I can try and replicate the setup you have described and get something working.

**Comment by cnizzardini** [comment]
Yes, the key not being configurable seems like a bug. For my application, rather than modifying vendor source I just altered my login method to set the `sub` key before generating the token and this works well enough for me.

I'd post my documentation since I have the Cake Docs cloned locally, but, I am apprehensive given I am not sure what the author's original intent of the usage was here.

**Comment by lpj145** [comment]
https://github.com/lpj145/cakephp_template
this template have jwt implemented yet.

**Comment by cnizzardini** [comment]
I am closing this. Documentation was added in this commit https://github.com/cakephp/authentication/commit/bd5ac6f716edaba83035b89975e44815f980a725#diff-727f6496e270e4a2b844149d551c51e3 by @rchavik

**Comment by ishanvyas22** [comment]
Created this demo project to demonstrate how this can be implemented.

https://github.com/ishanvyas22/cakephp-jwt-authentication-demo

**Comment by Novslugger** [comment]
> Created this demo project to demonstrate how this can be implemented.
> 
> https://github.com/ishanvyas22/cakephp-jwt-authentication-demo

The vendor folder is missing:

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\cakephp-jwt-auth/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\cakephp-jwt-auth\webroot\index.php on line 31

**Comment by mentisy** [comment]
> 
> 
> > Created this demo project to demonstrate how this can be implemented.
> > https://github.com/ishanvyas22/cakephp-jwt-authentication-demo
> 
> The vendor folder is missing:
> 
> Fatal error: require(): Failed opening required 'C:\xampp\htdocs\cakephp-jwt-auth/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\cakephp-jwt-auth\webroot\index.php on line 31

You'll need to run `composer install` in the terminal

**Comment by donatella71** [comment]
Hi,
I followed the instructions found in this project GitHub - ishanvyas22/cakephp-jwt-authentication-demo: CakePHP JWT authentication demo using Authentication plugin
In Application I set the userModel
$service->loadIdentifier(‘Authentication.Password’, [
‘returnPayload’ => false,
‘fields’ => $fields,
‘resolver’ => [
‘className’ => ‘Authentication.Orm’,
‘finder’ => ‘all’,
‘userModel’ => ‘Customers’,
],
Then in Customers controller implemented login, logout and index action:
The login authenticate form react axios API request on the Customers table.
After login from axios I send /customers request with the Bearer token in the Header request.
Initially the index action give me the error “Users table not found” so I’ve created the table for debugging purpose and the error give up, but now I receive error 401 “Authentication is required to continue”
$identity = $this->Authentication->getIdentity(); return null!

public function index()
{
$identity = $this->Authentication->getIdentity();
$json = [‘customer’ => $identity->getOriginalData()];
$this->set(compact(‘json’));
$this->viewBuilder()->setOption(‘serialize’, ‘json’);
$this->RequestHandler->renderAs($this, ‘json’);

}
I have insert
Debugger::dump($this->Authentication->getResult()); and this is the output

object(Authentication\Authenticator\Result) id:0 {
protected _status => ‘FAILURE_CREDENTIALS_MISSING’
protected _data => null
protected _errors => [
(int) 0 => ‘Login credentials not found’,

When using table users, all works!!!

**Comment by ghost** [comment]
https://gitlab.com/jarovarga/cakephp-api-plugin
