### ISSUE TITLE
allowUnauthenticated for the whole frontend

### ISSUE THREAD

**Issue by JRobich** [cakephp/authentication#361]
Hi there, i have in my AppController this situation:
```php
public function beforeFilter(EventInterface $event)
{
    if ($this->isAdminRouting()) {
        $this->initAdmin();
        return;
    }
    $this->initFrontend();
}

private function initFrontend()
{
    $this->Authentication->allowUnauthenticated(['login', 'logout']);
}

private function initAdmin()
{
}

protected function isAdminRouting()
{
    return ('admin' === $this->request->getParam('prefix'));
}
```
it is possibile to allow the whole frontend? for example:
`$this->Authentication->allowUnauthenticated(['*']);`

i can't find anything here:
https://book.cakephp.org/authentication/2/en/authentication-component.html

i think the documentation is not still finished....

thank you for help

**Comment by markstory** [comment]
> it is possibile to allow the whole frontend? for example:

No. You need to provide an explicit method list. You could use reflection to generate the method list though.

> i think the documentation is not still finished....

Yes the documentation is a work in progress. Are there other things you have not been able to find?

**Comment by JRobich** [comment]
Hi mark thank you for your answer, can you please explain me a little bit better what you mean with "use reflection"?

> Are there other things you have not been able to find?
yes for example how can i define the LoginRedirect
`$target = $this->Authentication->getLoginRedirect() ?? '/admin';`

thank you

**Comment by ndm2** [comment]
> No. You need to provide an explicit method list. You could use reflection to generate the method list though.

Further options would be to unload the component, disable the components automatic identity check, or to allow the requested action.

```
$this->components()->unload('Authentication');
```
```
$this->Authentication->setConfig('requireIdentity', false);
```
```
$this->Authentication->allowUnauthenticated([$this->request->getParam('action')]);
```

**Comment by dereuromark** [comment]
@JRobich 
You can also use [TinyAuth](https://github.com/dereuromark/cakephp-tinyauth) or alike that build on top of the plugins and offer convenience usage.
In your case, you can just set

    MyController = *

etc to whitelist all actions at once.

**Comment by JRobich** [comment]
Thanks all!

**Comment by dereuromark** [comment]
Documentation could still clarify this maybe.
