### ISSUE TITLE
getIdentity get the user entity

### ISSUE THREAD

**Issue by JRobich** [cakephp/authentication#363]
Hi all,

i have this scenario:

`debug($this->Authentication->getIdentity()); `

Output:

```
object(Authentication\Identity) {
	'config' => [
		'fieldMap' => [
			'id' => 'id'
		]
	],
	'data' => object(App\Model\Entity\User) {
		'id' => (int) 1,
		'uuid' => 'eb1ea1cd-3f51-4e8a-baef-46c588148c2c',
....
```

I need the User entity... i read in the doku the i can access to the ArrayAccess with get...
https://book.cakephp.org/authentication/2/en/identity-object.html

the i try:

`debug($this->Authentication->getIdentity()->get('data')); `

output:
`[]`

what am I doing wrong?

thank you so much

**Comment by dereuromark** [comment]
The data is already what you get back here.
So `->get('id')` should work here, or `->get('uuid')`

**Comment by JRobich** [comment]
thank you mark for your answer there is no way to get the whole entity?

thank you for help me

**Comment by dereuromark** [comment]
You can just check the source code
It is all there: https://github.com/cakephp/authentication/blob/master/src/Identity.php#L177

**Comment by JRobich** [comment]
Thank you so much mark!
