### ISSUE TITLE
Cake\Http\ServerRequest can't `serialize()` when Authentication.Orm resolver is used

### ISSUE THREAD

**Issue by mtak3** [cakephp/authentication#364]
```
php -r 'try {serialize(new PDO("sqlite:///tmp/test"));} catch (Exception $e) { echo $e; }'
Exception: Serialization of 'PDO' is not allowed in Command line code:1
Stack trace:
#0 Command line code(1): serialize(Object(PDO))
#1 {main}
```

https://github.com/cakephp/authentication/blob/2.1.0/src/Identifier/Resolver/OrmResolver.php#L20
```
use Cake\ORM\Locator\LocatorAwareTrait;
```

https://github.com/cakephp/cakephp/blob/4.0.4/src/ORM/Locator/LocatorAwareTrait.php#L31
```
    protected $_tableLocator;
```
have Table's instance.
And Table's instance have PDO's instance.

`\Cake\ORM\TableRegistry::getTableLocator()` instead of `LocatorAwareTrait`. PDO's instance will not be included in ServerRequest.

**Comment by markstory** [comment]
Why are you serializing requests?

**Comment by mtak3** [comment]
> Why are you serializing requests?

I want to release the application with a "small start" .

Operation log function: Only when detailed specifications have not been determined and display is determined to be necessary.

Save the serialized "request".

Once the detailed specifications are decided, I would like to convert them according to the specifications and use them.

**Comment by markstory** [comment]
Ok, can't say I totally understand all of that, but if you'd like to put a pull request together of the changes you're proposing we can talk about it further.

**Comment by ADmad** [comment]
You should use a middleware like https://github.com/php-middleware/log-http-messages to get serialized version of request/response messages with all relevant info instance directly trying to serialize `ServerRequest` objects.

**Comment by ADmad** [comment]
Or just try directly using this class https://github.com/laminas/laminas-diactoros/blob/master/src/Request/ArraySerializer.php.

**Comment by mtak3** [comment]
> Or just try directly using this class https://github.com/laminas/laminas-diactoros/blob/master/src/Request/ArraySerializer.php.

A very good way.
That package is already installed as a dependency.
Therefore, it is possible to respond with few modifications.

Thank you very much.
