### ISSUE TITLE
Allow Identifier Callback to return Result

### ISSUE THREAD

**Issue by lilHermit** [cakephp/authentication#367]
It would be useful to allow the Identifier Callback to return Result (as well as ArrayAccess|null) as this allows us to return error messages along with the failure. Currently I've had add to Session for Flash which isn't great.

**Comment by lilHermit** [comment]
I'm happy to do a PR if it helps

**Comment by markstory** [comment]
Identifiers don't have a result type yet. Were you thinking of re-using the authenticator result object?

**Comment by lilHermit** [comment]
It was so I can pass an error message back without using session as that feels hacky.

I thought something like

`src/Identifier/CallbackIdentifier.php`
```php
        $result = $callback($data);
        if ($result instanceof Result) {
            $this->_errors = $result->getErrors();
            return $result->getData();
        }
        if ($result === null || $result instanceof ArrayAccess) {
            return $result;
        }
```

**Comment by markstory** [comment]
Being able to pass errors back to the authenticator seems useful to me :+1:

**Comment by lilHermit** [comment]
@markstory Thoughts on the above implementation?! If you are happy I can create a PR with tests

**Comment by markstory** [comment]
@lilHermit I think it works well, a pull request would be great.
