### ISSUE TITLE
Callbacks for afterLogin/afterSetIdentity, beforeLogout/beforeClearIdentity?

### ISSUE THREAD

**Issue by inoas** [cakephp/authentication#37]
Without digging too much into the code, just looking at the docs:
- Is it already possible to run custom code on callbacks: after-login/after-set-identity (stateful/stateless), before-logout/before-clear-identity? (stateful only)
- If not would you deem it worthwhile?
- Example applications: update last_login_datetime, log failed and successful user sign-in attempts, log user sign-outs

**Comment by burzum** [comment]
I don't see a point in having afterSetIdentity(). Because you'll have to set it, there is no code in the plugin that is calling this methods. It's only purpose is to allow the user of the code to manually set an identity for whatever reason he has to do so.

**Comment by markstory** [comment]
Before we add more events, is there no other way to do the task you had listed before?

**Comment by burzum** [comment]
@markstory we already have an event for logout. Actually there *could* be before and afterLogout. However, I don't think it's *that* useful because you'll still manually call logout() so you can already to things before and after calling that method in your app.

See https://github.com/cakephp/authentication/blob/master/src/Controller/Component/AuthenticationComponent.php#L113-L130

**Comment by markstory** [comment]
Ok. I'm not a huge fan of before and after events unless we really need them. Each event we add, contributes complexity and runtime overhead.

**Comment by ADmad** [comment]
I too don't think we need any more events then what are already used by core AuthComponent.

**Comment by burzum** [comment]
@markstory agreed. So lets remove the even [here](https://github.com/cakephp/authentication/blob/master/src/Controller/Component/AuthenticationComponent.php#L113-L130)? You can perfectly well implement before and after logic without it. 

The only one that I think is useful is the one I'm adding in https://github.com/cakephp/authentication/pull/42

**Comment by markstory** [comment]
I agree that the `Authentication.logout` event is not necessary, and is something that could be implemented by the applications that need it to save overhead/complexity.

**Comment by burzum** [comment]
OK. I've done it in the branch `after-identify-event`. I think we can close this discussion now or is there any other event than `Authentication.afterIdentify` that is *really* needed?
