### ISSUE TITLE
setIdentity not update Auth Session

### ISSUE THREAD

**Issue by x-zolezzi** [cakephp/authentication#370]
Hi,

When I try setIdentity my Auth session aren't change with the new value.

```php
$user = $this->Users->find()->where(['Users.id' => $this->Authentication->getIdentityData('id')])->first();`

debug($this->Authentication->getIdentityData('firstname')); // Good old value
debug($this->request->getSession()->read('Auth.firstname')); // Good old value

$user->firstname = 'NEW FIRSTNAME';
$this->Authentication->setIdentity($user);

if ($this->Users->save($user)) {

     $this->Authentication->setIdentity($user);

     debug($this->Authentication->getIdentityData('firstname')); // Good new value
     debug($this->request->getSession()->read('Auth.firstname')); // Bad new value => old value
}
```

Thx

**Comment by markstory** [comment]
The session is not updated until the *end* of the request. The subsequent requests will have the correct data in the session however, you should use the `identity` attribute in the request to ensure you always have the current data.

**Comment by x-zolezzi** [comment]
I haven't the updated data in `$this->request->getAttribute('identity')->get('firstname')`
It's always old value

**Comment by markstory** [comment]
How have you setup the authentication plugin? In my applications the user data is refreshed.

**Comment by x-zolezzi** [comment]
```php
public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
    {
        $authenticationService = new AuthenticationService([
            'unauthenticatedRedirect' => \Cake\Routing\Router::url('/'),
            'queryParam' => 'redirect',
        ]);
        $authenticationService->loadIdentifier('Authentication.Password', [
            'fields' => [
                'username' => 'username',
                'password' => 'password',
            ]
        ]);
        $authenticationService->loadAuthenticator('Authentication.Session');
        $authenticationService->loadAuthenticator('Authentication.Cookie', [
            'cookie' => [
                'secure' => true
            ]
        ]); //@TODO: Secure Cookie
        $authenticationService->loadAuthenticator('Authentication.Form', [
            'fields' => [
                'username' => 'username',
                'password' => 'password',
            ],
        ]);

        return $authenticationService;
    }
```

**Comment by markstory** [comment]
> But I don't want have SQL on each request, I want only use Session Auth and update it when I want.

Not loading the user from the database on each request introduces the possibility for user data to diverge when there are concurrent sessions running though.

You might want to see what is going on inside the `setIdentity()` method. https://github.com/cakephp/authentication/blob/5e59b215de07d2b7a929c78f519fd4c135bbe8ae/src/Controller/Component/AuthenticationComponent.php#L278-L285

is what `setIdentity` does and the sessionauthenticator implementation of those methods looks like https://github.com/cakephp/authentication/blob/5e59b215de07d2b7a929c78f519fd4c135bbe8ae/src/Authenticator/SessionAuthenticator.php#L85-L117

You should be seeing new session data *and* the session id being rotated on each `setIdentity()` call. If you are only interested in updating the session why are you not doing that directly?
