### ISSUE TITLE
Customize UnauthenticatedException message

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/authentication#374]
Currently in `2.1.0`, I get a message like this for unauthenticated requests: 

```
{
  "exception": "UnauthenticatedException",
  "message": "No identity found. You can skip this check by configuring  `requireIdentity` to be `false`.",
  "url": "/api/v1/dealers",
  "code": 401,
  "file": "/var/www/personal/easyupp/vendor/cakephp/authentication/src/Controller/Component/AuthenticationComponent.php",
  "line": 176
}
```

Fine for developers, but is there a way we can change this message? I poked around the configs and the code and there doesn't appear to be a way to overwrite this or even catch the exception and throw our own.

**Comment by markstory** [comment]
There isn't a good way to overwrite this error message currently. It comes from the AuthenticationComponent, so we could add a configuration option to overwrite this message.

**Comment by cnizzardini** [comment]
I wonder what would be better here. Customizing the error message, which is kinda meh and seems like a bloated option or maybe a callback option instead. That might be more versatile.

**Comment by markstory** [comment]
I'm fine with either customizing the message or a callback based approach.

**Comment by cnizzardini** [comment]
Was this handled in a more recent version?

**Comment by ADmad** [comment]
Fixed in https://github.com/cakephp/authentication/pull/430.
