### ISSUE TITLE
Salted Password Identifier

### ISSUE THREAD

**Issue by smarek** [cakephp/authentication#375]
Hi, i'd like to check the user provided password but before hashing the password, I need to concat the provided password with salt stored with DAO Identity/Entity. I've came up with solution, but **I'd like to know, if this is recommended way to do such thing**. Eg. extending from lib provided PasswordIdentifier and overriding the method seems *a bit hacky*

```php
<?php
declare(strict_types=1);

namespace App\Authentication;

use App\Model\Entity\User;
use Authentication\Identifier\PasswordIdentifier;
use Authentication\Identifier\Resolver\ResolverInterface;

class PasswordSaltIdentifier extends PasswordIdentifier
{

    protected function _checkPassword($identity, ?string $password): bool
    {
        $passwordField = $this->getConfig('fields.' . self::CREDENTIAL_PASSWORD);

        if ($identity === null) {
            $identity = [
                $passwordField => '',
            ];
        }

        $hasher = $this->getPasswordHasher();
        $hashedPassword = $identity[$passwordField];
        // code of the method is identical to parent implementation, except for this block
        $passwordToCheck = (string)$password;
        if ($identity instanceof User) {
            $passwordToCheck .= $identity->salt;
        }
        if (!$hasher->check($passwordToCheck, $hashedPassword)) {
        // end of changed block
            return false;
        }

        $this->_needsPasswordRehash = $hasher->needsRehash($hashedPassword);

        return true;
    }

}
```

Maybe i'd like for **authentication** lib to provide a way, to correctly modifiy the user-provided password before hashing it, instead of assuming that the implementation of  `_checkPassword` remains the same in the parent.

One solution this might have is to pass the `$identity` along with `$passwordToCheck` and `$hashedPassword` to configured `PasswordHasher::check()`, so this could be solved by subclassing just the `DefaultPasswordHasher` instead of `PasswordIdentifier`. Said context (identity) in passwordHasher, might be useful in more ways probably.

**Comment by ADmad** [comment]
I don't really see the benefit of storing a salt for each user is a separate field when hashing schemes like bcrypt can already create unique salt on each usage and include it in the generated hash itself.

That's said there's nothing with extending `PasswordIdentifier` and overriding relevant parts to suit your needs. That's where modifying the password should be done, not inside `PasswordHasher`.
