### ISSUE TITLE
HttpBasic authentication issue

### ISSUE THREAD

**Issue by devateminent** [cakephp/authentication#381]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.7.

### What you did
Guys, I am creating stateless authentication using HttpBasic in cakephp 4.0.7 but in case of wrong details, I am getting blank response with 401. 
public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
    {
        $authenticationService = new AuthenticationService();

        // Load identifiers, ensure we check username and password fields
        $authenticationService->loadIdentifier('Authentication.Password', [
            'fields' => [
                'username' => 'username',
                'password' => 'api_key',
            ]
        ]);

        $authenticationService->loadAuthenticator('Authentication.HttpBasic');

        return $authenticationService;
    }

### What happened
For wrong details, I got 401 status code but blank body.

### What you expected to happen
A body message also with code and response.

**Comment by ADmad** [comment]
That's the expected response for HTTP Basic Auth failures. You would only get a 401 status code and `WWW-Authenticate` header with empty body.

Your browser should show you popup to enter login details. For any other client it should check for 401 status code and handle it accordingly.

**Comment by markstory** [comment]
Closing as the empty 401 is how basic auth failures are supposed to be handled.

**Comment by devateminent** [comment]
@markstory @ADmad Thanks for your help. But we were getting exception with message in cakephp 3.8. In this new version $this->Authentication->addUnauthenticatedActions also not working for any action with HttpBasic authentication.

**Comment by devateminent** [comment]
I want to do httpbasic authentication for my apis but form authentication for main site. Is that possible?

**Comment by markstory** [comment]
> In this new version $this->Authentication->addUnauthenticatedActions also not working for any action with HttpBasic authentication.

Yes, basic authentication failures are handled in the AuthenticationMiddleware before any controllers are invoked which is a difference from AuthComponent.

> I want to do httpbasic authentication for my apis but form authentication for main site. Is that possible?

It is if you apply the middleware different based on the URL scope. The documentation on how to do this doesn't really exist yet, but I can add an example.

**Comment by devateminent** [comment]
@markstory Yes, please add an example. I need basic authentication for apis on same application. I get stuck there.

**Comment by devateminent** [comment]
@markstory Thanks for your reply. It really helped me. Just need one more confirmation.
For basic authentication we will write it like as below:

// Load identifiers, ensure we check username and password fields
        $service->loadIdentifier('Authentication.Password', [
            'fields' => [
                'username' => 'username',
                'password' => 'api_key',
            ]
        ]);

        $service->loadAuthenticator('Authentication.HttpBasic');

Please confirm.
