### ISSUE TITLE
Not able to redirect back to same URL after Logged in for authenticated URL, $this->getLoginRedirect() is giving Null value

### ISSUE THREAD

**Issue by jaswanthvarma** [cakephp/authentication#386]
Hi,

I wanted user to go back to some random authenticated page which he wants to view after login but it is redirecting back to index page in Authentication Plugin Cakephp 4, which is used to work fine in Cakephp 3,

$this->getLoginRedirect()  is giving NULL value, what should i do for making user to go back to same page after login even with the post values.

**Comment by ADmad** [comment]
https://book.cakephp.org/authentication/2/en/migration-from-the-authcomponent.html#migrating-unauthenticated-redirects

**Comment by othercorey** [comment]
@jaswanthvarma Does this resolve the issue?
