### ISSUE TITLE
Using Uppercase in database field names confuses the plugin

### ISSUE THREAD

**Issue by VARGA-Peter** [cakephp/authentication#391]
Using uppercase characters in the database table fields, especially the password field, confuses the plugin and so for example the text in the password field is a plain text instead of the bullets.

I changed it `templates/Users/add.php & login.php`
```
        <?= $this->Form->control('Email') ?>
        <?= $this->Form->control('Password') ?>

```

I modify it also in `/src/Application.php`

```
        // Load identifiers, ensure we check email and password fields
        $authenticationService->loadIdentifier('Authentication.Password', [
            'fields' => [
                'username'  => 'Email',
                'password'  => 'Password',
            ]
        ]);
    
        // Load the authenticators, you want session first
        $authenticationService->loadAuthenticator('Authentication.Session');
        // Configure form data check to pick email and password
        $authenticationService->loadAuthenticator('Authentication.Form', [
            'fields' => [
                'username'  => 'Email',
                'password'  => 'Password',
            ],
            'loginUrl' => '/users/login',
        ]);
```

**Comment by ADmad** [comment]
The issue has nothing to do with this plugin. By default the FormHelper generates password only for lowercased password field.

To fix your issue you just have to explicitly specific the input type in your FormHelper::control() call:

`<?= $this->Form->control('Password', ['type' => 'password']) ?>`.

**Comment by VARGA-Peter** [comment]
Thank you for the fast reply. Yes, the way you explain it will for sure work [I am a bloody cakePHP beginner] but I can point out that I have to _introduce/map_ a field as the password [`'password'  => 'Password'`] and here the plugin could check that it isn't the default name `'password'` and could do the change on its own [may be using a setting]...

However, thank you for your help and I apologize for any inconvenience.

**Comment by ADmad** [comment]
CakePHP follows "convention over configuration" philosophy. Since you didn't follow the convention of lowercased field names you have to do the extra configuration.

Doing things like passing over authenticator config over to the FormHelper would be unnecessary coupling and code complexity.

**Comment by VARGA-Peter** [comment]
I understand and thank you for your time. Very kind of you!
