### ISSUE TITLE
Homogeneous api for identifiers and authenticators

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/authentication#40]
Why don't identifiers and authenticators get loaded on a similar way? I mean, the use case it's pretty much the same: to load a class (optionally with its config) into a stack/set of elements. If you take a look into its load methods and are pretty similar...

Right now we have:

```php
        // Load identifiers
        $service->identifiers()->load('Authentication.Orm', [
            'fields' => [
                'username' => 'email',
                'password' => 'password'
            ]
        ]);

        // Load the authenticators, you want session first
        $service->loadAuthenticator('Authentication.Session');
        $service->loadAuthenticator('Authentication.Form');
```

I wonder why don't we have same way on both:

```php
        // Load identifiers
        $service->identifiers()->load('Authentication.Orm', [/*...config...*/]);

        // Load the authenticators, you want session first
        $service->authenticators()->load('Authentication.Session', [/*...config...*/]);
        $service->authenticators()->load('Authentication.Form'); // without config
```

or:

```php
        // Load identifiers
        $service->loadIdentifier('Authentication.Orm', [/*...config...*/]);

        // Load the authenticators, you want session first
        $service->loadAuthenticator('Authentication.Session', [/*...config...*/]);
        $service->loadAuthenticator('Authentication.Form'); // without config
```

I guess it's more a question than a bug, but I just noticed that and wanted to let you know. I think that will be easier to learn/remember an api when things are done in a "standard" way.

**Comment by markstory** [comment]
Consistency does make life simpler. I think having service level methods `$service->load(Authenticator|Identifier)` is better as there is one fewer method/object to interact with in simple use cases.

**Comment by dereuromark** [comment]
PR open.
