### ISSUE TITLE
FormAuthenticator causes Error: Serialization of 'PDO' is not allowed

### ISSUE THREAD

**Issue by chyt** [cakephp/authentication#405]
I am trying to switch from deprecated `AuthComponent` to the new authentication plugin on Cakephp 4.1.4. I have read through the docs and am following the standard quick start, using `Session` and `Form` authenticators with `Password` identifier and a custom finder resolver. 

Upon successful authentication, I get this error:

![Screen Shot 2020-09-29 at 9 39 21 AM](https://user-images.githubusercontent.com/3202957/94573385-a931c480-0237-11eb-99d5-d1647a715a12.png)

This appears to be caused by the fact that the `$user` retrieved in the `FormAuthenticator` is an instance of `App\Model\Entity\User`. This is a PDO object, which is then being serialized at some point and causing the error. I can solve the problem with a custom resolver where I do something like `$user = $user->toArray()`. 

However, I'm not sure why I need to do this in the first place. Looking at the screenshot, the serialization attempt is happening very early on in the stack trace before it gets into any application code. How do I debug and resolve this?

**Comment by ndm2** [comment]
The stacktrace might be a little misleading, the error is happening at the end of the request, after your application code has run, hence there's no trace into your application code.

Your user object is just an entity, and they can usually be serialized just fine, as ideally they shouldn't be too much more than stupid data transfer objects.

`PDO` here refers to an instance of the `PDO` class, which normally shouldn't be anywhere near your entities. I would start with debugging `$user` to figure what the internal data structure looks like, that might help to get an idea of how a PDO instance might have slipped in there.

**Comment by chyt** [comment]
I figured it out, it's because I'm loading some other `Table` objects when I initialize a `User` entity. I know that's not the best practice, but in the meantime I'll just stick with the `toArray()` conversion, which I think should work fine for my purposes. Thanks for your help!
