### ISSUE TITLE
$this->Authentication->allowUnauthenticated Not Working In Controller Action With Underscore

### ISSUE THREAD

**Issue by ordinarywebguy** [cakephp/authentication#409]
* [x] bug

* CakePHP Version: 4.1.4
* cakephp/authentication: 2.3.0
* Platform and Target: Ubuntu 18.04.5 LTS

### What you did

```
class MyController extends AppController
{
    public function beforeFilter(EventInterface $event) 
    {
        $this->Authentication->allowUnauthenticated([
            'my_action'
        ]);
        parent::beforeFilter($event);
    }

    public function my_action()
    {
        echo 123;
        exit;
    }
}
```

### What happened
It redirects to /?redirect=%2Fmy_controller%2Fmy_action

### What you expected to happen
It should be able to display the page without user authentication. It's working all fine if there's no underscore in the action name.

**Comment by dereuromark** [comment]
Please note that all actions in controllers must be camelCase as per convention since 4.0.0.
Maybe we need to make the docs here more clear on that one.

**Comment by markstory** [comment]
What is the value of `$this->request->getParam('action')` in your underscored action names? That is what AuthenticationComponent compares against.

**Comment by ordinarywebguy** [comment]
@markstory the $this->request->getParam('action') = **myAction**. Got it! Thanks! :+1:

**Comment by dereuromark** [comment]
Looks like the old method syntax still works, but gets already normalized to the expected camelBacked form then.
