### ISSUE TITLE
New Login without first Logout

### ISSUE THREAD

**Issue by OneHatRepo** [cakephp/authentication#417]
I am using the **Authentication.Session** and **Authentication.Form** authenticators.
Everything works fine when a user visits `/login`, does some work, and then visits `/logout`

login:
`$this->Authentication->setIdentity($user);`

logout:
`$this->Authentication->logout()`

The problem is if one user logs in, then in the same browser tries to login as a different user by visiting `/login` again without first logging out the original user. He tries to submit the form with other user credentials. The session authenticator automatically authenticates the user _as the previously logged-in user,_ and then ignores the newly submitted login credentials.

The [documentation says](https://book.cakephp.org/authentication/2/en/index.html#getting-started) that when combining authenticators, "Session should be first." This, I believe is the problem. When reversing the order, putting the Form authenticator first, the problem goes away.

So, my question is, "Is there any downside to putting the Form authenticator first, and if not, then shouldn't the documentation be changed to suggest putting the Form authenticator first?

Thanks!

**Comment by markstory** [comment]
> So, my question is, "Is there any downside to putting the Form authenticator first, and if not, then shouldn't the documentation be changed to suggest putting the Form authenticator first?

The only downside is that the FormAuthenticator will run a small amount of code on every request. Other than that there shouldn't be any real downsides to putting FormAuthenticator first. An update to the documentation to put FormAuthenticator first sounds reasonable to me, as it does make the scenario you described simpler and I think that is a situation that will come up frequently during development.

**Comment by othercorey** [comment]
I think the only other solution is to log the user out whenever they load `/login` which might not be optimal.

**Comment by OneHatRepo** [comment]
Do you mean when the user loads `/login` to get the form? I did decide to do that, and it helps, but not in all circumstances. I often use CakePHP as an API backend to mobile apps. In that case, the mobile app hits `/login` without ever having loaded the form, so it never has opportunity to first logout.

**Comment by OneHatRepo** [comment]
In fact the mobile app scenario is what caused me to find the issue in the first place. Users were sharing mobile devices and trying to login with different accounts, but it wasn't acknowledging the newly submitted credentials.

**Comment by OneHatRepo** [comment]
I think I have settled on this:

```
public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface {
	$service = new AuthenticationService();

...

	// Load the authenticators.
	if (preg_match('/login|logout/i', $request->getUri()->getPath())) {
		$service->loadAuthenticator('Authentication.Form', [
			'fields' => $fields,
			// 'checkFullUrl' => true,
		]);
	}
	$service->loadAuthenticator('Authentication.Session');

...

	return $service;
}
```

It only loads the **Authentication.Form** authenticator when on the `/login` or `/logout` URLs. Everything else is session only.

**Comment by ADmad** [comment]
> I often use CakePHP as an API backend to mobile apps.

Using session based login for mobile apps is quite uncommon. Mobile apps usually communicate with the backend using stateless API.

**Comment by OneHatRepo** [comment]
The apps I'm referring to don't need to scale massively, so using session-based state works well.
