### ISSUE TITLE
[bug] UnauthenticatedException 401 error code is cast to 500 by cakephp ExceptionRenderer

### ISSUE THREAD

**Issue by liqueurdetoile** [cakephp/authentication#428]
Hi,

Before all, I must say I'm very found of new middleware approach for authentication ❤️ 

Versions used :
- cakephp : 4.2.1
- cakephp/authentication ; 2.3.1

I've set up a non redirected access token based auth for a REST API and used to get a 401 error in case of auth failure but receives a 500 instead since cakephp upgrade to 4.2, confirmed with debug mode disabled.

It's coming from the new behavior of [cakephp exception renderer](https://book.cakephp.org/4/en/appendices/4-2-migration-guide.html#error). Because the `UnauthenticatedException` thrown by plugin is not an instance of `HttpException` nor registered in the `exceptionHttpCodes` of the renderer for a 401 code, it forces a 500 response code.

I was not sure about where to report it. Should I also open an issue on cakephp ? Close this one ? Consider it is a final behavior and override exception renderer as described in migration guide ?

Thanks !

**Comment by markstory** [comment]
I think we need to change base class of that exception.  We might already have that change done, just not released yet.

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/authentication/pull/429
