### ISSUE TITLE
Custom hash function for Authentication.Fallback

### ISSUE THREAD

**Issue by theChaosCoder** [cakephp/authentication#433]
Hi, so basically I want to migrate old cake2 passwords to new ones. I want to use the Fallback option for that. 
The problem is I don't see any way to use a custom hash function. I read the docs (and tutorials) but now I'm stuck at this problem. 

Is there a custom function option? Or how would I use it in combinaton with the fallback option?

My legacy hash looks like this: `$hash = md5($password . 'mystring');`

```
# from docs
# hashtype does not help me here
$service->loadIdentifier('Authentication.Password', [
    // Other config options
    'passwordHasher' => [
        'className' => 'Authentication.Fallback',
        'hashers' => [
            'Authentication.Default',
            [
                'className' => 'Authentication.Legacy',
                'hashType' => 'md5',
                'salt' => false // turn off default usage of salt
            ],
        ]
    ]
]);
```

**Comment by markstory** [comment]
> Is there a custom function option? Or how would I use it in combinaton with the fallback option?

You should build your own password hasher implementation.

**Comment by theChaosCoder** [comment]
I could "clone" LegacyPasswordHasher.php. But how would I let "Authentication" know about the new hasher?
This works `'className' => 'Authentication.Test'` when I put my file in vendor->cakephph->authentication, but this does not seem like the correct solution.

```
'passwordHasher' => [
                'className' => 'Authentication.Fallback',
                'hashers' => [
                    'Authentication.Default',
                    [
                        'className' => 'Authentication.Test',
                        'hashType' => 'md5',
                        'salt' => false // turn off default usage of salt
                    ],
                ]
            ]
```

**Comment by markstory** [comment]
the className key could either be `MyTest` or the full classname from `MyTest::class`.

**Comment by theChaosCoder** [comment]
Ahh got it, works now. Thank you!
