### ISSUE TITLE
composer install line for authentication should be updated

### ISSUE THREAD

**Issue by theChaosCoder** [cakephp/authentication#434]
I think the composer line should be changed from
`php composer.phar require "cakephp/authentication:^2.0"`
to 
`php composer.phar require "cakephp/authentication`

The first line will install version 2 and not the newest one v2.5. 
The problem: v2.0 always uses salt = true (fixed in newer version) while in the example code, it shows what you can use salt=false.
https://book.cakephp.org/authentication/2/en/password-hashers.html#upgrading-hashing-algorithms

I wasted at least 1 hour  trying to make login work with md5 hash + without salt...

https://book.cakephp.org/4/en/tutorials-and-examples/cms/authentication.html#installing-authentication-plugin
https://book.cakephp.org/authentication/2/en/index.html

```
'hashers' => [
            'Authentication.Default',
            [
                'className' => 'Authentication.Legacy',
                'hashType' => 'md5',
                'salt' => false // turn off default usage of salt <== ALWAYS TRUE in 2.0 /!\
            ],
        ]

```

**Comment by garas** [comment]
`^2.0` accepts `>=2.0.0,<3.0.0`, so it should install 2.5.

Some ` composer.json` dependencies had changed in 2.4, they might block newer version.
Check with `php composer.phar why-not cakephp/authentication 2.5` if something blocks.

**Comment by theChaosCoder** [comment]
On my machine it installs 2.0
I'm using composer v2 (on Windows10 64bit)

```
composer require cakephp/authentication
Using version ^2.5 for cakephp/authentication
./composer.json has been updated
Running composer update cakephp/authentication
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading cakephp/authentication (2.0.0 => 2.5.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading cakephp/authentication (2.0.0 => 2.5.0): Extracting archive
Generating autoload files
53 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

```
composer require "cakephp/authentication:^2.0"
./composer.json has been updated
Running composer update cakephp/authentication
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Downgrading cakephp/authentication (2.5.0 => 2.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading cakephp/authentication (2.5.0 => 2.0.0): Extracting archive
Generating autoload files
53 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by theChaosCoder** [comment]
v2.5 is installed
```
composer why-not cakephp/authentication 2.5
There is no installed package depending on "cakephp/authentication" in versions not matching 2.5
```

```
"Downgrade"
composer require "cakephp/authentication:^2.0"
....
  - Downgrading cakephp/authentication (2.5.0 => 2.0.0): Extracting archive
```

```
composer why-not cakephp/authentication 2.5
cakephp/app  -  requires  cakephp/authentication (2.0)
```

**Comment by garas** [comment]
2.0.0 was installed, because Composer probably received `^2.0` as `2.0`.

`^` can be [lost in Windows](https://www.github.com/composer/composer/issues/5151).

**Comment by theChaosCoder** [comment]
I think this could be it.
I installed via powershell 

composer require "cakephp/authentication:^2.0" saves it in composer.json as:
```
{
    "require": {
        "cakephp/authentication": "2.0"
    }
}
```

**Comment by ndm2** [comment]
[**It should work fine in all other shells**](https://github.com/cakephp/authentication/pull/422), Powershell unfortunately ignores the quotes, and since `^` is an escaping character on the Windows shells, you'll effectively end up with `cakephp/authentication:2.0`.

There's not much that can be done here, other than using for example `~`, but that constraint operator seems frowned upon 🙃

**Comment by theChaosCoder** [comment]
I tried it in CMD => works. I thought powershell will save us all    **( ಥ ﹏ ಥ )**

Thx for you help, I will close this then.

**Comment by othercorey** [comment]
Does `cakephp/authentication:2.x` work with powershell?

**Comment by ndm2** [comment]
It does, but I'm afraid proposing this for the docs will still lure @dereuromark out of the bushes to kick you in the shin.

**Comment by othercorey** [comment]
Not much you can do about it. Just fix the composer.json entry afterwards.

**Comment by theChaosCoder** [comment]
Yep  `cakephp/authentication:2.x` does work great.
