### ISSUE TITLE
AuthenticationRequiredException not an HttpException. Why?

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/authentication#435]
Hello there,

I have the following problem:
the [AuthenticationRequiredException](https://github.com/cakephp/authentication/blob/master/src/Authenticator/AuthenticationRequiredException.php) is usefull because it enables to pass headers to the response [here](https://github.com/cakephp/authentication/blob/master/src/Middleware/AuthenticationMiddleware.php#L112). Great!

Thus, if I throw an AuthenticationRequiredException in my CustomAuthenticator, I can pass elements to the header of the response from my CustomAuthenticator. All that I need, perfect.

Now the AuthenticationRequiredException does not extend the HttpException, but a simple RuntimeException. As opposed to the [UnauthenticatedException](https://github.com/cakephp/authentication/blob/master/src/Authenticator/UnauthenticatedException.php). Strange. Is there a reason for that?

Not being an HttpException, it is not catched by my ErrorController, and this is really annoying.

My question thus: would it be possible to have the AuthenticationRequiredException extending the HttpException class? I can make a PR for that. Or is there a good reason to avoid that?

**Comment by markstory** [comment]
> My question thus: would it be possible to have the AuthenticationRequiredException extending the HttpException class? I can make a PR for that. Or is there a good reason to avoid that?

It should be extending `HttpException` and was missed in earlier fixes. A pull request would be greatly appreciated.

**Comment by othercorey** [comment]
That might have been my mistake. I might have thought it was an internal exception when updating all the related exceptions for the HttpException change in cakephp 4.2.
