### ISSUE TITLE
Spoof session through remember-me cookie after database leak

### ISSUE THREAD

**Issue by RobertoRoos** [cakephp/authentication#439]
Not entirely sure if I'm correct, but does the remember-me cookie allow users to impersonate someone of they had access to the application database?

The remember-me token is a [hash of the username and password hash](https://github.com/cakephp/authentication/blob/master/src/Authenticator/CookieAuthenticator.php#L152) (`token = hash(username + hash(password))`), so having the hashed password would be enough to create a correct token, which could be achieved through a database leak.

Obviously a database leak is already bad, though with form authentication having a hashed password doesn't get you anywhere yet.

If this is correct, would it be an option to add a feature for generated key-token pairs to use in cookie authentication?

**Comment by markstory** [comment]
> If this is correct, would it be an option to add a feature for generated key-token pairs to use in cookie authentication?

Wouldn't this token need to be stored in the database as well?

**Comment by ndm2** [comment]
Maybe as a basic additional barrier the token could be signed with the current application salt, similar to the CSRF token.

**Comment by RobertoRoos** [comment]
> Wouldn't this token need to be stored in the database as well?

If you would save the secret token as plaintext. But usually you generate an identifier and a secret token. You send both to the client, and store the secret only as a hash (like a password). The verification token is then a concatenation of the identifier and the token hash. Only the owner of the original secret could do this. (See [this nice SO answer](https://stackoverflow.com/questions/244882/what-is-the-best-way-to-implement-remember-me-for-a-website).)


> Maybe as a basic additional barrier the token could be signed with the current application salt, similar to the CSRF token.

Maybe. I guess that might be easier to accomplish than an extra database table.

**Comment by markstory** [comment]
> Maybe as a basic additional barrier the token could be signed with the current application salt, similar to the CSRF token.

Isn't that what this is doing? https://github.com/cakephp/authentication/blob/master/src/Authenticator/CookieAuthenticator.php#L168-L175

The username + password hash, are rehashed using the application's password hasher (which also salts). If you *only* have a database dump and not the application configuration you shouldn't be able generate a remember me token from what I can see in the code.

**Comment by ndm2** [comment]
> The username + password hash, are rehashed using the application's password hasher (which also salts)

But that's just a dynamic salt that ensures uniqueness, it's not a secret. If an attacker obtains access to the database of an application that uses the default password hasher, then they can simply do `password_hash($usernameFromDb + $hashedPasswordFromDb)` and they will have a valid cookie token.

**Comment by othercorey** [comment]
Do we consider the salt config more secure than the db?

**Comment by ndm2** [comment]
Just from my personal experience I'd say that the filesystem / app config is usually a little more secure, simply because SQL injection vulnerabilities are usually far more widespread. Once an attacker has read/write access to the filesystem it's over anyways.

The salt is certainly not the pinnacle of security, but at least it's an additional layer that would need to be breached, which certainly wouldn't hurt, especially if it can be implemented at pretty much no cost.

**Comment by markstory** [comment]
> But that's just a dynamic salt that ensures uniqueness, it's not a secret.

You're right my mistake. Adding an additional HMAC an option, but we'd need to take care to continue accepting the current format lest we break all the remember me tokens in the wild.

**Comment by ndm2** [comment]
Personally I would be fine if such a change would invalidate my authentication cookie, actually I would very much welcome it :)

But I guess there would be complaints, so if this needs to be implemented in a backwards compatible way, then there's probably no way around introducing an option.

**Comment by ADmad** [comment]
Having the option turned off by default means most people won't turn it on. Instead it should be on by default and we can mention in the (minor) release statement that those who want to keep existing cookies valid can turn it off.

**Comment by markstory** [comment]
> Aside from that, I would still be in favour of a dedicated identifier+token system. But maybe that would exceed the scope of this plugin? It is acceptable to include a database table with it?

Would it require a separate database table, it could be a field on the user table similar to how API token authentication works.

**Comment by RobertoRoos** [comment]
The problem with a single field would be having multiple devices. If don't store the original secret you cannot grant a new cookie token.

**Comment by markstory** [comment]
Could you not provide the same token to all devices for the user? A separate table adds more complexity as schema needs to be managed, relationships created and implies that end users would able to view and revoke tokens on devices individually.

**Comment by RobertoRoos** [comment]
To give it out multiple times means having to save the secret as plain text, which brings us back to the same issue with using the hashed password.
The only advantage of a single token is it could be reset without affecting the user password I guess.

**Comment by markstory** [comment]
> To give it out multiple times means having to save the secret as plain text, which brings us back to the same issue with using the hashed password.

Could the cookie value not also contain an HMAC? That would allow the server to validate that the token was signed by the application and not a 3rd party in case the database is leaked. The steps would be:

1. Split the cookie into the value + hmac.
2. Look up the user based on `username`
3. Compare the provided hmac with a new hmac of the `plaintoken`. This is done after the user is queried so that we can mitigate timing attacks on usernames.
4. Success or Failure

The plain token could be a separate field (alternate location of the `password` field) or a discrete field.

If we do add a new path I think it would need to be enabled by default and have a configuration option to enable compatibility with no hmac values. This allows new applications to be safer in the future and developers to invalidate their existing login tokens if they want to.

**Comment by ndm2** [comment]
If there's no consensus about a complex solution that involves additional fields or even tables, how about we start slow, sign the token using the application salt, and go from there?

**Comment by RobertoRoos** [comment]
Sounds good. I'm putting together a PR.

**Comment by RobertoRoos** [comment]
PR is in progress, issue shouldn't be closed yet.

**Comment by RobertoRoos** [comment]
#467 got merged. With that I think this issue is solved?
