### ISSUE TITLE
AuthenticationComponent::setIdentity not update identity in CookieAuthenticator

### ISSUE THREAD

**Issue by mcsknp** [cakephp/authentication#446]
Data stored by `CookieAuthenticator` isn't updated after `AuthenticationComponent::setIdentity` called.

Run below code in controller
```
$this->Authentication->setIdentity($newInfo);
```
and re-open browser. User will be logged out.

**Comment by markstory** [comment]
That's on purpose though. The identity cookie is only refreshed when the current request URL matches a 'login' URL.
