### ISSUE TITLE
AuthenticationService::getLoginRedirect() and absolute URL

### ISSUE THREAD

**Issue by hiryu85** [cakephp/authentication#450]
Hello,
This is not a bug, its a small feature request.

I noticed that AuthenticationService does not allow you to use absolute URLs to set through queryParam the link where to redirect the user once logged in.
Reading the code (correct me if I'm wrong) if you set an absolute url this value is ignored. See https://github.com/cakephp/authentication/blob/e4c17b4ad3005a9c14a1c76e772e5d2006864d2f/src/AuthenticationService.php#L416

For security reasons it makes sense to disable remote urls, but it would be great to disable via AuthenticationService :: setConfig to set whether these absolute links are allowed or not or maybe do a custom validation via a callback.

**Comment by markstory** [comment]
> For security reasons it makes sense to disable remote urls, but it would be great to disable via AuthenticationService :: setConfig to set whether these absolute links are allowed or not or maybe do a custom validation via a callback.

Why? allowing absolute redirects in query string parameters makes applications vulnerable to open-redirect flaws.

**Comment by hiryu85** [comment]
I have three applications, one for backend, the other for frontend, and the other for reporting.
The login session is shared between the three apps, and based on where the authentication comes from (via queryParam) I have to redirect to the app that generated the login request.

In reality through configuration you could make a callback to validate the URL domain I did not intend to enable it by default.
I still solved it via the authentication controller which does a manual redirect

**Comment by karmicdice** [comment]
Referral can be forged?
How are we talking security when our redirect depends on a queryParam? *blows my mind!

Maybe do a `session::create` on redirect?
