### ISSUE TITLE
Introduce french translation

### ISSUE THREAD

**Issue by zachee54** [cakephp/authentication#453]
Hello,

While the Cookbook is entirely available in french, Authentication plugin is only available in english and japanese.
Shall I introduce the french translation ?
Please indicate whether it would be appropriate (might someone else be already working on it ?), and whether I should begin upon any basis made by some maintainer (like folders creation, etc), or simply copy/translate rst files in "fr" directory and push them up.
I use git frequently, but I'm still quite a beginner with Github so I may have missed the good way for this request. Apologize, in this case.

**Comment by markstory** [comment]
> Please indicate whether it would be appropriate (might someone else be already working on it ?), and whether I should begin upon any basis made by some maintainer (like folders creation, etc), or simply copy/translate rst files in "fr" directory and push them up.

No one has started the french translation. You can clone the english files into an `fr` directory to get started.

**Comment by othercorey** [comment]
If you are introducing a new language, it needs to be a complete translation before we consider it.

**Comment by zachee54** [comment]
Got it.
I start the translation. It should be quick.
