### ISSUE TITLE
Authentication:2.0 can't parse session identity (generated from authentication:1.0)

### ISSUE THREAD

**Issue by hiryu85** [cakephp/authentication#454]
Hello,
I don't know if it's a bug so I'm sorry if I opened an issue.
I have three cakephp applications that manage different parts of the same project and share the same domain.
All three use the authentication plugin and are configured to use the AuthenticatorService Session, with the necessary configuration to be able to set the cookie domain to be "mydomain.com".
So I have a unique session between login.mydomain.com, user.mydomain.com, admin.mydomain.com.

I noticed that by logging into login.mydomain.com I can access login protected parts of admin.mydomain.com, but if I go to user.mydomain.com (cake: 4 && authentication: 2.0) despite the cookie having the same session_id I see that the identity is empty.
The identity has _fields empty but _properties does not. 

# Login from login.mydomain

![clinita__login_session_ok](https://user-images.githubusercontent.com/406275/117583358-09121700-b107-11eb-993a-402d02e371f2.png)

# Shared session but identity's attributes is empty

![clinita__login_session_ko](https://user-images.githubusercontent.com/406275/117583351-044d6300-b107-11eb-824d-267bd1e5a7c5.png)

**Is it possible that in the case of authentication: 1 you use _properties while for authentication: 2 you use _fields to set the entity?**

**Comment by markstory** [comment]
> Is it possible that in the case of authentication: 1 you use _properties while for authentication: 2 you use _fields to set the entity?

This is entirely possible as the ORM stores data in different places between the two versions. However, that storage should be internal. If you have session authenticators setup to reload the user from the database on each request you might be able to get around this problem as only the user's id will be stored in the session data.

**Comment by hiryu85** [comment]
> This is entirely possible as the ORM stores data in different places between the two versions. However, that storage should be internal. If you have session authenticators setup to reload the user from the database on each request you might be able to get around this problem as only the user's id will be stored in the session data.

Thank your Mark. 
From what I understand I should configure the AuthenticationService of the Session with the option "identity => true".
However, I did not understand how to configure the identifier: should I set the identifier.password resolver or use identifier.callback?

`php
       // app/src/Application.php
        $service->loadAuthenticator('Authentication.Session', [
            'identify' => true,
        ]);
        $service->loadIdentifier('Authentication.Callback', [
            'callback' => function($data) {
                $this->Users = \Cake\ORM\FactoryLocator::get('Table')->get('Users');
                $user = $this->Users->findByUsername($data);
                if ($user) {
                    return $user->toArray();
                }

                return null;
            }
        ]);
`

Could you be so kind to tell me which way to go? Thanks again

**Comment by hiryu85** [comment]
Ok, i have founded the way. Maybe this way is not elegant, but works.

```php
    // app/src/Model/Entity/User.php
    // This method read old entity fields (named _properties in cake 3)
    public function getProperties()
    {
        $array  = (array) $this;
        $prefix = chr(0).'*'.chr(0);
        return $array[$prefix . '_properties'];
    }
```

```php
       // src/Application.php
        $service = new AuthenticationService();
        // .... any setup

        $service->loadAuthenticator('Authentication.Session', [
            'identify' => true,
        ]);
        $service->loadIdentifier('Authentication.Callback', [
            'callback' => function($data) {
                $data = $_SESSION ?? $data;
                $entity = $_SESSION['Auth'];

                if ($entity) {
                    $properties = $entity->getProperties(); // it's a custom \App\Model\Entiy\User method
                    if (isset($properties['id'])) {
                        foreach ($properties as $key => $value) {
                            $entity->set($key, $value);
                        }
                        return $entity;
                    }
                }

                return null;

                // Optional: fallback with database
                $this->Users = \Cake\Datasource\FactoryLocator::get('Table')->get('Users');
                $user = $this->Users->findByUsername($data['username'])->first();

                // Return an array of the identified user or null for failure.
                if ($user) {
                    return $user;
                }

                return null;
            }
        ]);
```
