### ISSUE TITLE
Can I use JWT and Form/Session Authentication in same app?

### ISSUE THREAD

**Issue by Josecanalla** [cakephp/authentication#462]
I have the following code

```
//In Application.php
public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
{
    $service = new AuthenticationService();

    // Define where users should be redirected to when they are not authenticated
    $service->setConfig([
        'unauthenticatedRedirect' => Router::url([
            'prefix' => false,
            'plugin' => null,
            'controller' => 'Users',
            'action' => 'login',
        ]),
        'queryParam' => 'redirect',
    ]);

    $fields = [
        IdentifierInterface::CREDENTIAL_USERNAME => 'nombre_usuario',
        IdentifierInterface::CREDENTIAL_PASSWORD => 'pass'
    ];
    
    // Load the authenticators.
    
    $service->loadAuthenticator('Authentication.Jwt', [
        'secretKey' => Security::getSalt(),
        'returnPayload' => false,
    ]);

    $service->loadAuthenticator('Authentication.Session');
    $service->loadAuthenticator('Authentication.Form', [
        'fields' => $fields
    ]);

    // Load identifiers
    $service->loadIdentifier('Authentication.JwtSubject');
    $service->loadIdentifier('Authentication.Password', [
        'returnPayload' => false,
        'fields' => $fields,
    ]);

    return $service;
}
```

```
//In routes.php
$routes->scope('/', function (RouteBuilder $builder) {
    $builder->applyMiddleware('csrf');
    $builder->connect('/', ['controller' => 'RecReclamos', 'action' => 'index']);
    $builder->connect('/pages/*', 'Pages::display');   
    $builder->fallbacks();
});

$routes->prefix('Api', function (RouteBuilder $builder) {
    $builder->setExtensions(['json']);
    $builder->fallbacks();
});
```

```
//In /Api/UsersController.php
public function login()
{
    $this->Authorization->skipAuthorization();
    $result = $this->Authentication->getResult();

    if ($result->isValid()) {
        $privateKey = Security::getSalt();
        $user = $result->getData();
        $payload = [
            'sub' => $user->id,
            'exp' => time() + 60,
        ];
        $json = [
            'token' => JWT::encode($payload, $privateKey),
        ];
    } else {
        $this->response = $this->response->withStatus(401);
        $json = [];
    }
    $this->set(compact('json'));
    $this->viewBuilder()->setOption('serialize', 'json');
}
```

```
//In UsersController.php
public function login()
{
    $this->Authorization->skipAuthorization();
    $result = $this->Authentication->getResult();
    
    // If the user is logged in send them away.
    if ($result->isValid()) {
        $target = $this->Authentication->getLoginRedirect() ?? '/';
        return $this->redirect($target);
    }
    if ($this->request->is('post') && !$result->isValid()) {
        $this->Flash->error('Credenciales incorrectas');
    }
}
```

And the behavior is:

1. I can login using the basic HTML form in /users/login
2. If I do a HTTP_POST to /api/users/login.json with this json body
`{
"nombre_usuario": "username",
"pass": "passwordOk"
}`
I get an Authenticator error: "FAILURE_CREDENTIALS_MISSING".
3. If I do a HTTP_POST to /api/users/login.json sending "nombre_usuario" and "pass" as x-www-form-urlencoded I get the user logged OK and get JWT token. 
4. After that, if I do a new HTTP_POST to /api/users/login.json sending "nombre_usuario" and "pass" as x-www-form-urlencoded but **with incorrect credentials** I also get a new JWT token. 

Is that the normal behavior?

**Comment by markstory** [comment]
> If I do a HTTP_POST to /api/users/login.json with this json body

You would also need the body decoding middleware active so that request data is populated from the JSON body.

> After that, if I do a new HTTP_POST to /api/users/login.json sending "nombre_usuario" and "pass" as x-www-form-urlencoded but with incorrect credentials I also get a new JWT token.

You also have the session authenticator active. If this request includes cookies you're likely being authenticated via cookies.

**Comment by Josecanalla** [comment]
> > If I do a HTTP_POST to /api/users/login.json with this json body
> 
> You would also need the body decoding middleware active so that request data is populated from the JSON body.
> 
Yes, I was loading the `BodyParserMiddleware` after the `AuthenticationMiddleware`. So now I am loading the `BodyParserMiddleware` before and it works.
> > After that, if I do a new HTTP_POST to /api/users/login.json sending "nombre_usuario" and "pass" as x-www-form-urlencoded but with incorrect credentials I also get a new JWT token.
> 
> You also have the session authenticator active. If this request includes cookies you're likely being authenticated via cookies.
Yes, I understand. But I need the SessionAuthenticator because my app has a website with normal HTML authentication. So how can I have Session and JWT authenticators active at same time, using one for the api part of the app and the other for the website part?

Thanks.

**Comment by markstory** [comment]
> Yes, I understand. But I need the SessionAuthenticator because my app has a website with normal HTML authentication. So how can I have Session and JWT authenticators active at same time, using one for the api part of the app and the other for the website part

In your application's `getAuthenticationService()` method you can look at the request and return include the appropriate authenticators and identifiers. Something like

```php
public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
{
    $service = new AuthenticationService();

    // Define where users should be redirected to when they are not authenticated
    $service->setConfig([
        'unauthenticatedRedirect' => Router::url([
            'prefix' => false,
            'plugin' => null,
            'controller' => 'Users',
            'action' => 'login',
        ]),
        'queryParam' => 'redirect',
    ]);
    if ($request->getParam('prefix') == 'api') {
        // Include API specific authenticators
    } else {
        // Web UI specific authenticators.
    }

    return $service;
}
```

If your application isn't using prefixes you could use other request attributes like the presence of a header or path segment being present in the request URL.

**Comment by markstory** [comment]
If you were to look for this in the docs where would you expect to find it?

**Comment by markstory** [comment]
If you were to look for this in the docs where would you expect to find it?

**Comment by Josecanalla** [comment]
> If you were to look for this in the docs where would you expect to find it?

I would put a note that the BodyParserMiddleware needs to be loaded before the AuthenticationMiddleware if you use JSON requests. I would put that note in "Authenticators -> JWT" section.

And also I would put a new section, inside "Authenticators" explaining the situation when the app has website and JWT authentication at same time, explaining with example how you can define what Authenticator to use in function of the request, like your last post.
