### ISSUE TITLE
Ability to remove fields from getIdentity()

### ISSUE THREAD

**Issue by karmicdice** [cakephp/authentication#465]
This is a feature-request. Unless, it already exists that I couldn't find in the docs.

Our code was security-audited and the report had a low impact notice.

After `$result->isValid()`
we did:
```
$currentSession = $this->Authentication->getIdentity();
pr($currentSession);
```
The log suggested this is in-memory:

```
Authentication\Identity Object
(
    [config] => Array
        (
            [fieldMap] => Array
                (
                    [id] => id
                )

        )

    [data] => App\Model\Entity\User Object
        (
            [id] => 1
            [email] => test@example.com
            [password] => $2y$10$lJmWmCJuneg9O3AD2KsfI.qER7UQEBJn1ihnHA4pyKdUmX3TrCFUO
            [activeToken] => 83s6f9e1d6a8d1f85d2f4d9a3as1c8
            [token] => 56asd546a8s5d484fd156dsf98f56ew12
            [[new]] => 
            [[accessible]] => Array
                (
                    [username] => 1
                    [profiles] => 1
                )

            [[dirty]] => Array
                (
                )

            [[original]] => Array
                (
                )

            [[virtual]] => Array
                (
                )

            [[hasErrors]] => 
            [[errors]] => Array
                (
                )

            [[invalid]] => Array
                (
                )

            [[repository]] => Users
        )

)
```

In User.php I have:

```
protected $_hidden = [
    'password',
    'activeToken',
    'token'
];
```

As per ToS low impact notices are not a deal-breaker but that gave me a thought...

If we had an ability to tell `getIdentity()` or `setIdentity()` (if it exists) to NOT store certain fields in session memory.

If you guys think this can benefit our community, I would like to work on it and send a PR.

What say?

**Comment by ADmad** [comment]
Use a custom `finder` to only fetch the fields that you need. https://book.cakephp.org/authentication/2/en/identifiers.html#orm-resolver

**Comment by othercorey** [comment]
The fields selected are stored in the session. You can't filter the identity that's stored.
