### ISSUE TITLE
Remove usage of Cake\Network\Exception\UnauthorizedException

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#47]
Using `Cake\Network\Exception\UnauthorizedException` means we would have to add `cakephp/cakephp` as dependency which is undesirable. To avoid that the plugin should have it's own `UnauthorizedException`.

**Comment by burzum** [comment]
@ADmad should this exception do something special or do we want to set some data to it? Or just extend \Exception and we're OK?

**Comment by ADmad** [comment]
@burzum Check @markstory's comments on #48.

**Comment by markstory** [comment]
Closing as #50 is open.
