### ISSUE TITLE
Handling Audience claim in JWT tokens

### ISSUE THREAD

**Issue by gbdeboer** [cakephp/authentication#470]
According to [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3):
"The "aud" (audience) claim identifies the recipients that the JWT is intended for.  Each principal intended to process the JWT MUST identify itself with a value in the audience claim. **If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected.** [...]".

As far as I could tell, the authentication plugin disregards the value of the "aud" claim altogether. Shouldn't the plugin be configurable as to which audience should be accepted? What would be the best way to limit the accepted values for the "aud" claim?

**Comment by markstory** [comment]
> As far as I could tell, the authentication plugin disregards the value of the "aud" claim altogether. Shouldn't the plugin be configurable as to which audience should be accepted?

Could this be an option for the JWT authenticator? An allow list of `aud` values that must be present might be a simple way to add this condition for applications that need/want it.

**Comment by gbdeboer** [comment]
> Could this be an option for the JWT authenticator? An allow list of `aud` values that must be present might be a simple way to add this condition for applications that need/want it.

That seems like a good solution to me. As far as I could tell the 'aud' claim is also the only registered claim name for which the specification describes that it MUST be rejected if not matching, that wasn't yet handled by the plugin already ('exp' and 'nbf' also must be rejected if invalid, but this is already handled by the plugin).

Then there is also the 'iss' (issuer) claim. It seems reasonable that you'd want to be able to limit the issuers that your application should accept tokens from. I can image that there is an argument to be made to make this a configurable parameter for the plugin as well. However, the specification doesn't state that a JWT should be rejected if the issuer isn't known by the processing application. So one could also argue that limiting the issuers should be handled by the authorization plugin rather than the authentication plugin. 

Ergo: should the 'iss' claim be configurable too besides the 'aud' claim, or should it be left to authorization?

**Comment by markstory** [comment]
> Ergo: should the 'iss' claim be configurable too besides the 'aud' claim, or should it be left to authorization?

We've been keeping the authenticator out of the business of generating JWTs and I'd prefer to keep it that way. I can see the argument for being able to constrain the `iss` claim alongside the `aud` claim as well. I'm unsure how much value these additional contraints provide if you're also signing JWTs though. I understand that it is 'in the spec' but the spec also encompasses unsigned tokens which should never be used in my opinion.

**Comment by gbdeboer** [comment]
> We've been keeping the authenticator out of the business of generating JWTs and I'd prefer to keep it that way.
Agreed.

> I'm unsure how much value these additional contraints provide if you're also signing JWTs though.
In a microservice architecture being able to limit issuer and audience claims would help prevent valid tokens being reused against other services they aren't meant for. Of course you could prevent this by using a public/private key algorithm, but this would require setting up a public/private key infrastructure for each of these services.

**Comment by swiffer** [comment]
> > As far as I could tell, the authentication plugin disregards the value of the "aud" claim altogether. Shouldn't the plugin be configurable as to which audience should be accepted?
> 
> Could this be an option for the JWT authenticator? An allow list of `aud` values that must be present might be a simple way to add this condition for applications that need/want it.

Is this something you would accept pull requests for (making audience a config option and rejecting non matching keys in case the option is set?)

**Comment by ADmad** [comment]
> Is this something you would accept pull requests for (making audience a config option and rejecting non matching keys in case the option is set?)

Yes
