### ISSUE TITLE
getLoginRedirect() always returns Null

### ISSUE THREAD

**Issue by general2000vn** [cakephp/authentication#471]
I am using CakePHP 4.2.8, Authentication plugin ver 2.6.1

I follow the documentation for Authentication 2x.

My Users::login() always redirect to alternative route.
I have set a variable of 
`$supposed = $this->Authentication->getLoginRedirect() ;` 
and disable redirection, just to see what is returned.

The result is getLoginRedirect() always returns Null, even I can see login url has redirect paramenter in browser url bar.

**Comment by markstory** [comment]
How could someone reproduce the problem you're having? We have a tests for [getLoginRedirect() showing it returning something other than null](https://github.com/cakephp/authentication/blob/master/tests/TestCase/Controller/Component/AuthenticationComponentTest.php#L341)
