### ISSUE TITLE
Software Quality see this as security blocker issue

### ISSUE THREAD

**Issue by braguzz** [cakephp/authentication#488]
https://github.com/cakephp/authentication/blob/e635880fb50813bfd43cfc66044fff8db79463ef/src/Identifier/IdentifierInterface.php#L23

Credentials should not be hard-coded

**Comment by dereuromark** [comment]
Isnt that the Key?

**Comment by ndm2** [comment]
It is a key (name) indeed.

**Comment by ADmad** [comment]
Just because something is named "password" doesn't mean it's a hard coded credential :slightly_smiling_face:.
