### ISSUE TITLE
public function identify($data)

### ISSUE THREAD

**Issue by dereuromark** [cakephp/authentication#49]
This method should not `@return false|EntityInterface` but instead `@return EntityInterface|null`.
It is a cleaner default value in general (despite the fact that this should be "bool", not "false", as false doesnt exist as type).
Also, this would be future compliant with 7.1+ "nullable" strictness, if we ever introduced that.

It is also more consistent with the rest of the framework or the direction it goes to, or where it should go to - either using a NullObject of some sorts or just returning null.
Using more than that as return type alternatives is usually a code smell - and a clear nogo even when returning objects.

**Comment by markstory** [comment]
Seems like a reasonable change to me

**Comment by dereuromark** [comment]
PR open.
