### ISSUE TITLE
problem authentication with username or email

### ISSUE THREAD

**Issue by arbims** [cakephp/authentication#493]
Hello everyone
# problem authentication with username or email

* I tried to add in the array an array ['username', 'email'] as we do with the auth component but it doesn't work.
```
$fields = [
            IdentifierInterface::CREDENTIAL_USERNAME => ['username', 'email'],
            IdentifierInterface::CREDENTIAL_PASSWORD => 'password'
        ];
```
* I also need to add a scope for active users

thanks for help

**Comment by othercorey** [comment]
Please discuss this in the slack channel, discord channel or on discourse:

https://cakephp.org/get-involved#getHelp
