### ISSUE TITLE
[doc] Testing with Authentication

### ISSUE THREAD

**Issue by Cyrille37** [cakephp/authentication#514]
Hello :-)

Is it possible to add reference to `Cake\TestSuite\IntegrationTestTrait`,and others if any, testing helper ? Or a link to a Testing documentation place ?

Thanks & cheers

**Comment by markstory** [comment]
Where would you be looking for those links?

**Comment by Cyrille37** [comment]
Sorry, I forgot links & explains :-)

I was in [Testing with Authentication](https://book.cakephp.org/authentication/2/en/testing.html) but there is no information about the mandatory context, like using IntegrationTestTrait.
Perhaps adding some words about needed context and a link to https://book.cakephp.org/4/en/development/testing.html

**Comment by Cyrille37** [comment]
Thanks :-)
