### ISSUE TITLE
Add debug log when using FormAuthentication without BodyParserMiddleware

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/authentication#521]
I expect to see a debug (or error log) if I am using `Authentication.Form` without adding `BodyParserMiddleware` before `AuthenticationMiddleware`. Currently, the only way the user would know why their authentication is broken is by this note here https://book.cakephp.org/authentication/2/en/authenticators.html#form

Is it possible to add something like this to https://github.com/cakephp/authentication/blob/2.x/src/Authenticator/FormAuthenticator.php?

I think providing something like this would be a better developer experience.

**Comment by markstory** [comment]
That sounds like a great idea to me. Using a warning level is probably where we want to land level wise.

**Comment by ADmad** [comment]
But the BodyParserMiddleware is only required if one is dealing with JSON/XML requests. There could be other mistakes devs might be doing which might case FormAuthenticate to not work as expected when dealing just HTML. We shouldn't be throwing errors when not actually applicable and confuse the devs more.

**Comment by markstory** [comment]
What if the warning didn't mention body parser at all? Instead it could be triggered when the request data was empty?

**Comment by ADmad** [comment]
I guess that could work.

**Comment by cnizzardini** [comment]
I looked at this a bit more. As @ADmad keyed in on, I am definitely using JSON requests. First, there was some additional user error.

1. If I have not loaded `BodyParserMiddleware` and my authenticators are loaded in this order:

```php
        $service->loadAuthenticator('Authentication.Form', [
            'fields' => [
                IdentifierInterface::CREDENTIAL_USERNAME => 'email',
                IdentifierInterface::CREDENTIAL_PASSWORD => 'password',
            ],
            'loginUrl' => '/auth/login'
        ]);
        $service->loadAuthenticator('Authentication.Jwt', [
            'secretKey' => Security::hash(Security::getSalt(), 'sha256'),
            'algorithm' => 'HS256',
        ]);
```

I get the following error:

```
FAILURE_CREDENTIALS_INVALID
```

2. If I swap the order with AuthenticationForm occuring second I get a much better error:

```
Login credentials not found
```

I think for scenario 2, adding some additional debug info on missing body parser middleware would be nice. I am not sure how to create a better dev experience for the first one. It's very easy to misconfigure this IMO.

Edit: Maybe for the first scenario the ResultObject could include more information? It currently only includes the results from the last authenticator as far as I can tell:

```
Authentication\Authenticator\Result Object
(
    [_status:protected] => FAILURE_CREDENTIALS_INVALID
    [_data:protected] => 
    [_errors:protected] => Array
        (
        )

)
```

My code to parse this out and display user errors currently looks like this:

```php
        if (count($result->getErrors())) {
            throw new UnauthenticatedException(implode('. ', $result->getErrors()));
        }
        throw new UnauthenticatedException($result->getStatus());
```

For additional reference I have been cobbling together jwt auth demo for mixerapi if you want to see the pr branch its here: https://github.com/mixerapi/demo/tree/authentication/app/plugins/AuthenticationApi
