### ISSUE TITLE
`isLoggedIn()` in a Controller?

### ISSUE THREAD

**Issue by mehov** [cakephp/authentication#619]
In a view or a template I can call [`isLoggedIn()`](https://github.com/cakephp/authentication/blob/73cab9a3cd6938279925f3a2165d335b4ce356a5/src/View/Helper/IdentityHelper.php#L90):

```
$this->loadHelper('Authentication.Identity');
debug($this->Identity->isLoggedIn());
```

But how do I check whether a user is logged in inside a Controller?

I want to load different templates based on if a user is logged in.

**Comment by mehov** [comment]
The [code search](https://github.com/search?q=repo%3Acakephp%2Fauthentication%20isLoggedIn&type=code) is finding only the [src/View/Helper/IdentityHelper.php](https://github.com/cakephp/authentication/blob/73cab9a3cd6938279925f3a2165d335b4ce356a5/src/View/Helper/IdentityHelper.php#L90)

**Comment by markstory** [comment]
> But how do I check whether a user is logged in inside a Controller?

You can read the current identity from `$this->Authentication->getIdentity()`, if it isn't null, the user is logged in :smile:
