### ISSUE TITLE
Add authenticator for Oauth2

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#62]
This would take some effort but wanted to create the issue in case someone wants to take a crack at it.

**Comment by cleptric** [comment]
This is targeting to implement our own oauth 2 server, right?
Maybe we can work sth. out with https://oauth2.thephpleague.com

**Comment by ADmad** [comment]
Not server, client for authentication.

**Comment by ADmad** [comment]
Leveraging league's would definitely help though it would pull in guzzle :P

**Comment by cleptric** [comment]
Ok, this makes things easier then :)
I'll take a look.

**Comment by dereuromark** [comment]
Technically, it would be a suggest (or require dev), so people not using oauth2 (only jwt) wouldnt have to pull in guzzle then :)

**Comment by ADmad** [comment]
Yes it would be suggest.

**Comment by markstory** [comment]
Why would you need guzzle or another library to be an oauth2 client? Is there something more to it beyond setting the Authorization header correctly?

**Comment by burzum** [comment]
@ADmad *someone*? Sounds like you volunteered by opening this issue? 😃

**Comment by ADmad** [comment]
Nope,  I am just finishing, waiting for someone to bite the hook :)

**Comment by cleptric** [comment]
I dived into this a little bit. Not an easy topic, but quite interesting :)
Supporting all the different grant types would result in copying the generic provider of league's oauth2 client, minus guzzle.
Would be a `JWT Bearer` grant supporting authenticator enough or do we want more?

**Comment by burzum** [comment]
@cleptric we use a vendor for JWT as well, I don't see a reason why we can't do it here as well if the leagues lib works fine for what we want to do? Just add it to the suggest section of composer.json and get the authenticator to work. :)

**Comment by ADmad** [comment]
I don't mind using league's oauth2 client either. It would be a "suggest" and not a hard dependency so the fact that it pulls in guzzle is not a problem.  Maybe I'll add a new authenticator to my hybridauth plugin for those who want to avoid guzzle :)

**Comment by ADmad** [comment]
@cleptric Interested in checking out another lib? :smile:

I found a new lib https://github.com/SocialConnect/auth which seems decent. It has proper interfaces which  allow using custom adapter for handling requests and session, thereby avoiding any external dependencies like guzzle.

**Comment by burzum** [comment]
@ADmad why do all these providers require different implementations? That's how it looks like at least to me. I thought Oauth was thought to be some kind of standard so that you *don't* have the fun of dealing with different implementations.

**Comment by josegonzalez** [comment]
@burzum there are different revisions of the spec, and people sometimes use different args for sending requests downstream.

**Comment by cleptric** [comment]
@ADmad Looks good to me. Prototype is up and running. Will continue tomorrow 😀

**Comment by burzum** [comment]
@cleptric can we get an update on that? :) I've refactored the code a little and added a stub for the test case. It's years since I've worked with Oauth the last time, so I'm a little rusty on that topic. Can you create a list of things that need to be done to complete this? I don't mind working on it when I know what needs to be done to finish it.

**Comment by cleptric** [comment]
@burzum 
- We should add a check for the provider. So you can have different buttons on the login page for different providers (e.g. Twitter, Facebook, Google, ...) that pass the provider as a query parameter.
- We have to handle the redirect and access token request independently. Only redirect to the provider if the request comes form the login page and contains the prover. After that, we have to get the access token and the user identity.
- Maybe we need a virtual redirect endpoint as we don't have a route for that in place

I already have some code for that in place, but it needs some refinement. I'll merge my changes and push the code later today.

**Comment by cleptric** [comment]
PR is open
