### ISSUE TITLE
v3 docs need to be built/deployed

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#636]
https://book.cakephp.org/authentication/3/ is currently 404.

Same needs to be done for all other plugins.

**Comment by markstory** [comment]
I can take care of this in the upcoming week.

**Comment by ADmad** [comment]
I mistakenly directly pushed this new config file to `3.x` branch instead of making a PR https://github.com/cakephp/authentication/commit/fba8741e78311b3c09eaec6c28e17758dda8f150.

I assume there are still additional steps need to make the v3 docs accessible like nginx config changes somewhere.

**Comment by markstory** [comment]
Closing as these docs are up now.
