### ISSUE TITLE
Reduce constraint for psr/http-message

### ISSUE THREAD

**Issue by swiffer** [cakephp/authentication#643]
Similar to what has been done here: https://github.com/cakephp/cakephp/pull/17360

Can we reduce this to widen compatibility with other packages?

**Comment by dereuromark** [comment]
Make a PR and see what happens :)

**Comment by swiffer** [comment]
@dereuromark, done - but the GitHub Actions Workflow will not install psr/http-message ^1.0 until CakePHP 5.0.2? is released and we are setting this as lower bound for cakephp/authentication i guess.

**Comment by swiffer** [comment]
@dereuromark can you tag 3.0.3 (since CakePHP 5.0.2 is out now)

**Comment by swiffer** [comment]
Sorry for asking again - could we have a 3.0.3 release tagged or is something pending @dereuromark ?

**Comment by dereuromark** [comment]
I usually dont release them
@markstory did afaik
