### ISSUE TITLE
Use Authentication into Cell

### ISSUE THREAD

**Issue by JessyLELIEVRE** [cakephp/authentication#666]
Hello, 

I'm contacting you to let you know that I'd like to be able to use and browse authentication information in the "component" way in Cells.

Do you have a temporary idea for how to do this? *

Thank you,

**Comment by markstory** [comment]
> I'm contacting you to let you know that I'd like to be able to use and browse authentication information in the "component" way in Cells.

You can access the authentication service via the request attribute `request->getAttribute('authentication')` and the current identity is available on `request->getAttribute('identity')`. 

I'm interested in what kind of scenarios you need the component to be available in a cell for.

**Comment by JessyLELIEVRE** [comment]
Hello,

I'd like to use the identity component to retrieve user information from a cell.

My user has a side navigation bar. It contains information such as username, e-mail address and number of credits (virtual currencies). When my player makes a purchase, I take care to update the player session, as I don't want to perform a SQL query simply and solely to retrieve the information (except during the purchase for security checks).

That's why I want to be able to use the identity component from a cell.

Thank you in advance,

**Comment by markstory** [comment]
Could you use the [IdentityHelper](https://github.com/cakephp/authentication/blob/3.x/src/View/Helper/IdentityHelper.php) for that?

**Comment by JessyLELIEVRE** [comment]
> Could you use the [IdentityHelper](https://github.com/cakephp/authentication/blob/3.x/src/View/Helper/IdentityHelper.php) for that?

Hello,

Yep. I can. But that doesn't resolve my use case. 

A simple example of the use case I'd like:

`public function userCard(string $userAvatar = null) {
    $user = $this->fetchTable('Users')->get([...], select: ['Users.id','Users.username','Users.credits']);
    $this->set(compact('user', 'userAvatar'));
}`

Thank you in advance,

**Comment by ADmad** [comment]
@JessyLELIEVRE As already stated by markstory in his initial comment you can get the user identity from the request instance `$this->request->getAttribute('identity')`.

**Comment by JessyLELIEVRE** [comment]
> @JessyLELIEVRE As already stated by markstory in his initial comment you can get the user identity from the request instance `$this->request->getAttribute('identity')`.

Hello, 

All right, I'll do it this way.

Thank you so much,
