### ISSUE TITLE
How to migrate deny()

### ISSUE THREAD

**Issue by davidyell** [cakephp/authentication#69]
How do I migrate my `deny()` calls to this new system?

**Comment by ADmad** [comment]
`deny()` is authorization, this plugin only does authentication no authorization.

**Comment by davidyell** [comment]
So it's not a replacement for the Auth component? That's a shame.

**Comment by dereuromark** [comment]
@ADmad Are you sure? deny() is just the pendant to allow() afaik. Whitelist vs blacklist. Both are authentication (or skipping of it).
For me authorization comes into play once you are fully authenticated.

**Comment by davidyell** [comment]
Who cares who you are if you can access my whole application anyway? Do I just create my own `AccessDeniedException` then and throw that if `$request->getAttribute('authentication')->getResult()->isValid()` fails?

Nothing about this package makes any sense to my brain at all. I can't even follow the documentation properly.

**Comment by ADmad** [comment]
> So it's not a replacement for the Auth component? That's a shame.

It's not a drop in replacement at least. 

> Not sure it'll gain much adoption with such a key component missing.

Only time will tell :)  I personally don't consider the allow() / deny() methods of core auth component a key feature. It 

> Are you sure? deny() is just the pendant to allow() afaik. Whitelist vs blacklist. Both are authentication (or skipping of it = public = no authentication necessary).

allow() / deny() are used to decide whether an authentication user is allowed to access a resource, that's still a basic form of authorization.

> Nothing about this package makes any sense to my brain at all. 

That's probably cause you are still considering this as a 1:1 replacement for core AuthComponent instead of just understanding the features the plugin provides.

> I can't even follow the documentation properly.

This is still WIP. We are hoping community members such a yourself try out the plugin and help us with docs.

**Comment by burzum** [comment]
@davidyell *please* get away from the idea this being related to `authorization` at all. Let me quote what I wrote in my blog:

> One of the parts of the CakePHP framework I like the less is the authentication and authorization. There are a few reasons why. *For example the authentication and authorization. Firstly both authentication and authorization have been married through the AuthComponent, secondly the component is an ugly monolith that is coupled to the controller layer of the MVC pattern.*

Authorization and authentication should have never been coupled in this monlith called AuthComponent nor they should have been coupled tightly into the controller layer of the MVP pattern.

What you need to do is to pass your identity to whatever authorization system you use. Your identity is the `accessor` or `subject`, that thing that asking if it is allowed to do something. This can *anything*, in theory I could pass any data object that implements some interface I can rely on and my authorization implementation will accept it as accessor and check the permissions against a given object.

**Comment by dereuromark** [comment]
@davidyell 
I think there will always be some kind of Auth component available, glueing the different aspects of Auth together.
This split off is only just a small part of the future changes, but there will sure be something to still easily provide allow/deny functionality - based on the authorization mechanism used then.

**Comment by davidyell** [comment]
Thanks for all the feedback, that's made things much clearer. I'm already thinking about how I can setup an Authorization middleware layer in the application I'm testing this plugin with.

**Comment by burzum** [comment]
@dereuromark I don't think there will be always one component doing both things. :) Authentication already brings the new authentication component, which is just a tool to make accessing the authentication more easy and convenient.

The new authorization system won't be bound  to the controller layer either. It is more likely that you'll have to implement an interface and that you can use any object to authorize it. For example field level access to database rows would not happen in the controller at all.
