### ISSUE TITLE
AuthenticationComponent::logout

### ISSUE THREAD

**Issue by cleptric** [cakephp/authentication#77]
The `AuthenticationComponent::logout()` currently transforms the request and response into an array, which will break afterwards, if you call `$this->redirect()` in a controller.

**Comment by burzum** [comment]
Closing this because we have a PR open for it.

**Comment by burzum** [comment]
No? How does it break? AuthenticationComponent::logout() returns `void|string|array`. Could you please add a test case that demonstrates the issue?

```php
    public function logout()
    {
        $controller = $this->_registry->getController();
        $result = $this->_authentication->clearIdentity(
            $controller->request,
            $controller->response
        );

        $controller->request = $result['request'];
        $controller->response = $result['response'];

        $logoutRedirect = $this->getConfig('logoutRedirect');
        if ($logoutRedirect !== false) {
            return Router::normalize($logoutRedirect);
        }
    }
```

**Comment by cleptric** [comment]
The Problem is the return value of `SessionAuthenticator::clearIdentity()`.
It returns an array with the keys `request` and `response`.
Inside `AuthenticationService:.clearIdentity()`, the whole return value is set as the response, not just the response object inside the return value.

**Comment by cleptric** [comment]
PR is open.
