### ISSUE TITLE
Authentication Service is overriding original error

### ISSUE THREAD

**Issue by chrisShick** [cakephp/authentication#81]
Correct me if I am wrong, but I was looking into why my authentication error code was not being returned correctly and I noticed that in the AuthenticationService class the result is being overridden before being returned. 

     public function authenticate(ServerRequestInterface $request, ResponseInterface $response)
    {
        $this->loadAuthenticators();

        foreach ($this->_authenticators as $authenticator) {
            $result = $authenticator->authenticate($request, $response);
            if ($result->isValid()) {
                if ($authenticator instanceof PersistenceInterface) {
                    $authenticator->persistIdentity(
                        $request,
                        $response,
                        $result->getIdentity()
                    );
                }

                $this->_successfulAuthenticator = $authenticator;

                return $this->_result = $result;
            }
            if (!$result->isValid() && $authenticator instanceof StatelessInterface) {
                $authenticator->unauthorizedChallenge($request);
            }
        }

        $this->_successfulAuthenticator = null;
        $this->_result = $result;

        return $this->_result = new Result(null, Result::FAILURE_IDENTITY_NOT_FOUND);
    }

Was this left over debugging? If not, then what is the purpose of the line above it to set the result?

**Comment by burzum** [comment]
Do you refer to this line? 

```php
    $this->_result = $result;

    return $this->_result = new Result(null, Result::FAILURE_IDENTITY_NOT_FOUND);
```

You're right but I'm not sure how to resolve this now the best. I thin ```$this->_result = $result;``` should be correct as the idea was to return the last result.

**Comment by cleptric** [comment]
PR is open

**Comment by burzum** [comment]
@chrisShick this has been fixed and merged to master. Please let me know if there is still something wrong with it. Thank you.

**Comment by chrisShick** [comment]
@burzum Ahh, I thought perhaps this would help me solve the issue of keeping all the authentication logic including errors within the Authenticator, but it seems like I have to do the check in the controller regardless, right?

**Comment by burzum** [comment]
@chrisShick you can do whatever you want with the authentication objects where ever they're available. No idea what you want to do. The plugin includes an authentication component for the controller layer. All it does can be done in the middleware as well for example.
