### ISSUE TITLE
Add a LDAP identifier?

### ISSUE THREAD

**Issue by burzum** [cakephp/authentication#86]
It would a *very* easy to turn [this plugin](https://github.com/QueenCityCodeFactory/LDAP) into an identifier. Let's do it?

I just don't have a LDAP server I could test against it. I have no idea how to test the function calls either. A possibility would be a small OOP wrapper around the modules functions and mock the whole LDAP connection object.

**Comment by ADmad** [comment]
I too don't uave any experience with LDAP. Having adapter for it would be surely nice.

**Comment by burzum** [comment]
I'll ask the author of the plugin if he would like to contribute to this project. :)

**Comment by burzum** [comment]
I've slightly updated my old code I've started 1-2 month ago and pushed it to https://github.com/cakephp/authentication/tree/ldap-identifier

@ceeram and @cleptric use LDAP at work and said they can review and complete the work on this. Thanks guys. 👍

**Comment by cleptric** [comment]
I was able login against a LDAP Server: http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/
That said, I'm not happy at all with the current implementation.
The handling of the ldap result is pretty fragile. The config array is also getting pretty big.
We should also add a new `OrmTrait`, which can handle the db lookup for the `TokenIdentifier` and the `LdapIdentifier`.

**Comment by cleptric** [comment]
Hmm, on a second thought, I'm not quite sure if we want to lookup anything in the db while using the `LdapIdentifier`. I have to adjust the return of the identify method and create an entity on the fly, then.

**Comment by burzum** [comment]
@cleptric as I understand LDAP it should provide all the info for the user already. You log in using LDAP, done. Sure you could link it with an account inside your local application but that is out of scope of the identifier - IMO. If somebody wants to do that he can link the accounts after login / registration or extend the identifier.

Also I've seen you're overriding $_defaultConfig. Please note that we're not using the MergeVarTrait that would merge the arrays of defined properties. So you're completely overriding the defaults.

**Comment by cleptric** [comment]
@burzum LDAP doesn't provide you with any user data, if you're not searching for it. A ldap_bind is basically all is needed to authenticate a user against a LDAP server (I learned that yesterday 😉). If the bind is successful, you get `true` else `false`. So I dropped all the search code and the result juggling.
You're right about that an ORM lookup isn't necessary. _If_ the `LdapIdentifier` would do an ORM lookup, I just don't wanted to copy the code from the `TokenIdentifier`. This was the idea behind adding a trait.

**Comment by burzum** [comment]
@cleptric it can contain data. See https://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol#Directory_structure I think this case should be handled as well besides the ORM lookup.

We need to find a way to make the ORM lookup somehow optional and work with other ORMs as well. We've tried to keep this lib so far as open as possible to other implementations. I'm open for ideas on how to make this possible.

**Comment by cleptric** [comment]
@burzum Sorry, I was pointing to php `ldap_bind()` only returns bool, not LDAP in general 😄

**Comment by Theaxiom** [comment]
That LDAP plugin, while it works, is definitely missing quite a lot. It doesn't even have the option of creating associated user rows upon successful login, etc. If I get the time, I would like to bring this into an identifier: https://github.com/ldaptools/ldaptools

**Comment by burzum** [comment]
@Theaxiom it's not the duty of the identifier to create any records, this is totally out of the scope of this lib. Read this https://en.wikipedia.org/wiki/Separation_of_concerns to get an idea why. Also we intentionally did not include yet another dependency, we just want to get the user and the code we have does this well without adding a whole vendor lib.

However, if you want to create a whole LDAP plugin around that lib we would appreciate that. :)

**Comment by Theaxiom** [comment]
@burzum I understand what you are saying, and yes I do intend to create an LDAP plugin around that lib when and if I get the time. Right now I am using QueenCityCodeFactory, however it does raise some concerns but works in the meantime. :)

**Comment by cleptric** [comment]
PR is open. Sorry for the delay 😔
