### ISSUE TITLE
Documentation Gaps

### ISSUE THREAD

**Issue by HaroldPutman** [cakephp/authentication#88]
For users migrating from AuthComponent there are some big questions that are not answered by the documentation:

1. How do you log in?
2. How do restrict access to actions in a controller (like you do with  `$this->Auth->allow()`)?
3. How do you redirect to the login page when users are not logged in?

It would be helpful to have a version of the [Authentication and Authorization Blog Tutorial](https://book.cakephp.org/3.0/en/tutorials-and-examples/blog-auth-example/auth.html) using this  middleware instead of AuthComponent.

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/authentication/issues/69

**Comment by cleptric** [comment]
@HaroldPutman This `plugin`only handles `authentication`, not `authorization`.

If you want to build a basic login page, refer to the `AuthenticationComponent`. You have different options for that, depending which Authenticator you want to use.

**Comment by markstory** [comment]
@cleptric I think @HaroldPutman is looking for an example of the more common authenticators :smile:

**Comment by ADmad** [comment]
We need a tutorial app :)

**Comment by burzum** [comment]
Can we close this ticket? 2) Should be pretty clear now right on the readme.md 1) and 3) should be covered in the docs and / or a separate tutorial should be created.

**Comment by ADmad** [comment]
I would keep the ticket open until someone gets around to writing the tutorial.

**Comment by burzum** [comment]
Let's create a more specific ticket then with the exact requirements of what needs to be done and just link this here.

**Comment by HaroldPutman** [comment]
I'm cool with closing this issue. The recently added notes in the documentation help answer my original question.

**Comment by robertpustulka** [comment]
Hold on... I think `Auth->allow()` is not for authorization but for disabling authentication for controllers or actions. I'm afraid currently **all** requests must be authenticated. Is there a way to make an action "public"?

**Comment by burzum** [comment]
All actions are public and stay public, authentication has nothing to do with that. It just gives you an identity if an user is logged in. You can implement a check based on that in isAuthorized() for example using the still existing and useable old authorization system.
