### ISSUE TITLE
Using both Orm and Token identifiers

### ISSUE THREAD

**Issue by davidyell** [cakephp/authentication#95]
## What am I doing?
I'd like to use different Authentication for my CMS than my API. Previously I'd configure different AuthComponent setups in my `AppController`, `v3/ApiAppController` and `v4/ApiAppController`.

## What did I do?
```php
$service = new AuthenticationService();
$service->loadIdentifier('Authentication.Orm', [
    'fields' => [
        'username' => 'email',
        'password' => 'password'
    ],
    'userModel' => 'Users',
    'finder' => 'auth',
]);
$service->loadIdentifier('Authentication.Token', [
    'tokenField' => 'keycode',
//  'dataField' => '_token', // I'm not actually sure what this is supposed to be
    'userModel' => 'ApiUsers',
    'finder' => 'all',
    'tokenVerification' => 'Orm'
]);

$service->loadAuthenticator('Authentication.Session', [
    'sessionKey' => 'user'
]);
$service->loadAuthenticator('Authentication.Form', [
    'fields' => [
        'username' => 'email',
        'password' => 'password'
    ]
]);
$service->loadAuthenticator('Authentication.Token', [
    'header' => 'X-ApiToken',
    'queryParam' => '_token',
    'tokenPrefix' => null,
]);

$authentication = new AuthenticationMiddleware($service);
$middleware->add($authentication);
```

## What happened?
```
Database Error, PDOException
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Users.keycode' in 'where clause'
```

## What's going on?
I think that perhaps because I've specified `Orm` as the `tokenVerification` it's using the settings from the Orm identifier, and looking for the `ApiUsers.keycode` in the `Users` table.

**Comment by davidyell** [comment]
Also worth noting that when I tried to use a custom finder here instead of `all` I got an error for unknown finder. Let me know if that's worth me opening another issue.

**Comment by ADmad** [comment]
The problem is `TokenIdentifier` using key `model` instead of `userModel`. I'll fix that.

**Comment by davidyell** [comment]
Thanks @ADmad
