### ISSUE TITLE
Config key 'identify' not set in SessionAuthenticator

### ISSUE THREAD

**Issue by littleylv** [cakephp/authentication#97]
[https://github.com/cakephp/authentication/blob/master/src/Authenticator/SessionAuthenticator.php#L58](https://github.com/cakephp/authentication/blob/master/src/Authenticator/SessionAuthenticator.php#L58)
Key 'identify' is not set in $_defaultConfig.
Also, in docs [https://github.com/cakephp/authentication/blob/master/docs/Authenticators.md#session](https://github.com/cakephp/authentication/blob/master/docs/Authenticators.md#session)

**Comment by markstory** [comment]
What problems dies this omission create?

**Comment by burzum** [comment]
There is no need to set it. If it's not present the check in L58 will simply not return true and the session is not checked against the DB record.

**Comment by littleylv** [comment]
It won't cause any problems if it's not set.
But shouldn't we set it a default value?
At least mention it in the docs so developers will know SessionAuthenticator has a key 'identify'

**Comment by burzum** [comment]
@littleylv is that OK?

> * **identify**: Set this key with a value of bool `true` to enable checking the session credentials against the identifiers.

**Comment by ADmad** [comment]
It would still be nice to initialize the key in default config for those who prefer reading code rather than docs :)

**Comment by littleylv** [comment]
@burzum As @ADmad  said, I was reading `SessionAuthenticator.php` at that time and discovered the missing config key.  😃

**Comment by ADmad** [comment]
@littleylv Would you like to make a PR adding the kwy to default config?
