### ISSUE TITLE
Catchable authentication failures

### ISSUE THREAD

**Issue by davidyell** [cakephp/authentication#99]
Apologies in advance if this is outside of scope for the plugin.

## Use-case
I log access to my api into a datastore for various reasons, using my ApiMiddleware. I'd like to log if the request was successful or not, as well as other details about what the request is.

## Hooking the Authentication middleware
Am I able to hook the authentication middleware to see if a response from the auth middleware layer was successfull or not?

Or do I have to build the response in my custom `authorize()` method and return a built response from there with some stuff set which my ApiMiddleware can pickup?

**Comment by davidyell** [comment]
I should probably just log the failure using an alternative method in the `authorize()` method, but using Middleware seems more logical.

**Comment by ADmad** [comment]
The `Result` instance tells you whether authentication was successful or not. So just use `$request->getAttribute('authentication')->getResult()` to get the `Result` instance in your middleware.

**Comment by davidyell** [comment]
You can't do that unfortunately, as the request doesn't have an `authentication` attribute.

**Comment by davidyell** [comment]
This is a very hard thing to achieve.

**Comment by davidyell** [comment]
I found this old article especially enlightening.

http://blog.ircmaxell.com/2016/05/all-about-middleware.html
